// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Sonarr.Infrastructure.Persistence;

#nullable disable

namespace Sonarr.Infrastructure.Migrations
{
    [DbContext(typeof(SonarrDbContext))]
    [Migration("20260727121712_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.ChatGuildState", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_log");

                    b.Property<long>("GlobalClock")
                        .HasColumnType("bigint")
                        .HasColumnName("global_clock");

                    b.Property<string>("RoomMood")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("room_mood");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId")
                        .HasName("pk_guild_state");

                    b.ToTable("guild_state", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.Episode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("HappenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("happened_at");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("quote");

                    b.Property<string>("SentimentTag")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sentiment_tag");

                    b.Property<long>("Turn")
                        .HasColumnType("bigint")
                        .HasColumnName("turn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_episode");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_episode_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("GuildId", "UserId", "HappenedAt")
                        .HasDatabaseName("ix_episode_guild_id_user_id_happened_at");

                    b.ToTable("episode", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.Fact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("LearnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("learned_at");

                    b.Property<long>("LearnedAtTurn")
                        .HasColumnType("bigint")
                        .HasColumnName("learned_at_turn");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("predicate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_fact");

                    b.HasIndex("GuildId", "UserId", "Predicate")
                        .HasDatabaseName("ix_fact_guild_id_user_id_predicate");

                    b.ToTable("fact", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.IntentEmbedding", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("example");

                    b.Property<string>("IntentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("intent_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ContentHash")
                        .HasName("pk_intent_embedding");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_intent_embedding_intent_id");

                    b.ToTable("intent_embedding", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.Person", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("ActivityStack")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("activity_stack");

                    b.Property<string>("AssignedNickname")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assigned_nickname");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DialogueState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dialogue_state");

                    b.Property<string>("FiredLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fired_log");

                    b.Property<long>("LogicalClock")
                        .HasColumnType("bigint")
                        .HasColumnName("logical_clock");

                    b.Property<string>("Registers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("registers");

                    b.Property<string>("RelationshipTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relationship_tier");

                    b.Property<string>("Slots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("slots");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_person");

                    b.ToTable("person", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.RelationshipEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cause");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Delta")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("delta");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("Turn")
                        .HasColumnType("bigint")
                        .HasColumnName("turn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_relationship_event");

                    b.HasIndex("GuildId", "UserId", "At")
                        .HasDatabaseName("ix_relationship_event_guild_id_user_id_at");

                    b.ToTable("relationship_event", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.Stance", b =>
                {
                    b.Property<string>("Topic")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("topic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PoolRef")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pool_ref");

                    b.Property<string>("StanceText")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Topic")
                        .HasName("pk_stance");

                    b.ToTable("stance", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.StanceAgreement", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Topic")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("topic");

                    b.Property<bool>("Agreed")
                        .HasColumnType("boolean")
                        .HasColumnName("agreed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId", "UserId", "Topic")
                        .HasName("pk_stance_agreement");

                    b.HasIndex("Topic")
                        .HasDatabaseName("ix_stance_agreement_topic");

                    b.ToTable("stance_agreement", "chat");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.FeatureFlag", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Feature")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feature");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ChangedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("changed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId", "Feature")
                        .HasName("pk_feature_flag");

                    b.ToTable("feature_flag", "core");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.Guild", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId")
                        .HasName("pk_guild");

                    b.ToTable("guild", "core");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.GuildConfig", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("GuildId", "Key")
                        .HasName("pk_guild_config");

                    b.ToTable("guild_config", "core");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.Job", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("JobId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Recurrence")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("recurrence");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("JobId")
                        .HasName("pk_job");

                    b.HasIndex("Status", "RunAt")
                        .HasDatabaseName("ix_job_status_run_at");

                    b.ToTable("job", "core");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.Member", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<long>("MessageCount")
                        .HasColumnType("bigint")
                        .HasColumnName("message_count");

                    b.Property<string>("Timezone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_member");

                    b.HasIndex("GuildId", "Birthday")
                        .HasDatabaseName("ix_member_guild_id_birthday");

                    b.HasIndex("GuildId", "MessageCount")
                        .HasDatabaseName("ix_member_guild_id_message_count");

                    b.ToTable("member", "core");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.LevelProgress", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("FirstMsgBonusDay")
                        .HasColumnType("date")
                        .HasColumnName("first_msg_bonus_day");

                    b.Property<DateTimeOffset?>("LastMessageXpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_xp_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer")
                        .HasColumnName("streak_days");

                    b.Property<DateOnly?>("StreakLastDay")
                        .HasColumnType("date")
                        .HasColumnName("streak_last_day");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("VoiceSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("voice_seconds");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_progress");

                    b.HasIndex("GuildId", "Xp")
                        .HasDatabaseName("ix_progress_guild_id_xp");

                    b.ToTable("progress", "levels");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.LevelReward", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId", "Level")
                        .HasName("pk_reward");

                    b.ToTable("reward", "levels");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.Season", b =>
                {
                    b.Property<long>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SeasonId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SeasonId")
                        .HasName("pk_season");

                    b.HasIndex("GuildId", "Status")
                        .HasDatabaseName("ix_season_guild_id_status");

                    b.ToTable("season", "levels");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.SeasonResult", b =>
                {
                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasColumnName("season_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("XpEarned")
                        .HasColumnType("bigint")
                        .HasColumnName("xp_earned");

                    b.HasKey("SeasonId", "UserId")
                        .HasName("pk_season_result");

                    b.ToTable("season_result", "levels");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Mod.InfractionSummary", b =>
                {
                    b.Property<long>("BanCount")
                        .HasColumnType("bigint")
                        .HasColumnName("ban_count");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("KickCount")
                        .HasColumnType("bigint")
                        .HasColumnName("kick_count");

                    b.Property<DateTimeOffset?>("LastCaseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_case_at");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<long>("WarnCount")
                        .HasColumnType("bigint")
                        .HasColumnName("warn_count");

                    b.ToTable((string)null);

                    b.ToView("infraction_summary", "mod");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Mod.ModCase", b =>
                {
                    b.Property<long>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("case_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CaseId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CaseId")
                        .HasName("pk_case");

                    b.HasIndex("GuildId", "TargetId")
                        .HasDatabaseName("ix_case_guild_id_target_id");

                    b.ToTable("case", "mod");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.MusicUserPrefs", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Favorites")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("favorites");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.HasKey("GuildId", "UserId")
                        .HasName("pk_user_prefs");

                    b.ToTable("user_prefs", "music");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.PlayHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("requester_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("uri");

                    b.HasKey("Id")
                        .HasName("pk_play_history");

                    b.HasIndex("GuildId", "PlayedAt")
                        .HasDatabaseName("ix_play_history_guild_id_played_at");

                    b.HasIndex("GuildId", "RequesterId")
                        .HasDatabaseName("ix_play_history_guild_id_requester_id");

                    b.ToTable("play_history", "music");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.Playlist", b =>
                {
                    b.Property<long>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("playlist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("PlaylistId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PlaylistId")
                        .HasName("pk_playlist");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_playlist_guild_id_name");

                    b.ToTable("playlist", "music");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.PlaylistTrack", b =>
                {
                    b.Property<long>("PlaylistId")
                        .HasColumnType("bigint")
                        .HasColumnName("playlist_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("AddedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("uri");

                    b.HasKey("PlaylistId", "Position")
                        .HasName("pk_playlist_track");

                    b.ToTable("playlist_track", "music");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.TrackRating", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Uri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("uri");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Vote")
                        .HasColumnType("smallint")
                        .HasColumnName("vote");

                    b.HasKey("GuildId", "Uri", "UserId")
                        .HasName("pk_track_rating");

                    b.ToTable("track_rating", "music", t =>
                        {
                            t.HasCheckConstraint("ck_track_rating_vote", "vote IN (-1, 1)");
                        });
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.Capsule", b =>
                {
                    b.Property<long>("CapsuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("capsule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CapsuleId"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DeliverAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CapsuleId")
                        .HasName("pk_capsule");

                    b.HasIndex("DeliverAt")
                        .HasDatabaseName("ix_capsule_deliver_at");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_capsule_guild_id");

                    b.ToTable("capsule", "social");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.EventRsvp", b =>
                {
                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("response");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EventId", "UserId")
                        .HasName("pk_event_rsvp");

                    b.ToTable("event_rsvp", "social");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.QuoteBoard", b =>
                {
                    b.Property<long>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("quote_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("QuoteId"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<long?>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<long>("SavedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("saved_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("QuoteId")
                        .HasName("pk_quote_board");

                    b.HasIndex("GuildId", "AuthorId")
                        .HasDatabaseName("ix_quote_board_guild_id_author_id");

                    b.ToTable("quote_board", "social");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.SocialEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("EventId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("description");

                    b.Property<long?>("DiscordEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("discord_event_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long?>("PingRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("ping_role_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("EventId")
                        .HasName("pk_event");

                    b.HasIndex("GuildId", "StartsAt")
                        .HasDatabaseName("ix_event_guild_id_starts_at");

                    b.ToTable("event", "social");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TicketId"));

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<long?>("ClosedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<long>("OpenerId")
                        .HasColumnType("bigint")
                        .HasColumnName("opener_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_id");

                    b.Property<string>("TranscriptRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("transcript_ref");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TicketId")
                        .HasName("pk_ticket");

                    b.HasIndex("ThreadId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_thread_id");

                    b.HasIndex("GuildId", "Status")
                        .HasDatabaseName("ix_ticket_guild_id_status");

                    b.ToTable("ticket", "social");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Stats.ActivitySample", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("HourBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hour_bucket");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Messages")
                        .HasColumnType("integer")
                        .HasColumnName("messages");

                    b.Property<int>("OnlineEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("online_estimate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VoiceUsers")
                        .HasColumnType("integer")
                        .HasColumnName("voice_users");

                    b.HasKey("GuildId", "HourBucket")
                        .HasName("pk_activity_sample");

                    b.ToTable("activity_sample", "stats");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Stats.CommandUsage", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Command")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("command");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GuildId", "Command", "Day")
                        .HasName("pk_command_usage");

                    b.ToTable("command_usage", "stats");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Web.LoginToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<IPAddress>("RequestedIp")
                        .HasColumnType("inet")
                        .HasColumnName("requested_ip");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("TokenHash")
                        .HasName("pk_login_token");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_token_expires_at");

                    b.ToTable("login_token", "web");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Web.WebAudit", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<string>("Target")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("target");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId")
                        .HasName("pk_audit");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_audit_at");

                    b.ToTable("audit", "web");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Web.WebSession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("SessionId")
                        .HasName("pk_session");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_session_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_session_user_id");

                    b.ToTable("session", "web");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.StanceAgreement", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Chat.Stance", "Stance")
                        .WithMany("Agreements")
                        .HasForeignKey("Topic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stance_agreement_stance_topic");

                    b.Navigation("Stance");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.GuildConfig", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_config_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Core.Member", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.LevelProgress", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.LevelReward", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reward_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.Season", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.SeasonResult", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Levels.Season", "Season")
                        .WithMany("Results")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_result_season_season_id");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Mod.ModCase", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_case_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.MusicUserPrefs", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_prefs_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.PlayHistory", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_play_history_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.Playlist", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.PlaylistTrack", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Music.Playlist", "Playlist")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlist_track_playlist_playlist_id");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.TrackRating", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_track_rating_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.Capsule", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_capsule_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.EventRsvp", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Social.SocialEvent", "Event")
                        .WithMany("Rsvps")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_rsvp_event_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.QuoteBoard", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_board_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.SocialEvent", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.Ticket", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Stats.ActivitySample", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_sample_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Stats.CommandUsage", b =>
                {
                    b.HasOne("Sonarr.Domain.Entities.Core.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_command_usage_guild_guild_id");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Chat.Stance", b =>
                {
                    b.Navigation("Agreements");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Levels.Season", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Music.Playlist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Sonarr.Domain.Entities.Social.SocialEvent", b =>
                {
                    b.Navigation("Rsvps");
                });
#pragma warning restore 612, 618
        }
    }
}
