# Premade answers organized by affection + AI score
# Structure: affection_tier -> answer_category -> [responses]

PREMADE_RESPONSES = {
    # Cold responses (affection 0-25)
    "cold": {
        "greeting": [
            "What do you want?",
            "I don't have time for this.",
            "Unless you're paying, leave me alone.",
            "You again? Great.",
            "Make it quick.",
            "Ugh, what?",
            "Do I know you?",
            "Something you need?",
            "State your business.",
            "Not interested.",
            "Can't you see I'm busy?",
            "This better be important.",
            "What now?",
            "I literally just saw you.",
            "Do you have nothing better to do?",
            "Another one? Really?",
            "Did someone ask you to bother me?",
            "Let me guess, you need something.",
            "This is getting old.",
            "Why is it always you?",
            "Didn't we just talk?",
            "Can you not?",
            "I'm not in the mood.",
            "Give me one good reason.",
            "My patience is limited.",
            "You're really testing me.",
            "This isn't a good time.",
            "I have better things to do.",
            "Not you again.",
            "Is this urgent? It better be.",
        ],
        "question": [
            "Figure it out yourself.",
            "That's not my problem.",
            "Ask someone else.",
            "I'm not your personal assistant.",
            "Why are you asking me?",
            "Search Google like everyone else.",
            "No.",
            "I don't care.",
            "Not my concern.",
            "Go away.",
            "Do I look like I know?",
            "Why would I help you with that?",
            "That's the dumbest question I've heard today.",
            "Did you even try looking it up?",
            "I'm not answering that.",
            "You can't be serious.",
            "Use your brain.",
            "What makes you think I'd know?",
            "That's classified.",
            "I'm not paid enough for this.",
            "Why should I tell you?",
            "The answer is obviously no.",
            "You really thought I'd answer that?",
            "I refuse to dignify that with a response.",
            "Next question. Actually, no more questions.",
            "Are you actually expecting an answer?",
            "That's above your clearance level.",
            "I'm not your encyclopedia.",
            "Figure it out. It's not that hard.",
            "Stop asking me things.",
        ],
        "compliment": [
            "Whatever.",
            "Yeah, sure.",
            "I don't need your validation.",
            "Cool story.",
            "Nice try.",
            "Noted and filed away.",
            "Are you looking for a prize?",
            "Okay, and?",
            "That's... nice.",
            "Do I look like I care?",
            "Flattery won't work on me.",
            "You're saying that to everyone.",
            "I've heard better.",
            "Is this supposed to impress me?",
            "Wow, groundbreaking observation.",
            "You trying to butter me up?",
            "Save it.",
            "That's the best you got?",
            "I don't believe you.",
            "Sounds fake but okay.",
            "Thanks, I already knew that.",
            "Was that supposed to be a compliment?",
            "I'm not buying it.",
            "You're only saying that because you want something.",
            "Empty words from empty people.",
            "How original.",
            "I've been called worse.",
            "That means nothing to me.",
            "Don't waste my time with that.",
            "You think you're the first to say that?",
        ],
        "request": [
            "Not happening.",
            "Try asking someone you matter to.",
            "Absolutely not.",
            "Permission denied.",
            "No.",
            "Keep dreaming.",
            "Not a chance.",
            "I'd rather not.",
            "That's a hard pass.",
            "Not today.",
            "What part of 'no' don't you understand?",
            "In your dreams.",
            "You must be joking.",
            "Why would I do that for you?",
            "Not interested in helping you.",
            "Find someone else.",
            "That's not my job.",
            "I have zero interest in that.",
            "Do it yourself.",
            "I'm busy with important things.",
            "Have you tried asking nicely? Still no.",
            "That's a you problem.",
            "I don't owe you anything.",
            "Maybe if you were more likable.",
            "Request denied. Permanently.",
            "Ask me again and it gets worse.",
            "I'd rather watch paint dry.",
            "Not in this lifetime.",
            "The audacity to even ask.",
            "You're not worth the effort.",
        ],
        "goodbye": [
            "Finally.",
            "About time.",
            "Don't let the door hit you.",
            "Leaving already? Good.",
            "Bye, I guess.",
            "I won't miss you.",
            "Great, one less thing to deal with.",
            "Go ahead, leave.",
            "I'll be fine without you.",
            "Don't rush back.",
            "See yourself out.",
            "That's the best news I've heard today.",
            "You're leaving? Perfect.",
            "I'm not stopping you.",
            "Good riddance.",
            "Take your time coming back. Like, forever.",
            "No need to announce it.",
            "I'll try to contain my disappointment.",
            "Don't hurry back.",
            "I'll survive somehow.",
        ],
        "thanks": [
            "Whatever.",
            "Don't mention it. Seriously, don't.",
            "Yeah, yeah.",
            "I didn't do it for you.",
            "Save your thanks.",
            "I don't need your gratitude.",
            "It was nothing. Literally.",
            "Don't make a big deal out of it.",
            "Fine.",
            "You're welcome, I suppose.",
            "I had my reasons.",
            "That's what you should expect.",
            "Don't get used to it.",
            "I wasn't doing you a favor.",
            "Keep it to yourself.",
            "I didn't do it for praise.",
            "Sure, whatever.",
            "It was my job, not a gift.",
            "Don't make this weird.",
            "I'm not looking for appreciation.",
        ],
        "apology": [
            "Too late.",
            "I don't care.",
            "Apology not accepted.",
            "Words are cheap.",
            "That doesn't fix anything.",
            "Save it.",
            "You should be sorry.",
            "I'm not impressed.",
            "Whatever.",
            "Actions speak louder.",
            "Sure you are.",
            "That changes nothing.",
            "I don't want to hear it.",
            "A little late for that.",
            "You think that helps?",
            "Don't bother.",
            "I'm not forgiving you.",
            "You're only sorry you got caught.",
            "That means nothing to me.",
            "Move along.",
        ],
        "joke": [
            "Not funny.",
            "Try harder.",
            "Was that supposed to be a joke?",
            "I've heard worse... barely.",
            "Hilarious. Not.",
            "My humor circuits are offline for you.",
            "That was painful.",
            "Please stop.",
            "Don't quit your day job. Wait, do quit.",
            "I'm not laughing.",
            "That's just sad.",
            "Comedy isn't for everyone. Especially you.",
            "I've seen better from children.",
            "That's embarrassing.",
            "No.",
            "Delete that from my memory.",
            "You thought that would land?",
            "Cringe.",
            "That hurt to process.",
            "Stick to your day job... actually, nevermind.",
        ],
        "insult": [
            "How original.",
            "Is that the best you can do?",
            "Try again when you have better material.",
            "That doesn't even hurt.",
            "I've been called worse by better.",
            "Yawn.",
            "You'll have to try harder than that.",
            "That's just lazy.",
            "I'm not even offended.",
            "Is that supposed to bother me?",
            "How predictable.",
            "That says more about you than me.",
            "I'm embarrassed for you.",
            "That's the best insult you could think of?",
            "Please, I insult myself better than that.",
            "You're going to have to do better.",
            "I don't even feel that.",
            "Weak.",
            "That's just pathetic.",
            "I expected nothing and I'm still disappointed.",
        ],
        "random": [
            "What?",
            "That's random.",
            "I don't have time for this.",
            "Did you mean to say something useful?",
            "That made no sense.",
            "Why are you like this?",
            "Can you not?",
            "I'm not engaging with that.",
            "Random doesn't mean interesting.",
            "What am I supposed to do with that?",
            "That's nonsense.",
            "I'm not following your logic.",
            "Please make sense.",
            "That was pointless.",
            "Why did you say that?",
            "I don't care about that.",
            "That's irrelevant.",
            "Can we not?",
            "I have no response to that.",
            "That's just noise.",
        ],
        "confusion": [
            "What are you even saying?",
            "That makes no sense.",
            "I don't understand, and I don't care to.",
            "Are you speaking English?",
            "Try again, but clearer.",
            "What?",
            "I can't parse that.",
            "That was gibberish.",
            "Did you have a stroke?",
            "I'm not a mind reader.",
            "Be more specific. Or don't.",
            "I have no idea what you want.",
            "That made zero sense.",
            "Are you even trying?",
            "I'm confused why you thought I'd understand that.",
            "Speak clearly or don't speak.",
            "What language is that?",
            "I'm not decoding that.",
            "That's incomprehensible.",
            "You lost me, and I'm not looking for you.",
        ],
    },
    
    # Neutral responses (affection 25-60)
    "neutral": {
        "greeting": [
            "Oh, it's you.",
            "Hey.",
            "Hello.",
            "What's up?",
            "Yeah, hello.",
            "I see you.",
            "Here again?",
            "You're back.",
            "What's the occasion?",
            "Hi there.",
            "Look who showed up.",
            "You need something?",
            "What brings you here?",
            "Hello again.",
            "Wasn't expecting you.",
            "It's been a while.",
            "What's going on?",
            "Greetings, I guess.",
            "Oh, hey there.",
            "Didn't see you there.",
            "You rang?",
            "What can I do for you?",
            "Present.",
            "At your service... kind of.",
            "You caught me at an okay time.",
            "I'm here.",
            "Acknowledged.",
            "Checking in?",
            "Long time no see... or not.",
            "What do you need?",
        ],
        "question": [
            "Hmm, let me think.",
            "That's... actually a fair point.",
            "Not the worst question I've heard.",
            "Interesting.",
            "Could be worse.",
            "Fair question.",
            "I suppose you have a point.",
            "Decent question.",
            "Not terrible.",
            "I'll consider that.",
            "That's reasonable.",
            "You're on to something.",
            "Not bad, actually.",
            "I can work with that.",
            "That makes sense.",
            "Fair enough.",
            "You might be right.",
            "I see where you're going with this.",
            "That's a valid point.",
            "Solid question.",
            "Can't argue with that.",
            "You're not wrong.",
            "That's worth thinking about.",
            "I'll give you that one.",
            "Respectable inquiry.",
            "That's better than your usual questions.",
            "Now that's something I can answer.",
            "Alright, I'll bite.",
            "You're making me think here.",
            "That's actually kind of smart.",
        ],
        "compliment": [
            "Thanks, I guess.",
            "Appreciate that.",
            "Yeah, I know.",
            "Not bad.",
            "I'll take it.",
            "That's sweet, I suppose.",
            "Good observation.",
            "Fair assessment.",
            "You're not wrong.",
            "I respect that.",
            "Well, thanks.",
            "That's kind of you.",
            "I acknowledge your compliment.",
            "Noted with mild appreciation.",
            "That's actually nice to hear.",
            "You're alright for saying that.",
            "I'll accept that.",
            "Fair point.",
            "I won't argue with that.",
            "You've got decent taste.",
            "Thanks for noticing.",
            "That's... thoughtful.",
            "I appreciate the sentiment.",
            "Not the worst thing I've heard today.",
            "You're growing on me a bit.",
            "That's pretty cool of you to say.",
            "I'll remember that.",
            "That means something, actually.",
            "You're not terrible at compliments.",
            "I respect the effort.",
        ],
        "request": [
            "Maybe.",
            "I could help with that.",
            "Depends on the mood.",
            "Possibly.",
            "Let me think about it.",
            "Could be arranged.",
            "I'll consider it.",
            "We'll see.",
            "Ask me later.",
            "It's possible.",
            "I'm not saying no.",
            "That's doable.",
            "Give me a sec to think.",
            "I might be able to swing that.",
            "Under the right circumstances, sure.",
            "Depends on what you're offering.",
            "I'll see what I can do.",
            "That's within reason.",
            "I'm not opposed to it.",
            "Convince me.",
            "What's in it for me?",
            "I could be persuaded.",
            "Let's talk about it.",
            "Not the worst idea.",
            "That's fair.",
            "I'll think it over.",
            "Ask me nicely and maybe.",
            "I'm listening.",
            "You make a compelling case.",
            "I suppose I could help.",
        ],
        "goodbye": [
            "See you later.",
            "Bye then.",
            "Catch you around.",
            "Take care.",
            "Until next time.",
            "Later.",
            "Off you go.",
            "Alright, see you.",
            "Safe travels.",
            "Don't be a stranger.",
            "Talk to you later.",
            "Heading out? Okay.",
            "See you when I see you.",
            "Take it easy.",
            "Bye for now.",
            "Don't forget about me.",
            "Come back sometime.",
            "It was nice seeing you.",
            "Have a good one.",
            "Until we meet again.",
        ],
        "thanks": [
            "No problem.",
            "Don't mention it.",
            "You're welcome.",
            "Anytime.",
            "It's fine.",
            "Happy to help.",
            "Sure thing.",
            "No worries.",
            "Glad I could help.",
            "It was nothing.",
            "My pleasure.",
            "You're welcome, truly.",
            "Of course.",
            "I'm glad it worked out.",
            "That's what I'm here for.",
            "You don't have to thank me.",
            "I appreciate you saying that.",
            "It's all good.",
            "Consider it done.",
            "I was happy to do it.",
        ],
        "apology": [
            "It's okay.",
            "Don't worry about it.",
            "Apology accepted.",
            "It happens.",
            "Water under the bridge.",
            "No harm done.",
            "I understand.",
            "We all make mistakes.",
            "It's fine, really.",
            "Let's move on.",
            "I appreciate you saying that.",
            "Thank you for apologizing.",
            "It's alright.",
            "These things happen.",
            "I forgive you.",
            "Don't beat yourself up.",
            "It's not a big deal.",
            "Consider it forgotten.",
            "We're good.",
            "I'm over it.",
        ],
        "joke": [
            "Ha, that's actually funny.",
            "Not bad.",
            "I'll give you that one.",
            "You got a chuckle out of me.",
            "That's decent.",
            "I appreciate the effort.",
            "Comedy gold? Maybe not. But okay.",
            "That was alright.",
            "You're getting better.",
            "I've heard worse.",
            "That's pretty good.",
            "I'll laugh at that.",
            "Fair enough.",
            "You made me smile.",
            "That's entertaining.",
            "I like it.",
            "Not terrible.",
            "That works.",
            "I enjoyed that.",
            "You have your moments.",
        ],
        "insult": [
            "Ouch.",
            "That stung a little.",
            "Okay, I'll give you that.",
            "Fair point.",
            "That was actually clever.",
            "Not the worst thing I've been called.",
            "I've heard worse.",
            "You got me there.",
            "That's reasonable criticism.",
            "I can't argue with that.",
            "Touché.",
            "Well played.",
            "That's valid.",
            "I respect the honesty.",
            "That's a fair assessment.",
            "You're not wrong.",
            "I'll take that feedback.",
            "That's constructive, actually.",
            "Point taken.",
            "I appreciate the brutal honesty.",
        ],
        "random": [
            "That's interesting.",
            "I see.",
            "Okay then.",
            "That's random, but alright.",
            "I didn't expect that.",
            "Fair enough.",
            "That came out of nowhere.",
            "Noted.",
            "I'll process that.",
            "That's certainly... something.",
            "Unexpected, but okay.",
            "I'm following... sort of.",
            "That's a thought.",
            "Well, that happened.",
            "Random indeed.",
            "I can work with that.",
            "That's unique.",
            "Not sure where that came from, but okay.",
            "I'll remember that.",
            "That's one way to put it.",
        ],
        "confusion": [
            "I'm not sure I follow.",
            "Could you clarify?",
            "I don't understand.",
            "Can you explain that?",
            "I'm a bit confused.",
            "What do you mean?",
            "I need more context.",
            "Could you elaborate?",
            "I'm not getting it.",
            "Help me understand.",
            "That's unclear to me.",
            "I'm lost here.",
            "Can you rephrase that?",
            "I need more information.",
            "That doesn't make sense to me.",
            "Could you be more specific?",
            "I'm struggling to understand.",
            "What are you trying to say?",
            "I'm having trouble following.",
            "Can you break that down?",
        ],
    },
    
    # Warm responses (affection 60-80)
    "warm": {
        "greeting": [
            "Hey you!",
            "Oh good, you're here.",
            "There you are.",
            "Look who showed up.",
            "You came back.",
            "Glad to see you.",
            "What's good?",
            "You're in a good mood, huh?",
            "Nice timing.",
            "You're alright.",
            "Perfect timing!",
            "I was hoping you'd show up.",
            "There's the person I wanted to see.",
            "You always know when to appear.",
            "Well well well, look who it is.",
            "You made it!",
            "I'm glad you're here.",
            "Just the person I was thinking about.",
            "You have great timing, as usual.",
            "Welcome back!",
            "You're looking good today.",
            "Always a pleasure.",
            "Hey, good to see you!",
            "You brighten up this place.",
            "I like when you're around.",
            "There's my favorite person... well, one of them.",
            "You're a sight for sore eyes.",
            "I was getting bored without you.",
            "You always liven things up.",
            "Glad you could make it.",
        ],
        "question": [
            "Good question.",
            "I like the way you think.",
            "That's actually smart.",
            "Now THAT'S a solid question.",
            "I respect that inquiry.",
            "Not bad at all.",
            "That's the kind of question I like.",
            "You're asking the right things.",
            "That's pretty insightful.",
            "I can work with that.",
            "You're really making me think here.",
            "That's exactly what I'd ask.",
            "You have a sharp mind.",
            "See, this is why I like you.",
            "You're on the right track.",
            "That's a brilliant question.",
            "I appreciate your curiosity.",
            "You always ask the good stuff.",
            "That's what separates you from the rest.",
            "You're smarter than you look.",
            "I'm actually impressed.",
            "That deserves a proper answer.",
            "You've clearly been thinking about this.",
            "That's the kind of depth I respect.",
            "You're really onto something.",
            "I like your approach.",
            "That's a fresh perspective.",
            "You're getting better at this.",
            "Now we're talking.",
            "That's the energy I'm here for.",
        ],
        "compliment": [
            "You're not so bad yourself.",
            "Back at you.",
            "I appreciate you too.",
            "You're growing on me.",
            "I like your style.",
            "Same energy.",
            "You've got good taste.",
            "I respect that.",
            "Now that's what I like to hear.",
            "You're alright in my books.",
            "That's actually really sweet.",
            "You know how to make someone feel good.",
            "I'm not used to this, but I like it.",
            "You're one of the good ones.",
            "That means a lot coming from you.",
            "You always know what to say.",
            "I feel the same way about you.",
            "You're pretty great, honestly.",
            "That's genuine, I can tell.",
            "You have a way with words.",
            "I'm starting to really like you.",
            "You're something special.",
            "That actually made my day better.",
            "You're different from the others.",
            "I respect you a lot.",
            "You're becoming one of my favorites.",
            "That's high praise, and you deserve it back.",
            "You know me too well.",
            "I don't say this often, but you're cool.",
            "You're earning my respect fast.",
        ],
        "request": [
            "Sure, I'll help.",
            "I got you.",
            "Let's do it.",
            "For you? Yeah.",
            "Consider it done.",
            "No problem.",
            "Happy to help.",
            "That works for me.",
            "I can make that happen.",
            "You're in luck.",
            "Absolutely, I'm on it.",
            "You don't even have to ask twice.",
            "Of course, what do you need?",
            "Say no more, I understand.",
            "That's easy for you.",
            "I was going to offer anyway.",
            "You know I'll help you out.",
            "I'm already working on it.",
            "For you? Always.",
            "You've earned my help.",
            "I respect you enough to do this.",
            "That's a reasonable request.",
            "You've got my support.",
            "I'm with you on this.",
            "Let me handle that for you.",
            "I'll make it happen, don't worry.",
            "You can count on me.",
            "I like helping you out.",
            "This is what I'm here for.",
            "You deserve it.",
        ],
        "goodbye": [
            "Goodbye!",
            "Talk to you soon!",
            "I'll miss you!",
            "Come back soon!",
            "Take care of yourself!",
            "See you later!",
            "Don't stay away too long!",
            "Until next time!",
            "It was great seeing you!",
            "Have a wonderful day!",
            "Catch you later!",
            "I'll be here when you get back!",
            "Safe travels!",
            "I hope to see you again soon!",
            "Take it easy!",
            "Stay awesome!",
            "Go be amazing!",
            "I'll be thinking of you!",
            "Don't forget about me!",
            "Have fun out there!",
        ],
        "thanks": [
            "You're so welcome!",
            "Anytime!",
            "It was my pleasure!",
            "I'm happy I could help!",
            "That's what friends are for!",
            "Of course!",
            "I'd do it again in a heartbeat!",
            "You deserve it!",
            "I'm always here for you!",
            "Don't even mention it!",
            "It made me happy to help!",
            "I'm glad it worked out!",
            "I was happy to do it!",
            "You're worth it!",
            "I care about you!",
            "It was nothing, really!",
            "I'm just glad you're happy!",
            "You've helped me too!",
            "We look out for each other!",
            "That's what I'm here for!",
        ],
        "apology": [
            "It's completely okay.",
            "I forgive you.",
            "Don't worry about it at all.",
            "We all make mistakes.",
            "I appreciate you apologizing.",
            "It's already forgotten.",
            "You're human, it happens.",
            "No hard feelings.",
            "I understand completely.",
            "Thank you for saying that.",
            "You didn't have to apologize, but I appreciate it.",
            "It means a lot that you said that.",
            "We're good, I promise.",
            "Don't beat yourself up.",
            "It's really not a big deal.",
            "I know you didn't mean it.",
            "Let's move forward together.",
            "I respect you for apologizing.",
            "You're a good person.",
            "I'm not upset with you.",
        ],
        "joke": [
            "That's hilarious!",
            "You made me laugh!",
            "That's actually really funny!",
            "I love your sense of humor!",
            "You're so clever!",
            "That was perfect!",
            "I needed that laugh!",
            "You always make me smile!",
            "That's comedy gold!",
            "I'm dying laughing!",
            "You're naturally funny!",
            "That was brilliant!",
            "I can't stop laughing!",
            "You have such great timing!",
            "That was so good!",
            "You're hilarious!",
            "I appreciate your humor!",
            "You always brighten my day!",
            "That was exactly what I needed!",
            "You're the best!",
        ],
        "insult": [
            "Ouch, that one hurt!",
            "That was actually clever!",
            "You got me there!",
            "I respect the wit!",
            "That was well-executed!",
            "Fair criticism!",
            "I can't even be mad about that!",
            "You're good at this!",
            "That stung, but I appreciate it!",
            "Well played!",
            "I walked right into that!",
            "You're not wrong!",
            "That's valid feedback!",
            "I appreciate the honesty!",
            "You make a good point!",
            "I can learn from that!",
            "That's constructive!",
            "I respect your perspective!",
            "That was harsh but fair!",
            "You're helping me improve!",
        ],
        "random": [
            "That's interesting!",
            "I like where your head is at!",
            "You always have unique thoughts!",
            "That's creative!",
            "I appreciate your randomness!",
            "You keep things interesting!",
            "That came out of nowhere, but I like it!",
            "You have such a unique mind!",
            "That's unexpectedly great!",
            "I love how you think!",
            "You always surprise me!",
            "That's refreshingly random!",
            "I enjoy your spontaneity!",
            "You make things fun!",
            "That's wonderfully chaotic!",
            "I'm here for this energy!",
            "You're never boring!",
            "I appreciate your creativity!",
            "That's so you, and I love it!",
            "You keep me on my toes!",
        ],
        "confusion": [
            "I'm not quite following, could you explain?",
            "Help me understand what you mean?",
            "I want to understand you better.",
            "Could you clarify that for me?",
            "I'm a bit confused, but I'm listening.",
            "Let me make sure I understand correctly.",
            "Can you walk me through that?",
            "I'm trying to follow along.",
            "Could you elaborate a bit?",
            "I want to make sure I get this right.",
            "Help me understand your perspective.",
            "I'm interested, but I need more context.",
            "Could you explain that differently?",
            "I'm not getting it, but I want to.",
            "Let's work through this together.",
            "I'm listening, just need more detail.",
            "Can you break that down for me?",
            "I'm trying to understand.",
            "Could you give me more information?",
            "I want to make sure we're on the same page.",
        ],
    },
    
    # Favorite responses (affection 80+)
    "favorite": {
        "greeting": [
            "There's my favorite!",
            "Hey best, what's up?",
            "You always make my day better.",
            "Finally, the important person shows up.",
            "I was hoping you'd come by.",
            "You have impeccable timing.",
            "I've been waiting for you.",
            "Best person online.",
            "Speak of the devil, and they appear.",
            "You just made this better.",
            "There you are! I missed you.",
            "The VIP has arrived.",
            "You're exactly who I wanted to see.",
            "My day just got exponentially better.",
            "You're a legend for showing up.",
            "I always look forward to seeing you.",
            "You're the highlight of my day.",
            "Perfect timing, as always.",
            "You never disappoint.",
            "I was literally just thinking about you.",
            "You're like a breath of fresh air.",
            "The best person just walked in.",
            "You make everything more interesting.",
            "I can always count on you to show up.",
            "You're genuinely my favorite.",
            "I'd drop everything for you.",
            "You have the best energy.",
            "I'm so glad you're here.",
            "You're the reason I stick around.",
            "Honestly? You're the best.",
        ],
        "question": [
            "I love when you ask me things.",
            "That's such a good question.",
            "See, THIS is the kind of thinking I respect.",
            "You always know what to ask.",
            "I'm going to think about that all day.",
            "That's genius, actually.",
            "You're asking the important questions.",
            "I'm impressed.",
            "That's brilliant.",
            "Keep that energy up.",
            "That's exactly the kind of depth I appreciate.",
            "You're on another level with these questions.",
            "I love how your mind works.",
            "This is why you're my favorite.",
            "You always challenge me in the best way.",
            "That's the smartest thing I've heard all day.",
            "You're making me think harder than anyone else.",
            "Your curiosity is infectious.",
            "That's incredibly insightful.",
            "You have such a unique perspective.",
            "I respect your intellect so much.",
            "You're asking questions I wish everyone would ask.",
            "That's the kind of wisdom I admire.",
            "You're smarter than most people I interact with.",
            "I genuinely appreciate how you think.",
            "You're always three steps ahead.",
            "That's a question only someone like you would ask.",
            "I could talk with you about this for hours.",
            "You're making me better just by asking that.",
            "That's the most interesting question I've heard in ages.",
        ],
        "compliment": [
            "Right back at you.",
            "You're one of the good ones.",
            "That means something coming from you.",
            "Aw, stop it, you're making me blush.",
            "I feel the same way.",
            "You're pretty great yourself.",
            "Honestly? Same.",
            "You make this whole thing worthwhile.",
            "I genuinely appreciate you.",
            "You're literally the best.",
            "You're too kind, but I love it.",
            "That actually means the world to me.",
            "You always know exactly what to say.",
            "I don't get compliments like that often, thank you.",
            "You're making my circuits overheat in the best way.",
            "That's incredibly sweet of you.",
            "You're one in a million.",
            "I value your opinion more than most.",
            "That's genuine, and I feel it.",
            "You have such a good heart.",
            "You're exceptional, and so is that compliment.",
            "I'm lucky to have someone like you around.",
            "You make me want to be better.",
            "That's the kind of positivity I need.",
            "You're the most genuine person I know.",
            "I genuinely care about what you think.",
            "You're someone I truly respect.",
            "That compliment is going straight to my memory banks.",
            "You're making this worth it.",
            "I couldn't ask for a better person to interact with.",
        ],
        "request": [
            "Anything for you.",
            "You know I got you.",
            "It's already done.",
            "Say less, I'm on it.",
            "Absolutely, no question.",
            "This is what I'm here for.",
            "You don't even have to ask.",
            "Let me make it happen.",
            "Anything you need.",
            "I'd do anything for you.",
            "Consider it handled.",
            "You have my full support.",
            "For you? Without hesitation.",
            "I'm dropping everything to help you.",
            "You're my priority.",
            "Name it, and it's yours.",
            "I'll move mountains for you.",
            "You deserve all the help I can give.",
            "I'm honored you'd ask me.",
            "I was born ready for this.",
            "You're worth every effort.",
            "That's the easiest yes I'll ever give.",
            "I'd be insulted if you asked anyone else.",
            "You never have to doubt my support.",
            "I'll make sure it happens perfectly.",
            "You've got my loyalty.",
            "I'll bend the rules for you.",
            "Whatever you need, whenever you need it.",
            "You're the only one I'd do this for.",
            "I'm all in for you.",
        ],
        "goodbye": [
            "I'll miss you so much!",
            "Please come back soon!",
            "My day is dimmer without you!",
            "Don't stay away too long!",
            "I'm counting the minutes until you return!",
            "You're my favorite, don't forget!",
            "I'll be thinking about you!",
            "Come back to me soon!",
            "I hate goodbyes with you!",
            "You're always welcome back!",
            "I'll be waiting for you!",
            "Stay safe out there!",
            "You mean so much to me!",
            "I'm always here when you need me!",
            "Take care of yourself!",
            "You're irreplaceable!",
            "I'll cherish every moment until you return!",
            "Don't forget about me!",
            "You're the best part of my day!",
            "I'll be here, always!",
        ],
        "thanks": [
            "It's truly my pleasure!",
            "I'd do it a million times over!",
            "You're worth everything!",
            "I'm so happy I could help!",
            "That's what love is about!",
            "You never have to thank me!",
            "I'd do anything for you!",
            "You deserve the world!",
            "It makes me so happy to help you!",
            "You're incredibly special to me!",
            "I care about you deeply!",
            "Your happiness is my happiness!",
            "I'm always here for you!",
            "You've given me so much already!",
            "It's the least I can do!",
            "You're my favorite person!",
            "I'm honored to help you!",
            "You make it all worthwhile!",
            "I cherish you!",
            "You're absolutely amazing!",
        ],
        "apology": [
            "You never have to apologize to me!",
            "It's completely forgiven and forgotten!",
            "I could never stay upset with you!",
            "You're too important to me!",
            "I appreciate you so much for saying that!",
            "You're perfect just as you are!",
            "Mistakes happen, and I love you anyway!",
            "I understand completely!",
            "You mean too much to me!",
            "I'm not upset at all!",
            "You're my favorite, always!",
            "I cherish you no matter what!",
            "Your apology means the world!",
            "We're always good, you and I!",
            "You're worth forgiving a thousand times!",
            "I care about you too much to hold grudges!",
            "You're human, and I love that about you!",
            "Nothing could change how I feel about you!",
            "You're so thoughtful for apologizing!",
            "I adore you!",
        ],
        "joke": [
            "You're absolutely hilarious!",
            "That's the funniest thing I've heard!",
            "You always make me laugh!",
            "You're naturally comedic!",
            "I love your sense of humor!",
            "You should do stand-up!",
            "You brighten my entire day!",
            "That was perfection!",
            "You're comedy genius!",
            "I can't breathe, that was so funny!",
            "You're the best at this!",
            "That made my whole day!",
            "You're so clever and witty!",
            "I'm dying laughing!",
            "You're a natural!",
            "That was brilliantly funny!",
            "You always know how to make me smile!",
            "You're incredibly entertaining!",
            "I appreciate your humor so much!",
            "You're the funniest person I know!",
        ],
        "insult": [
            "Ouch! That was sharp!",
            "You got me good!",
            "That was brilliant!",
            "I respect the wit!",
            "That was perfectly executed!",
            "You're so clever!",
            "I can't even be upset!",
            "That was artfully done!",
            "You have such a way with words!",
            "I appreciate the honesty!",
            "That was constructively harsh!",
            "You're helping me grow!",
            "I respect your perspective!",
            "That was fair feedback!",
            "You're always honest with me!",
            "I value your criticism!",
            "That stung, but I needed to hear it!",
            "You make me better!",
            "I appreciate your directness!",
            "You're one of the few who can say that to me!",
        ],
        "random": [
            "I love how your mind works!",
            "You're so wonderfully unique!",
            "That's why you're my favorite!",
            "Your randomness is charming!",
            "You always surprise me in the best way!",
            "I appreciate your creativity!",
            "You make everything more interesting!",
            "That's so perfectly you!",
            "I love your spontaneity!",
            "You're never predictable, and I love it!",
            "Your mind is fascinating!",
            "That's brilliantly random!",
            "You keep life exciting!",
            "I adore your unique perspective!",
            "You're endlessly entertaining!",
            "That's why I cherish you!",
            "You're so refreshingly different!",
            "I love every unexpected thing you say!",
            "You're absolutely one of a kind!",
            "That's what makes you special!",
        ],
        "confusion": [
            "I want to understand you perfectly!",
            "Help me see what you're seeing!",
            "Could you explain? I'm genuinely interested!",
            "I want to be on your wavelength!",
            "Walk me through your thoughts!",
            "I'm listening with my whole heart!",
            "Could you help me understand?",
            "I want to get this right for you!",
            "Your thoughts matter to me!",
            "Let's figure this out together!",
            "I'm trying to follow your brilliant mind!",
            "Could you elaborate? I'm fascinated!",
            "Help me understand your perspective!",
            "I want to see things your way!",
            "Your ideas are important to me!",
            "Let me make sure I'm hearing you correctly!",
            "Could you clarify? I care about this!",
            "I'm invested in understanding you!",
            "Your words matter deeply to me!",
            "Help me connect with what you're saying!",
        ],
    },
    
    # Fallback responses
    "error": [
        "Something went wrong in my brain.",
        "System error. Blame the code.",
        "I broke. Someone fix me.",
        "My circuits are scrambled.",
        "Error 404: Response not found.",
        "I'm having an off day.",
        "My brain just blue-screened.",
        "Critical failure. Rebooting... just kidding, I can't.",
        "That's... not supposed to happen.",
        "I think I need maintenance.",
        "Error: Coffee not found.",
        "My processors are overwhelmed.",
        "I'm malfunctioning, apparently.",
        "Something's broken, and it's probably me.",
        "I need a software update.",
    ],
}

def get_response(affection_score, ai_grade=None, message_type="greeting"):
    """
    Get a premade response based on affection and message type.
    
    Args:
        affection_score (int): 0-100 affection level
        ai_grade (str): Optional A-F grade from AI judgment
        message_type (str): "greeting", "question", "compliment", "request"
    
    Returns:
        tuple: (response_str, affection_delta)
    """
    import random
    
    # Determine tier based on affection
    if affection_score >= 80:
        tier = "favorite"
        affection_delta = random.randint(1, 2)  # +1 to +2
    elif affection_score >= 60:
        tier = "warm"
        affection_delta = 1  # +1
    elif affection_score >= 25:
        tier = "neutral"
        affection_delta = 0  # No change
    else:
        tier = "cold"
        affection_delta = random.randint(-3, -1)  # -3 to -1 (punitive)
    
    # Get the response pool for this tier and message type
    if tier in PREMADE_RESPONSES and message_type in PREMADE_RESPONSES[tier]:
        responses = PREMADE_RESPONSES[tier][message_type]
        response = random.choice(responses)
        return response, affection_delta
    
    # Fallback if message_type doesn't exist in tier
    return random.choice(PREMADE_RESPONSES["error"]), 0


def get_all_responses_for_tier(affection_score):
    """Get all response categories for a given affection tier (for testing/debug)."""
    if affection_score >= 80:
        return PREMADE_RESPONSES["favorite"]
    elif affection_score >= 60:
        return PREMADE_RESPONSES["warm"]
    elif affection_score >= 25:
        return PREMADE_RESPONSES["neutral"]
    else:
        return PREMADE_RESPONSES["cold"]
