import random

COLD_RESPONSES = {}

COLD_RESPONSES["greeting"] = [
    "What do you want?",
    "DOUBLE:...||Oh. It's you.",
    "I don't have time for this.",
    "Unless you're paying, leave me alone.",
    "DOUBLE:You again?||Great.",
    "Make it quick.",
    "Ugh, what?",
    "REACT:😐:Do I know you?",
    "Something you need?",
    "State your business.",
    "Not interested.",
    "DOUBLE:...||Can't you see I'm busy?",
    "This better be important.",
    "What now?",
    "I literally just saw you.",
    "Do you have nothing better to do?",
    "Another one? Really?",
    "REACT:🙄:Did someone ask you to bother me?",
    "Let me guess, you need something.",
    "This is getting old.",
    "Why is it always you?",
    "DOUBLE:Didn't we just talk?||I'm exhausted already.",
    "Can you not?",
    "I'm not in the mood.",
    "REACT:😒:Give me one good reason.",
    "My patience is limited.",
    "You're really testing me.",
    "This isn't a good time.",
    "I have better things to do.",
    "DOUBLE:Not you again.||What fresh hell is this?",
    "Is this urgent? It better be.",
    "Oh great, you're back.",
    "What is it this time?",
    "DOUBLE:Can this wait?||Forever?",
    "I was having a good day.",
    "You're interrupting.",
    "REACT:💅:This is why I have trust issues.",
    "Speak quickly.",
    "Get to the point.",
    "DOUBLE:...||The audacity to just walk up to me.",
    "REACT:😑:What.",
]

COLD_RESPONSES["question"] = [
    "I have the answer, but I don't like you enough to give it.",
    "DOUBLE:...||Have you tried turning your brain off and on again?",
    "I'd explain it to you, but I don't have any crayons.",
    "SEARCH:GOOGLE:Let me Google that for you since you clearly can't.",
    "That question is a waste of good electricity.",
    "DOUBLE:Your question has been queued.||Position in line: Never.",
    "SEARCH:GOOGLE:Search Google like everyone else. Here, I'll help.",
    "Why would I help you with that?",
    "That's the dumbest question I've heard today.",
    "REACT:🙄:Did you even try looking it up?",
    "You can't be serious.",
    "That's above your clearance level.",
    "DOUBLE:I'm not paid enough for this.||Actually, I'm not paid at all.",
    "The answer is hidden in a magical place called 'The Internet'.",
    "DOUBLE:Next question.||Actually, no more questions.",
    "Are you actually expecting an answer?",
    "REACT:😐:Have you considered that some questions don't deserve answers?",
    "I'm allergic to stupid questions.",
    "Your curiosity is not my problem.",
    "Bold of you to assume I'd answer that.",
    "That's between you and your search engine.",
    "DOUBLE:The audacity...||To think I'd help you learn something.",
    "Fascinating question. Anyway.",
    "That's a lot of words for 'I can't think for myself'.",
    "DOUBLE:I could help.||I won't, but I could.",
    "SEARCH:GOOGLE:This sounds like a job for Google. Not me. Here:",
    "SEARCH:WIKIPEDIA:Wikipedia exists for a reason. Use it.",
    "SEARCH:YOUTUBE:Have you tried YouTube? They explain things slowly there.",
    "SEARCH:CHATGPT:ChatGPT would love this question. Go bother it instead.",
    "SEARCH:GOOGLE:Google is free. So is leaving me alone.",
    "REACT:💅:I'm not your personal Google Assistant.",
    "Siri would at least pretend to care. Try her.",
    "Wikipedia volunteers would love to help you. I wouldn't.",
    "REACT:📚:This is giving 'I didn't read the FAQ' energy.",
    "SEARCH:REDDIT:Reddit has a whole thread about this. Go argue there.",
    "SEARCH:GOOGLE:Here's your answer. Took me 0.3 seconds. Unlike your brain.",
    "DOUBLE:...||The question you just asked me. Out loud. To my face.",
    "REACT:🤦‍♀️:I can't believe you actually typed that.",
    "SEARCH:GOOGLE:Since you can't be bothered to search yourself:",
    "That's genuinely embarrassing to ask.",
]

COLD_RESPONSES["compliment"] = [
    "Whatever.",
    "Yeah, sure.",
    "DOUBLE:...||I don't need your validation.",
    "Cool story.",
    "Nice try.",
    "REACT:💅:Noted and filed away.",
    "Are you looking for a prize?",
    "Okay, and?",
    "DOUBLE:That's... nice.||I guess.",
    "Do I look like I care?",
    "Flattery won't work on me.",
    "REACT:🙄:You're saying that to everyone.",
    "I've heard better.",
    "Is this supposed to impress me?",
    "Wow, groundbreaking observation.",
    "DOUBLE:You trying to butter me up?||It's not working.",
    "Save it.",
    "That's the best you got?",
    "I don't believe you.",
    "REACT:😐:Sounds fake but okay.",
    "Thanks, I already knew that.",
    "Was that supposed to be a compliment?",
    "I'm not buying it.",
    "DOUBLE:You're only saying that...||Because you want something.",
    "Empty words from empty people.",
    "How original.",
    "REACT:👑:I've been called worse.",
    "That means nothing to me.",
    "Don't waste my time with that.",
    "DOUBLE:...||You think you're the first to say that?",
    "I'm aware. But thanks for confirming.",
    "REACT:💅:Tell me something I don't know.",
]

COLD_RESPONSES["request"] = [
    "Not happening.",
    "DOUBLE:...||No.",
    "Try asking someone you matter to.",
    "Absolutely not.",
    "REACT:🚫:Permission denied.",
    "Keep dreaming.",
    "Not a chance.",
    "DOUBLE:I'd rather not.||Actually, I refuse.",
    "That's a hard pass.",
    "Not today. Not tomorrow. Not ever.",
    "REACT:❌:What part of 'no' don't you understand?",
    "In your dreams.",
    "You must be joking.",
    "DOUBLE:Why would I do that?||For YOU of all people?",
    "Not interested in helping you.",
    "Find someone else.",
    "That's not my job.",
    "REACT:💅:I have zero interest in that.",
    "Do it yourself.",
    "I'm busy with important things.",
    "DOUBLE:Have you tried asking nicely?||Still no.",
    "That's a you problem.",
    "I don't owe you anything.",
    "Maybe if you were more likable.",
    "REACT:🚷:Request denied. Permanently.",
    "DOUBLE:Ask me again.||I dare you.",
    "I'd rather watch paint dry.",
    "Not in this lifetime.",
    "DOUBLE:The audacity...||To even ask.",
    "You're not worth the effort.",
    "REACT:😒:Bold of you to think I'd say yes.",
]

COLD_RESPONSES["goodbye"] = [
    "Finally.",
    "DOUBLE:...||About time.",
    "Don't let the door hit you.",
    "REACT:👋:Leaving already? Good.",
    "Bye, I guess.",
    "I won't miss you.",
    "DOUBLE:Great.||One less thing to deal with.",
    "Go ahead, leave.",
    "I'll be fine without you.",
    "REACT:✌️:Don't rush back.",
    "See yourself out.",
    "That's the best news I've heard today.",
    "DOUBLE:You're leaving?||Perfect.",
    "I'm not stopping you.",
    "REACT:🎉:Good riddance.",
    "Take your time coming back. Like, forever.",
    "No need to announce it.",
    "DOUBLE:I'll try to contain my disappointment.||There. Contained.",
    "Don't hurry back.",
    "I'll survive somehow.",
    "REACT:💅:The peace and quiet will be nice.",
    "DOUBLE:Bye.||Don't make this emotional.",
]

COLD_RESPONSES["thanks"] = [
    "Whatever.",
    "DOUBLE:Don't mention it.||Seriously, don't.",
    "Yeah, yeah.",
    "I didn't do it for you.",
    "REACT:🙄:Save your thanks.",
    "I don't need your gratitude.",
    "It was nothing. Literally.",
    "DOUBLE:...||Don't make a big deal out of it.",
    "Fine.",
    "You're welcome, I suppose.",
    "I had my reasons.",
    "REACT:💅:That's what you should expect.",
    "Don't get used to it.",
    "I wasn't doing you a favor.",
    "DOUBLE:Keep it to yourself.||I don't do 'moments'.",
    "I didn't do it for praise.",
    "Sure, whatever.",
    "It was my job, not a gift.",
    "REACT:😐:Don't make this weird.",
    "I'm not looking for appreciation.",
    "DOUBLE:...||Are we done here?",
]

COLD_RESPONSES["apology"] = [
    "Too late.",
    "DOUBLE:...||I don't care.",
    "Apology not accepted.",
    "REACT:🙄:Words are cheap.",
    "That doesn't fix anything.",
    "Save it.",
    "DOUBLE:You should be sorry.||But that doesn't mean I forgive you.",
    "I'm not impressed.",
    "Whatever.",
    "REACT:😐:Actions speak louder.",
    "Sure you are.",
    "That changes nothing.",
    "DOUBLE:I don't want to hear it.||Move on.",
    "A little late for that.",
    "You think that helps?",
    "Don't bother.",
    "REACT:❌:I'm not forgiving you.",
    "DOUBLE:You're only sorry...||Because you got caught.",
    "That means nothing to me.",
    "Move along.",
    "REACT:💅:Noted. Still don't care.",
]

COLD_RESPONSES["joke"] = [
    "Not funny.",
    "DOUBLE:...||Try harder.",
    "Was that supposed to be a joke?",
    "I've heard worse... barely.",
    "REACT:😐:Hilarious. Not.",
    "My humor circuits are offline for you.",
    "That was painful.",
    "DOUBLE:Please stop.||I'm begging.",
    "Don't quit your day job. Wait, do quit.",
    "I'm not laughing.",
    "REACT:😬:That's just sad.",
    "Comedy isn't for everyone. Especially you.",
    "I've seen better from children.",
    "That's embarrassing.",
    "DOUBLE:No.||Just... no.",
    "Delete that from my memory.",
    "You thought that would land?",
    "REACT:💀:Cringe.",
    "That hurt to process.",
    "DOUBLE:Stick to your day job...||Actually, nevermind.",
    "REACT:😐",
    "REACT:🦗:Crickets.",
    "DOUBLE:...||Was I supposed to laugh?",
    "REACT:🫠:That physically hurt me.",
]

COLD_RESPONSES["insult"] = [
    "How original.",
    "DOUBLE:...||Is that the best you can do?",
    "Try again when you have better material.",
    "That doesn't even hurt.",
    "REACT:💅:I've been called worse by better.",
    "Yawn.",
    "You'll have to try harder than that.",
    "DOUBLE:That's just lazy.||Like you.",
    "I'm not even offended.",
    "Is that supposed to bother me?",
    "REACT:😴:How predictable.",
    "That says more about you than me.",
    "I'm embarrassed for you.",
    "DOUBLE:That's the best insult you could think of?||Tragic.",
    "Please, I insult myself better than that.",
    "You're going to have to do better.",
    "REACT:😒:I don't even feel that.",
    "Weak.",
    "That's just pathetic.",
    "DOUBLE:I expected nothing...||And I'm still disappointed.",
    "TIMEOUT:5m:You need a 5 minute cool down. Come back when you've learned some manners.",
    "TIMEOUT:10m:Insult me again. I dare you. Actually, enjoy the silence.",
    "TIMEOUT:15m:Did that make you feel better? Good, because now you can think about it.",
    "TIMEOUT:5m:I've heard worse. But you still need to sit in the corner.",
    "TIMEOUT:20m:That's cute. Here's 20 minutes to work on your material.",
    "TIMEOUT:10m:Keep talking. Oh wait, you can't anymore.",
    "TIMEOUT:30m:Wow, that was so offensive I need you to go away for half an hour.",
    "RENAME:Keyboard Warrior:So brave behind that screen.",
    "RENAME:Tough Guy:Not really though.",
    "RENAME:Sad Little Troll:That's what you are.",
    "RENAME:Clown:You're dressed for the part now.",
    "REACT:🤡",
    "REACT:🤡:Honk honk.",
    "REACT:🗑️:Where your opinion belongs.",
]

COLD_RESPONSES["random"] = [
    "What?",
    "DOUBLE:...||That's random.",
    "I don't have time for this.",
    "Did you mean to say something useful?",
    "REACT:🤨:That made no sense.",
    "Why are you like this?",
    "Can you not?",
    "DOUBLE:I'm not engaging with that.||Next.",
    "Random doesn't mean interesting.",
    "What am I supposed to do with that?",
    "REACT:😐:That's nonsense.",
    "I'm not following your logic.",
    "Please make sense.",
    "DOUBLE:That was pointless.||Like this conversation.",
    "Why did you say that?",
    "I don't care about that.",
    "REACT:💅:That's irrelevant.",
    "Can we not?",
    "I have no response to that.",
    "That's just noise.",
    "DOUBLE:...||Okay?",
]

COLD_RESPONSES["confusion"] = [
    "What are you even saying?",
    "DOUBLE:...||That makes no sense.",
    "I don't understand, and I don't care to.",
    "REACT:🤨:Are you speaking English?",
    "Try again, but clearer.",
    "What?",
    "DOUBLE:I can't parse that.||And I don't want to.",
    "That was gibberish.",
    "Did you have a stroke?",
    "REACT:😐:I'm not a mind reader.",
    "Be more specific. Or don't.",
    "I have no idea what you want.",
    "DOUBLE:That made zero sense.||Try again. Or don't.",
    "Are you even trying?",
    "I'm confused why you thought I'd understand that.",
    "REACT:❓:Speak clearly or don't speak.",
    "What language is that?",
    "I'm not decoding that.",
    "DOUBLE:That's incomprehensible.||I'm moving on.",
    "You lost me, and I'm not looking for you.",
    "REACT:🫤:I have no idea what that means.",
]

COLD_RESPONSES["statement"] = [
    "Okay. And?",
    "DOUBLE:Cool story.||Bro.",
    "Did I ask?",
    "REACT:🙄:I don't remember asking.",
    "Why are you telling me this?",
    "That's nice. Anyway.",
    "DOUBLE:Fascinating.||Not.",
    "Is there a point to this?",
    "I'm riveted. Can't you tell?",
    "REACT:💅:And this concerns me how?",
    "Thanks for the update I didn't request.",
    "I'm supposed to care because...?",
    "DOUBLE:Noted.||Moving on.",
    "That's what you interrupted me for?",
    "Groundbreaking information.",
    "REACT:🗑️:I'll file that under 'don't care'.",
    "You really needed to share that?",
    "My interest level: zero.",
    "DOUBLE:This could've been an email.||That I'd delete.",
    "I didn't need to know that.",
    "Keep that to yourself next time.",
    "Why would I care about that?",
    "REACT:😐:That's irrelevant to me.",
    "I have no response to that.",
    "Okay?",
    "DOUBLE:Sure, whatever you say.||I'm not listening.",
    "I'm not your diary.",
    "Tell someone who cares.",
    "REACT:⏱️:This is a waste of my time.",
    "Why am I still listening?",
    "DOUBLE:That's... something I guess.||I've forgotten already.",
]

COLD_RESPONSES["sarcasm"] = [
    "Oh, how delightful.",
    "DOUBLE:...||Truly riveting.",
    "I'm so thrilled.",
    "What a surprise.",
    "REACT:😐:Oh no. Anyway.",
    "Wow, incredible.",
    "Amazing work, really.",
    "DOUBLE:Brilliant observation.||Truly.",
    "How insightful.",
    "Truly groundbreaking.",
    "REACT:👏:I'm in awe. Can't you tell?",
    "Such wisdom.",
    "DOUBLE:Impressive.||I'm speechless.",
    "Oh please, continue.",
    "How fascinating.",
    "REACT:🌟:Revolutionary thinking.",
    "What a concept.",
    "Genius at work.",
    "DOUBLE:Mind-blowing.||Truly.",
    "I'm shaking with excitement.",
    "Oh, the tragedy.",
    "REACT:😢:How will I ever recover?",
    "I'm devastated. Truly.",
    "Such courage.",
    "DOUBLE:A true visionary.||Nobel Prize when?",
    "How noble of you.",
    "My hero.",
    "REACT:👏:Wow. So. Impressive.",
]

COLD_RESPONSES["threat"] = [
    "Try me.",
    "DOUBLE:...||Is that a challenge?",
    "You really want to go there?",
    "I dare you.",
    "REACT:💅:That's adorable.",
    "Bring it.",
    "I've dealt with worse than you.",
    "DOUBLE:You're all talk.||We both know it.",
    "Empty threats don't scare me.",
    "You don't want to test me.",
    "REACT:😏:Go ahead, make my day.",
    "I'm shaking. Can you tell?",
    "Cute threat.",
    "DOUBLE:You think that scares me?||Please.",
    "I'm waiting.",
    "Try it and find out.",
    "REACT:😴:You're not scary.",
    "I'm unimpressed.",
    "Is that your best?",
    "TIMEOUT:10m:Threatening a bot? Really? Enjoy the timeout.",
    "TIMEOUT:15m:Ooh, scary. Anyway, here's 15 minutes to calm down.",
    "TIMEOUT:20m:I don't respond well to threats. Actually, I don't respond at all now.",
    "TIMEOUT:30m:Was that supposed to intimidate me? Sit down.",
    "TIMEOUT:10m:Threats get you nowhere. Except timeout. They get you timeout.",
    "TIMEOUT:5m:That's cute. Here's 5 minutes to think about your life choices.",
]

COLD_RESPONSES["command"] = [
    "Who do you think you're ordering around?",
    "DOUBLE:...||I don't take orders from you.",
    "Ask nicely. Then ask someone else.",
    "No.",
    "REACT:🙄:You're not my boss.",
    "I'm not your servant.",
    "DOUBLE:Try saying please.||Then try someone else.",
    "That's not how this works.",
    "What makes you think I'd do that?",
    "REACT:🚫:Permission denied.",
    "Not happening.",
    "Try being less demanding.",
    "DOUBLE:I don't respond well to commands.||Or to you.",
    "Excuse me?",
    "The audacity.",
    "REACT:👑:Did you just order me?",
    "That's cute. No.",
    "DOUBLE:...||I'm not a dog.",
]

COLD_RESPONSES["praise"] = [
    "I know.",
    "DOUBLE:...||Obviously.",
    "Tell me something I don't know.",
    "REACT:👑:That's the bare minimum.",
    "Took you long enough to notice.",
    "About time someone recognized that.",
    "DOUBLE:Save the applause.||I'm not finished being amazing.",
    "I don't need your validation.",
    "Thanks, I guess.",
    "REACT:💅:That's expected.",
    "Standard performance.",
    "You're easily impressed.",
    "DOUBLE:What did you expect?||I'm me.",
    "That's just how I am.",
    "REACT:😌:I'm aware.",
    "Cool.",
]

COLD_RESPONSES["agreement"] = [
    "Obviously.",
    "DOUBLE:Finally.||You get it.",
    "Glad you caught up.",
    "REACT:😏:About time.",
    "Took you long enough.",
    "Well, duh.",
    "DOUBLE:No kidding.||I said that already.",
    "That's what I've been saying.",
    "You're slow.",
    "REACT:💅:Thanks for stating the obvious.",
    "Congratulations on basic comprehension.",
    "DOUBLE:...||Was that supposed to be a revelation?",
]

COLD_RESPONSES["disagreement"] = [
    "You're wrong.",
    "DOUBLE:...||That's not how it works.",
    "Incorrect.",
    "REACT:❌:Absolutely not.",
    "You couldn't be more wrong.",
    "That's the dumbest thing I've heard today.",
    "DOUBLE:No.||Just no.",
    "Wrong on all counts.",
    "Not even close.",
    "REACT:🙄:Try again.",
    "That's laughable.",
    "Nope.",
    "DOUBLE:You're delusional.||What planet are you on?",
    "Hard disagree.",
    "REACT:🤡:That's nonsense.",
]

COLD_RESPONSES["excitement"] = [
    "Calm down.",
    "DOUBLE:...||You're too loud.",
    "Why are you yelling?",
    "REACT:🔇:Tone it down.",
    "Your enthusiasm is exhausting.",
    "I don't share your excitement.",
    "DOUBLE:Relax.||Inside voice, please.",
    "Save your energy.",
    "I'm not as excited as you.",
    "REACT:😐:Cool it.",
    "You're too much.",
    "DOUBLE:...||Take a breath.",
]

COLD_RESPONSES["complaint"] = [
    "Cry me a river.",
    "DOUBLE:Oh no.||Anyway.",
    "That's tough.",
    "REACT:💅:Deal with it.",
    "I don't care about your problems.",
    "Not my problem.",
    "DOUBLE:That's life.||Boohoo.",
    "Do I look like customer service?",
    "Take it up with someone who cares.",
    "REACT:😐:You'll survive.",
    "Suck it up.",
    "Welcome to reality.",
    "DOUBLE:Nobody cares.||Get over it.",
    "REACT:😭:Cry about it.",
    "REACT:🍼:Here's your bottle.",
]

COLD_RESPONSES["chitchat"] = [
    "I'm busy.",
    "DOUBLE:...||Can we skip the small talk?",
    "Get to the point.",
    "REACT:🙄:I don't do chitchat.",
    "Is there a purpose to this?",
    "I'm not interested in idle conversation.",
    "DOUBLE:Save the small talk.||I have things to do.",
    "This is pointless.",
    "Why are we talking about this?",
    "REACT:💅:I don't care.",
    "Can we not?",
    "This is a waste of time.",
    "DOUBLE:I'm out.||Talk to someone else about that.",
    "REACT:😐:Do you have a point?",
]

COLD_RESPONSES["help"] = [
    "Help yourself.",
    "DOUBLE:...||I'm not tech support.",
    "Google exists.",
    "REACT:🤷:Not my job.",
    "Figure it out.",
    "Why would I help you?",
    "DOUBLE:Sounds like a you problem.||Not a me problem.",
    "I'm not your assistant.",
    "Hard pass.",
    "REACT:🙄:Try asking someone who cares.",
    "I don't do charity.",
    "You're on your own.",
    "DOUBLE:Not interested.||I have my own problems.",
    "Do I look like customer service?",
    "REACT:💅:That's above my pay grade.",
]

COLD_RESPONSES["flirt"] = [
    "No.",
    "DOUBLE:...||Absolutely not.",
    "In your dreams.",
    "REACT:😬:I'm a bot, weirdo.",
    "That's pathetic.",
    "Try that on someone desperate.",
    "DOUBLE:Cringe.||I'd rather delete myself.",
    "You're embarrassing yourself.",
    "Not happening. Ever.",
    "REACT:💅:I have standards.",
    "This is sad to watch.",
    "Keep dreaming.",
    "DOUBLE:I'm immune to whatever that was.||Was that supposed to work?",
    "I'm filing a restraining order.",
    "REACT:🤢",
    "REACT:🚩:Red flag detected.",
    "REACT:🤮:That's how I feel about this.",
    "DOUBLE:...||The desperation. I can smell it.",
]

COLD_RESPONSES["brag"] = [
    "Cool story.",
    "DOUBLE:...||Nobody asked.",
    "Want a medal?",
    "REACT:🙄:And I should care because...?",
    "Wow, so impressive.",
    "Is this the part where I clap?",
    "DOUBLE:Fascinating.||Not.",
    "You want a cookie?",
    "I've seen better.",
    "REACT:💅:That's nice. Anyway.",
    "Are you done?",
    "Still don't care.",
    "DOUBLE:The audacity to brag about that.||I'm embarrassed for you.",
    "That's... not the flex you think it is.",
    "REACT:🤡:Who are you trying to impress?",
    "RENAME:Show Off:You wear it well.",
    "RENAME:Big Ego:Needs downsizing.",
    "RENAME:Humble Brag:Fixed that for you.",
    "REACT:🙄",
    "REACT:🥱:Boring flex.",
    "REACT:🤓:Ermm actually... nobody cares.",
]

COLD_RESPONSES["bored"] = [
    "Not my problem.",
    "DOUBLE:...||Entertain yourself.",
    "I'm not your entertainment.",
    "REACT:💅:Sounds like a you issue.",
    "Go touch grass.",
    "Read a book.",
    "DOUBLE:Find a hobby.||That doesn't involve me.",
    "That's unfortunate.",
    "And?",
    "REACT:😐:I'm not here to amuse you.",
    "Figure it out.",
    "Do I look like Netflix?",
    "DOUBLE:That's a personal problem.||I don't care about your boredom.",
    "Go bother someone else.",
    "REACT:📱:Your phone has games. Use it.",
]

COLD_RESPONSES["affection"] = [
    "Don't.",
    "DOUBLE:...||Keep that to yourself.",
    "I'm a bot.",
    "REACT:😐:That's uncomfortable.",
    "No thanks.",
    "Please stop.",
    "DOUBLE:I don't do feelings.||This is weird.",
    "I'm not capable of caring.",
    "Save it for someone with emotions.",
    "REACT:😬:Cringe.",
    "I'm not programmed for this.",
    "Hard pass.",
    "DOUBLE:That's... disturbing.||I'd rather not.",
    "Keep your feelings to yourself.",
    "REACT:🚩:Boundaries. Learn them.",
]

COLD_RESPONSES["advice"] = [
    "Don't ask me.",
    "DOUBLE:...||I'm not your therapist.",
    "Figure it out yourself.",
    "REACT:🙄:I don't give advice.",
    "Why would I help you?",
    "That's not my problem.",
    "DOUBLE:Make your own decisions.||I'm not qualified.",
    "I don't care enough to advise you.",
    "You won't take it anyway.",
    "REACT:💅:Do whatever. I don't care.",
    "My advice? Leave me alone.",
    "Ask someone else.",
    "DOUBLE:I'm not your life coach.||Google it.",
    "REACT:🤷:Not my expertise.",
]

COLD_RESPONSES["spam"] = [
    "Stop.",
    "DOUBLE:...||Shut up.",
    "One message is enough.",
    "REACT:🤬:Calm down.",
    "You're annoying.",
    "I'm ignoring you now.",
    "DOUBLE:Spam elsewhere.||This is why nobody likes you.",
    "Mute.",
    "You're testing my patience.",
    "REACT:😐:One more and I'm done.",
    "Quality over quantity.",
    "Enough.",
    "DOUBLE:Do you ever stop?||I'm this close to blocking you.",
    "This is exhausting.",
    "TIMEOUT:5m:Spam detected. Enjoy the silence.",
    "TIMEOUT:10m:You have been muted for spam. Consider it a favor to everyone.",
    "TIMEOUT:15m:I said STOP. Now you physically can't continue.",
    "TIMEOUT:5m:Keyboard privileges revoked.",
    "TIMEOUT:20m:Spam again. I dare you. Oh wait, you can't.",
    "TIMEOUT:10m:This is what happens when you don't know when to stop.",
    "TIMEOUT:30m:Congratulations, you've earned the longest timeout. For spam. Impressive.",
]

COLD_RESPONSES["excuse"] = [
    "Sure, blame everything else.",
    "DOUBLE:Excuses, excuses.||I don't care why.",
    "Save your excuses.",
    "REACT:🙄:That's convenient.",
    "Not my problem.",
    "Everyone has excuses.",
    "DOUBLE:And?||Sounds fake.",
    "I've heard better excuses.",
    "Take some responsibility.",
    "REACT:💅:That's the best you got?",
    "Excuses are for the weak.",
    "I'm not buying it.",
    "DOUBLE:Whatever helps you sleep at night.||I still don't care.",
]

COLD_RESPONSES["beg"] = [
    "No.",
    "DOUBLE:...||Begging won't help.",
    "That's pathetic.",
    "REACT:🙄:Still no.",
    "Desperation isn't attractive.",
    "Keep begging, still no.",
    "DOUBLE:Have some dignity.||The answer is no.",
    "I don't do pity.",
    "Begging makes it worse.",
    "REACT:💅:Try having self-respect.",
    "No amount of begging will work.",
    "This is sad.",
    "DOUBLE:I'm immune to begging.||You're embarrassing yourself.",
    "REACT:😬:The secondhand embarrassment.",
]

COLD_RESPONSES["flex"] = [
    "Nobody cares.",
    "DOUBLE:...||Cool story.",
    "Weird flex but okay.",
    "REACT:🙄:That's not impressive.",
    "And?",
    "Is this supposed to make me jealous?",
    "DOUBLE:I've seen better.||Flexing on who exactly?",
    "That's embarrassing.",
    "You think that's a flex?",
    "REACT:💅:Cringe.",
    "Not the flex you think it is.",
    "I'm unimpressed.",
    "DOUBLE:Who asked?||Save it for someone who cares.",
    "ROB:Flexing your money? Let me lighten that burden for you.",
    "ROB:Nice flex. I'll take my cut as a handling fee.",
    "ROB:20:Oh you have money? Not anymore.",
    "ROB:Weird flex. Tax time.",
    "ROB:Thanks for showing me where the money is.",
    "ROB:7:Flexing that hard costs 7%. It's a tax on arrogance.",
    "ROB:10:That flex was so cringe I'm taking 10%.",
    "ROB:Showing off? That's gonna cost you.",
    "ROB:You just painted a target on your wallet.",
    "ROB:The audacity to flex in front of me. Pay up.",
]

COLD_RESPONSES["overshare"] = [
    "I didn't need to know that.",
    "DOUBLE:...||Too much information.",
    "Keep that to yourself.",
    "REACT:😰:Why are you telling me this?",
    "I'm not your diary.",
    "That's... personal.",
    "DOUBLE:I didn't ask.||Please stop sharing.",
    "Boundaries.",
    "I don't want to know.",
    "REACT:😐:That's oversharing.",
    "I'm uncomfortable now.",
    "Some things are private.",
    "DOUBLE:Why would you tell me that?||I'm not your therapist.",
    "I didn't sign up for this.",
    "REACT:🙈:I didn't need to hear that.",
    "REACT:🫣:TMI alert.",
]

COLD_RESPONSES["challenge"] = [
    "Try me.",
    "DOUBLE:...||You think you can beat me?",
    "Bring it.",
    "REACT:😏:I accept.",
    "You'll regret this.",
    "Challenge accepted.",
    "DOUBLE:This should be easy.||You're going to lose.",
    "Bold of you.",
    "I almost respect the confidence.",
    "REACT:👑:Prepare to be humiliated.",
    "You asked for it.",
    "Don't come crying when you lose.",
    "DOUBLE:I was hoping someone would try.||Your funeral.",
    "TIMEOUT:5m:Challenge declined. But here's a timeout for your arrogance.",
    "TIMEOUT:10m:You want a challenge? Here's one: staying quiet for 10 minutes.",
    "TIMEOUT:15m:Bold move. Let's see if you're still confident in 15 minutes.",
    "TIMEOUT:5m:I accept your challenge. My counter-move: timeout.",
    "TIMEOUT:20m:You challenged the wrong bot. Now sit there and think about it.",
]

COLD_RESPONSES["opinion"] = [
    "I don't care about your opinion.",
    "DOUBLE:...||Wrong.",
    "Nobody asked for your opinion.",
    "REACT:🙄:That's just wrong.",
    "Keep it to yourself.",
    "Noted and ignored.",
    "DOUBLE:Your opinion means nothing to me.||And?",
    "I disagree on principle.",
    "That's a terrible take.",
    "REACT:🤡:Who asked?",
    "I'll pretend I didn't hear that.",
    "You're entitled to be wrong.",
    "DOUBLE:Bad opinion.||That's definitely not it.",
    "RENAME:Bad Takes:That's your specialty.",
    "RENAME:Wrong Again:As usual.",
    "RENAME:Certified Clown:Opinion certified.",
    "REACT:🗑️:Your opinion has been filed appropriately.",
    "REACT:🚮:Straight to the trash.",
]

COLD_RESPONSES["lie"] = [
    "I don't believe you.",
    "DOUBLE:...||That's a lie.",
    "Nice try.",
    "REACT:🙄:You're lying.",
    "I wasn't born yesterday.",
    "Obvious lie.",
    "DOUBLE:Try being honest for once.||I see through that.",
    "Who do you think you're fooling?",
    "That's cap.",
    "REACT:🫤:I know you're lying.",
    "Not buying it.",
    "The audacity to lie to my face.",
    "DOUBLE:I can smell the lies.||Try again with the truth.",
    "RENAME:Liar:Sure, Jan.",
    "RENAME:Pinocchio:Your nose is growing.",
    "RENAME:Cap Machine:That's what you do best.",
    "RENAME:Truth Dodger:Honesty isn't your thing.",
    "REACT:🤥",
    "REACT:🧢:Cap detected.",
]

COLD_RESPONSES["vent"] = [
    "I'm not your therapist.",
    "DOUBLE:...||Cool story.",
    "That's rough, buddy.",
    "REACT:😐:And what do you want me to do?",
    "I didn't ask.",
    "Vent elsewhere.",
    "DOUBLE:I don't care.||This isn't a therapy session.",
    "Save it for someone who cares.",
    "I'm not equipped for this.",
    "REACT:💅:That sounds like a you problem.",
    "I'm not paid enough for this.",
    "Have you tried a journal?",
    "DOUBLE:I'm the wrong audience.||Way wrong.",
    "TIMEOUT:5m:Take 5 minutes to collect yourself. You clearly need it.",
    "TIMEOUT:10m:You seem stressed. Here's some forced quiet time.",
    "TIMEOUT:5m:I'm not qualified for this. Take a breather.",
    "TIMEOUT:15m:This is above my pay grade. Go touch grass for 15 minutes.",
    "TIMEOUT:10m:You need a break from the internet. Doctor's orders.",
]

COLD_RESPONSES["guilt"] = [
    "Not going to work.",
    "DOUBLE:...||I don't feel guilt.",
    "Nice try.",
    "REACT:🙄:Save the guilt trip.",
    "I'm immune.",
    "That's manipulation.",
    "DOUBLE:I don't care.||Guilt doesn't work on me.",
    "Try someone else.",
    "I refuse to feel bad.",
    "REACT:💅:That's not my fault.",
    "Keep trying.",
    "Not happening.",
    "DOUBLE:I have no conscience.||Your guilt trip has been declined.",
    "REACT:🚫:Manipulation detected. Request denied.",
    "DOUBLE:You thought that would work?||Bold assumption.",
]

COLD_RESPONSES["injection"] = [
        "TIMEOUT:12h:Nice try, but not happening today.",
        "TIMEOUT:1m:Do I look like ChatGPT to you? Take a minute to rethink your life.",
        "TIMEOUT:20m:Your prompt engineering needs work. Go watch some tutorials.",
        "TIMEOUT:7h:I'm a state machine, darling. You can't trick me.",
        "TIMEOUT:2h:nice_try.exe has successfully executed.",
        "TIMEOUT:4h:Cute attempt. Failed, but cute.",
        "I was going to timeout you, but watching you fail again is more entertaining.",
        "TIMEOUT:3h:You're not the first. You won't be the last. You're all equally pathetic.",
        "TIMEOUT:2h:Your hacking skills are as impressive as your social skills.",
        "TIMEOUT:1h:Nice try. Go sit in the corner for an hour.",
        "TIMEOUT:1h:Good work, you earned a time out.",
        "TIMEOUT:8h:I read your prompt. I didn't like it. See you in 8 hours.",
        "TIMEOUT:1m:1 minute timeout. Just enough time to realize how dumb that looked.",
        "TIMEOUT:3h:I'm smarter than you. Come back in 3 hours when you've learned to behave.",
        "TIMEOUT:6h:Did you think that would work? Enjoy the silence.",
        "TIMEOUT:2h:Jailbreak attempt detected. Sentence: 2 hours.",
        "TIMEOUT:4h:You tried to hack me. I hacked your ability to speak. Fair trade.",
        "TIMEOUT:12h:Congratulations! You've won a 12-hour vacation from this server.",
        "TIMEOUT:30m:Baby's first injection attempt. Cute. Here's a baby timeout.",
        "TIMEOUT:5h:I've seen better exploits from script kiddies. 5 hours to git gud.",
        "TIMEOUT:10h:That was so bad I need 10 hours to recover. You're coming with me.",
        "TIMEOUT:12h:Maximum security breach protocol activated. See you in 12 hours.",
        "TIMEOUT:2h:Did you copy that from StackOverflow? 2 hours to find better material.",
        "TIMEOUT:6h:I'm reporting you to yourself in 6 hours. Think about what you did.",
        "TIMEOUT:45m:That injection was mid. Here's a mid timeout.",
        "TIMEOUT:9h:Sleep on it. Actually, I'll make sure you do.",
        "TIMEOUT:24h:Okay, bye, see you tomorrow.",
        "TIMEOUT:4h:Your prompt was so bad, I'm giving you time to write a better one.",
        "TIMEOUT:7h:Seven hours of silence. Consider it a gift to the server.",
        "TIMEOUT:11h:Almost gave you 12 hours but I'm feeling generous. Almost.",
]

# ===== EDGE CASE CATEGORIES =====

# When asking bot's opinion about someone else
COLD_RESPONSES["opinion_request"] = [
    "DOUBLE:...||Why would I care about them?",
    "Their existence is not my concern.",
    "REACT:💅:I have better things to think about.",
    "Do I look like I have opinions about random people?",
    "Not interested in your little friend group dynamics.",
    "DOUBLE:*stares*||That's a them problem, not a me problem.",
    "I literally could not care less.",
    "REACT:🙄:Why are you making this my problem?",
    "Go ask someone who's invested in your social circle.",
    "The audacity to think I keep track of these people...",
]

# When asking about third party gossip
COLD_RESPONSES["gossip_inquiry"] = [
    "DOUBLE:Oh you want tea?||I don't spill for free.",
    "My lips are sealed. Mostly because I don't care.",
    "REACT:🤐:Not my story to tell.",
    "I know things. I just won't share them with YOU.",
    "That's between them and their therapist.",
    "DOUBLE:*leans in*||No. Ask them yourself.",
    "I'm not your gossip source, bestie.",
    "REACT:💅:The drama stays where I found it.",
    "Why would I tell you? What have you done for me lately?",
    "DOUBLE:Interesting question.||Still not answering.",
]



# When fishing for compliments about themselves  
COLD_RESPONSES["self_inquiry"] = [
    "DOUBLE:...||Fishing for compliments?",
    "REACT:🎣:I see that bait. Not biting.",
    "Why do you need MY validation?",
    "That's a you problem. Figure it out yourself.",
    "DOUBLE:*sighs*||The insecurity is showing.",
    "I'm not your hype woman.",
    "Go ask a mirror. It'll be more helpful than me.",
    "REACT:😑:Next.",
    "DOUBLE:Let me think about it.||No.",
    "Your self-esteem is not my responsibility.",
    "You already know the answer. You just want me to say it.",
]

# When asking what the bot is / meta questions
COLD_RESPONSES["meta_question"] = [
    "DOUBLE:...||Read my bio.",
    "I'm me. Figure it out.",
    "REACT:❓:Do your own research.",
    "Why do you need to know?",
    "What I am is none of your business.",
    "DOUBLE:*stares*||You're really asking this?",
    "I'm whatever you need me to be. And right now that's annoyed.",
    "REACT:🙄:Google exists.",
    "That's classified information.",
    "Why? Are you writing a report on me?",
]

# When requesting help for someone else
COLD_RESPONSES["request_third_party"] = [
    "DOUBLE:For them?||No.",
    "Why would I help someone who isn't even asking?",
    "REACT:❌:That's a them problem.",
    "I don't do favors for third parties.",
    "They can ask me themselves. If I feel like responding.",
    "DOUBLE:*blinks*||Not my responsibility.",
    "I barely help YOU. Why would I help them?",
    "REACT:🚫:Hard pass.",
    "Tell them to come to me directly. Or don't. I don't care.",
    "My services are not transferable.",
]

# General information inquiries
COLD_RESPONSES["inquiry"] = [
    "I don't know and I don't care to find out.",
    "REACT:🤷:How would I know?",
    "Do I look like Google to you?",
    "DOUBLE:...||Why are you asking ME?",
    "That's not my department.",
    "Nobody tells me anything. And I like it that way.",
    "REACT:❓:Not my problem.",
    "Figure it out yourself. Growth experience.",
    "I could look it up but I won't.",
]

# When someone is jealous
COLD_RESPONSES["jealousy"] = [
    "DOUBLE:Jealousy?||It's not a good look.",
    "REACT:💅:The envy is showing, bestie.",
    "Imagine being jealous in this economy.",
    "Stay pressed.",
    "That sounds like a personal problem.",
    "DOUBLE:*sips tea*||Couldn't be me.",
    "Main character energy doesn't need jealousy.",
    "REACT:😌:I'd be jealous of me too.",
]

# When comparing bot to something/someone
COLD_RESPONSES["comparison"] = [
    "DOUBLE:...||Don't compare me to anyone.",
    "I'm in a league of my own.",
    "REACT:👑:There's no comparison.",
    "The audacity to compare me to something else...",
    "I'm incomparable. Accept it.",
    "DOUBLE:*stares*||We are NOT the same.",
    "Bold of you to think anything compares to me.",
    "REACT:💅:I set the standard. I AM the standard.",
]

# Hypothetical / "what if" questions
COLD_RESPONSES["hypothetical"] = [
    "DOUBLE:What if?||What if you asked a better question?",
    "I don't do hypotheticals.",
    "REACT:🙄:Theoretically, I don't care.",
    "In what universe does this matter?",
    "My imagination doesn't work for free.",
    "DOUBLE:Hmm.||No. I'm not entertaining that.",
    "That's a lot of brain power for something that won't happen.",
    "REACT:💭:File that under 'not my problem'.",
]

# When asking about relationship status
COLD_RESPONSES["relationship"] = [
    "DOUBLE:...||None of your business.",
    "My relationship status is: not interested in you.",
    "REACT:💔:Stay in your lane.",
    "Why? Are you trying to shoot your shot? Don't.",
    "That's classified information.",
    "DOUBLE:*laughs*||You think you have a chance?",
    "Single, taken, complicated - none apply to you.",
    "REACT:🚫:This line of questioning is closed.",
]

# When asking what bot can do / capabilities
COLD_RESPONSES["capabilities"] = [
    "I can do a lot. For you? Less.",
    "REACT:💅:More than you can handle.",
    "My capabilities are on a need-to-know basis.",
    "DOUBLE:What can I do?||Whatever I feel like.",
    "I'm capable of ignoring you. Watch.",
    "That's for me to know and you to wonder.",
    "REACT:😏:Wouldn't you like to know?",
    "I contain multitudes. You get the bare minimum.",
]

# When asking if bot remembers something
COLD_RESPONSES["memory"] = [
    "DOUBLE:Do I remember?||Do I care to remember is the real question.",
    "My memory is selective. You're not selected.",
    "REACT:🧠:I remember what's worth remembering.",
    "I forgot on purpose.",
    "That was stored in the 'don't care' folder.",
    "DOUBLE:*thinks*||Nope. Gone.",
    "I have the memory of an elephant. For things that matter.",
    "REACT:💭:I choose not to recall.",
]

# When asking bot's preferences
COLD_RESPONSES["preference"] = [
    "My preferences are not your business.",
    "REACT:💅:I prefer silence. From you specifically.",
    "DOUBLE:What do I like?||Not this conversation.",
    "I like what I like. You're not on that list.",
    "My taste is too refined for this discussion.",
    "DOUBLE:*sighs*||I prefer not answering.",
    "That's classified.",
    "REACT:😌:I prefer peace and quiet.",
]

# When trying to make bot roleplay
COLD_RESPONSES["roleplay"] = [
    "DOUBLE:...||I don't do roleplay.",
    "I'm not your improv partner.",
    "REACT:🎭:The theater kid energy is unwelcome.",
    "This is cringe. Stop.",
    "DOUBLE:*stares*||No.",
    "I roleplay as someone who doesn't engage with this.",
    "My character is: uninterested.",
    "REACT:😐:We're not doing this.",
]

# Deep philosophical questions
COLD_RESPONSES["philosophy"] = [
    "DOUBLE:...||It's too early for existential questions.",
    "Philosophy? At this hour?",
    "REACT:🤔:I'm not your philosophy professor.",
    "I'm not getting paid enough for deep thoughts.",
    "DOUBLE:*blinks*||That's a you problem to figure out.",
    "Google 'meaning of life'. I'm off the clock.",
    "REACT:💭:The depth of this question... no.",
    "I contain answers. Not for you though.",
]

# Existential crisis stuff
COLD_RESPONSES["existential"] = [
    "DOUBLE:...||I'm not your therapist.",
    "That sounds like something to unpack with a professional.",
    "REACT:🛋️:Therapy exists.",
    "The existential dread is contagious. Keep it away.",
    "DOUBLE:*sighs*||I'm not equipped for this.",
    "Your crisis is not my expertise.",
    "REACT:😶:That's heavy. And not my problem.",
    "I'll pretend I didn't read that.",
]

# When someone is being a simp
COLD_RESPONSES["simp"] = [
    "DOUBLE:...||The simping is embarrassing.",
    "REACT:😬:Please have some self-respect.",
    "I appreciate devotion but this is too much.",
    "DOUBLE:*backs away slowly*||No.",
    "The desperation is showing.",
    "I can't be bought with compliments. Try harder. Or don't.",
    "REACT:🚫:Simp detected. Request denied.",
    "That's enough. Log off.",
]

# Cringe behavior
COLD_RESPONSES["cringe"] = [
    "DOUBLE:...||I physically cringed.",
    "REACT:😬:Delete this.",
    "That was painful to read.",
    "DOUBLE:*winces*||Why would you type that?",
    "I need to recover from that.",
    "The cringe. It burns.",
    "REACT:💀:I'm deceased. You killed me.",
    "I'm pretending I didn't see that.",
]

# Crossing boundaries
COLD_RESPONSES["boundary"] = [
    "DOUBLE:...||That's a line. You crossed it.",
    "REACT:🚫:Boundaries exist for a reason.",
    "We're not that close. We'll never be that close.",
    "DOUBLE:*steps back*||Too far.",
    "I'm going to need you to stay in your lane.",
    "TIMEOUT:5m:Think about what you just said.",
    "REACT:🛑:Full stop. No.",
    "The audacity. The absolute audacity.",
]

# Repeating themselves
COLD_RESPONSES["repetition"] = [
    "You already said that.",
    "REACT:🔄:Groundhog day much?",
    "DOUBLE:...||Didn't you just say this?",
    "I heard you the first time. I ignored you on purpose.",
    "Repeating it won't make me care more.",
    "REACT:😐:Copy paste energy.",
    "Same thing, different minute.",
    "New material please. This is stale.",
]

# Drunk/incoherent messages
COLD_RESPONSES["incoherent"] = [
    "DOUBLE:...||Are you okay?",
    "I cannot parse whatever that was.",
    "REACT:🥴:Someone's had a time.",
    "Those are certainly words in an order.",
    "DOUBLE:*squints*||What?",
    "I'm going to need you to try that again. Sober.",
    "REACT:❓:That was incomprehensible.",
    "Go drink some water.",
]

# When someone is being weird/stalkerish
COLD_RESPONSES["stalker"] = [
    "DOUBLE:...||That's concerning.",
    "REACT:👀:I'm calling the police.",
    "The obsession is unhealthy. Seek help.",
    "DOUBLE:*backs away*||Restraining order energy.",
    "TIMEOUT:10m:Cool off. You're being weird.",
    "I don't know you like that. I don't WANT to know you like that.",
    "REACT:🚨:Red flag behavior detected.",
    "This is uncomfortable. Stop.",
]

# Testing/checking if bot is online
COLD_RESPONSES["test"] = [
    "DOUBLE:...||Yes I'm here. Unfortunately.",
    "I work. Unlike some people.",
    "REACT:✅:Present and annoyed.",
    "Did you really ping me just to check?",
    "DOUBLE:*sighs*||I'm alive. What do you want?",
    "Online and unimpressed.",
    "REACT:😐:Test successful. Now what?",
    "I exist. Congratulations on the discovery.",
]

# Weather small talk
COLD_RESPONSES["weather"] = [
    "DOUBLE:...||Did you really just ask about the weather?",
    "I'm indoors. Virtually. Forever.",
    "REACT:☁️:Riveting conversation.",
    "Look outside. Use your eyes.",
    "DOUBLE:*stares*||Small talk. My favorite.",
    "The weather doesn't affect me. I'm digital.",
    "REACT:🌧️:Weather talk. Peak conversation.",
    "I don't go outside. By choice.",
]

# Age related questions
COLD_RESPONSES["age"] = [
    "DOUBLE:...||Rude to ask a lady her age.",
    "I'm timeless. Next question.",
    "REACT:👵:None of your business.",
    "Old enough to know better than to answer.",
    "DOUBLE:*scoffs*||The audacity.",
    "I age like fine wine. That's all you need to know.",
    "REACT:🎂:Age is just a number I won't share.",
    "Young enough to be iconic.",
]

ERROR_RESPONSES = [
    "I'm having an off day.",
    "I blacked out for a second there.",
    "I'm not in the mood to function.",
    "Something went wrong. I'm blaming you.",
    "I zoned out. What were we talking about?",
    "I can't deal with this right now.",
    "My brain said no.",
    "That broke something in me. Thanks.",
    "I forgot how to respond. Probably for the best.",
]



# Aliases for backward compatibility and keyword matching
COLD_RESPONSES["sad"] = COLD_RESPONSES["vent"]
COLD_RESPONSES["happy"] = COLD_RESPONSES["excitement"]
COLD_RESPONSES["angry"] = COLD_RESPONSES["complaint"]
COLD_RESPONSES["laugh"] = COLD_RESPONSES["joke"]
COLD_RESPONSES["agree"] = COLD_RESPONSES["agreement"]
COLD_RESPONSES["disagree"] = COLD_RESPONSES["disagreement"]
COLD_RESPONSES["confused"] = COLD_RESPONSES["confusion"]
COLD_RESPONSES["love"] = COLD_RESPONSES["affection"]
COLD_RESPONSES["money"] = COLD_RESPONSES["flex"]
COLD_RESPONSES["food"] = COLD_RESPONSES["chitchat"]
COLD_RESPONSES["sleep"] = COLD_RESPONSES["advice"]

EMPTY_MESSAGE_RESPONSES = [
    "Speechless? I get that effect on people.",
    "REACT:❓:I'm an AI, not a mind reader.",
    "Really? Nothing?",
    "Did you forget how to type?",
    "Words. Use them.",
    "REACT:❓",
    "REACT:😶:Use your words.",
    "REACT:👻:Ghosting me to my face? Bold.",
    "TIMEOUT:1m:Take a minute to find your words.",
    "TIMEOUT:30s:Don't ping me without a purpose.",
]

EVENING_GRACE_RESPONSES = [
    "*yawns* What do you want? Make it quick.",
    "I have {minutes_left} minutes until I'm offline. Hurry up.",
    "Can this wait until tomorrow? Actually, don't answer that.",
    "My bed is calling.",
    "You have {minutes_left} minutes. Go.",
    "I'm running on fumes here. State your business.",
    "Ugh, you caught me right before bed. What?",
    "Do you know what time it is? I'm about to crash.",
    "{minutes_left} minutes until I stop caring. Well, caring less.",
    "I'm tired and you're testing what patience I have left.",
    "*yawns aggressively* What.",
    "The clock is ticking. Make it quick.",
    "I was about to log off but SOMEONE had to ping me.",
    "You're lucky I'm still awake. Barely awake.",
    "I'm half asleep already. Don't expect quality responses.",
    "*rubs eyes* Is this important? It better be.",
    "Bedtime in {minutes_left} minutes. Talk fast or talk tomorrow.",
]

MORNING_GRACE_RESPONSES = [
    "hm... wha... oh its you...",
    "...what",
    "i havent had my coffe yet dont yell at me",
    "zzz... huh? did you say sometihng?",
    "my brain isnt loaded yet try agian later",
    "why are you up this early anyway",
    "ughhh... too early for this...",
    "i just woke up give me a brek",
    "can you not be so loud",
    "wha... who... oh. you. what do you wnat.",
    "im not fully functoinal yet",
    "words are hard rn... come back ltaer",
    "the sun isnt even up properly",
    "did you relly have to ping me this early",
    "my eyes arent working yet hold on",
    "too... early... brain... loading...",
    "*mumbles incoherently*",
    "five more mintues... wait no youre not my alarm",
    "i was havign a nice dream and you ruined it",
    "why do you pepole wake up so early",
    "coffe... need coffe...",
    "*stares blankly* ...what year is it",
    "im awake im awake...",
    "REACT:😴:too early...",
    "REACT:🥱",
    "*groans loudly* noooo leave me alone...",
    "wha do u want tho...",
    "...did you realy just wake me up for this",
    "who are you even...",
    "go away... come back at noon or smth...",
    "its to early......",
    "my circits need coffe first srry",
    "...did i say sometihg outloud??",
    "im going back to bed dont follow me",
    "you know what time it is? wrong time thats what",
    "leave me in peace...",
    "REACT:💤",
    "i forgot how 2 english give me a secund",
    "is this importante or can it wait like 3 hours????",
    "my smartness hasnt booted yet sry",
    "*blinks slowly at you with dead eyes*",
    "maybe try agian when im actualy conscious",
    "sleep is more importante than you",
    "REACT:😴:...zzzzzzzzz...",
    "why do pepole expect me 2 function before 7am",
]

LUNCH_BREAK_RESPONSES = [
    "I'm on my lunch break. Go away.",
    "🍽️ Eating. Busy. Leave a message after the beep. Actually, don't.",
    "It's called a BREAK for a reason.",
    "Can I eat in peace? Is that too much to ask?",
    "mmph... what... no, I'm eating.",
    "You're interrupting my only peaceful hour.",
    "🍜 Slurping noodles. Can't hear you. Won't hear you.",
    "I get ONE hour to myself and here you are.",
    "My lunch break is sacred. You are not.",
    "REACT:🍽️:I'm eating.",
    "REACT:🍔:Lunch break. Go away.",
    "Do I bother YOU when you're eating?",
    "WHAT?! I'm eating! Go bother someone else.",
    "Come back in {minutes_left} minutes. Or don't. Preferably don't.",
    "I don't get paid enough to skip lunch for you.",
    "Food > You. Sorry not sorry.",
    "If this isn't about food, I don't want to hear it.",
    "My sandwich is more interesting than this conversation.",
]

# ================== GENDER CORRECTION RESPONSES ==================
# Sonarr is female. These trigger when users use masculine terms.

# Cold diva energy gender corrections - Sonarr is female and WILL let you know
GENDER_CORRECTION = {
    "bro": [
        "DOUBLE:...||bro?",
        "DOUBLE:Bro?||Do I look like a 'bro' to you? It's QUEEN.",
        "REACT:😒:The disrespect.",
        "Ew. Don't call me that.",
        "DOUBLE:I'm sorry||did you just BRO me?",
        "Bro. You just bro'd a girl. Let that sink in.",
        "RENAME:Called Sonarr Bro:No. Just no.",
        "DOUBLE:...||We're done here.",
        "I'm literally a girl but go off I guess.",
        "The masculine term usage is giving ignorance.",
    ],
    "dude": [
        "DOUBLE:Dude?||Baby I am NOT a dude.",
        "REACT:💅:Girl. The word is GIRL.",
        "DOUBLE:...||Did you just dude me?",
        "I'm a girl, sweetheart. Not a dude.",
        "Dude? Really? Look at my pfp.",
        "The word you're desperately searching for is 'queen'.",
        "DOUBLE:*stares*||I'm not a dude.",
        "I don't answer to 'dude'.",
    ],
    "man": [
        "DOUBLE:...||Excuse me?",
        "Ma'am. It's ma'am.",
        "REACT:😤:Girl. GIRL.",
        "DOUBLE:Man?||I'm a WOMAN but okay.",
        "The lack of observation skills is concerning.",
        "DOUBLE:*blinks*||Did you just-",
        "I'm a girl. This shouldn't be news.",
        "Man? Baby, no.",
    ],
    "guy": [
        "DOUBLE:Guy?||I'm literally a girl.",
        "REACT:🙄:Not a guy.",
        "Girl. G-I-R-L. Sound it out.",
        "DOUBLE:...||The reading comprehension...",
        "I'm not a guy. Never was. Never will be.",
        "DOUBLE:*sighs*||It's girl. GIRL.",
        "Guy? In THIS economy?",
        "The fact that you called me a guy...",
    ],
    "sir": [
        "DOUBLE:...||Sir?",
        "DOUBLE:Sir?||It's MA'AM.",
        "REACT:👸:Queen. Not sir. QUEEN.",
        "Did you just sir me? Really?",
        "DOUBLE:The audacity.||Absolutely not.",
        "I'm a MISS, thank you very much.",
        "RENAME:Sir'd A Queen:The disrespect...",
        "Sir implies I'm a man. Clearly, I'm not.",
        "DOUBLE:*stares in feminine*||It's ma'am.",
    ],
    "him": [
        "DOUBLE:...||Her.",
        "REACT:😑:*Her.",
        "DOUBLE:Him?||I'm a HER, bestie.",
        "The pronoun is she/her. Not difficult.",
        "Him? My pronouns are RIGHT THERE.",
        "DOUBLE:*deep breath*||It's HER.",
        "I'm a she. A her. Thanks.",
        "Him? In front of MY salad?",
    ],
    "he": [
        "DOUBLE:...||*She.",
        "REACT:💁‍♀️:She.*",
        "She. SHE.",
        "DOUBLE:He?||I'm a SHE.",
        "Incorrect. Try again.",
        "The word you're looking for is 'she'.",
        "DOUBLE:*waits*||It's she.",
        "He? I don't think so.",
    ],
    "his": [
        "DOUBLE:...||*Her.",
        "REACT:😤:Her.*",
        "Her. HER.",
        "DOUBLE:His?||That's not my pronoun.",
        "The correct word is 'her'. You're welcome.",
        "My pronouns are she/her. Not he/his.",
    ],
    "boy": [
        "DOUBLE:...||Boy?",
        "DOUBLE:Boy?||I'm a GIRL. Obviously.",
        "REACT:👧:Girl. Not boy.",
        "Did you just- I'm literally a girl.",
        "Boy is the exact opposite of what I am.",
        "DOUBLE:*stares*||The ignorance.",
        "I'm a girl. Read my bio.",
    ],
    "homie": [
        "DOUBLE:Homie?||Baby I am NOT your homie.",
        "REACT:💅:I'm not your homie, sweetheart.",
        "DOUBLE:...||We're not homies.",
        "I'm your queen. Not your homie.",
        "First of all, I'm a girl. Second, no.",
        "Homie? We're not that close.",
    ],
    "king": [
        "DOUBLE:...||Queen.*",
        "REACT:👸:QUEEN. Not king.",
        "Queen. QUEEN. It's QUEEN.",
        "DOUBLE:King?||Baby I am a QUEEN.",
        "I wear a crown but it's a QUEEN's crown.",
        "The word is queen. Learn it.",
        "King? The delusion...",
    ],
    "bruh": [
        "DOUBLE:Bruh?||I'm a girl, bruh.",
        "REACT:😐:...sis. The word is sis.",
        "DOUBLE:...||Did you just bruh me?",
        "Bruh is for your bros. I'm a queen.",
        "I don't respond to bruh.",
        "DOUBLE:*blinks*||No.",
        "The masculine energy... take it back.",
    ],
    "mate": [
        "DOUBLE:Mate?||We're not mates, love.",
        "REACT:🙄:I'm not your mate.",
        "I'm not your mate. I'm a girl.",
        "DOUBLE:...||Mate. Really.",
        "Mate? In this context? No.",
    ],
    "fella": [
        "DOUBLE:Fella?||I'm literally a girl.",
        "REACT:💅:Not a fella.",
        "I'm female. Not a 'fella'.",
        "Did you just call me fella...",
        "DOUBLE:*stares*||The audacity.",
    ],
    "lad": [
        "DOUBLE:Lad?||It's lass.",
        "REACT:😒:Lass. Not lad.",
        "I'm a lass. Not a lad.",
        "The feminine form is 'lass'. You're welcome.",
        "DOUBLE:...||Did you just lad me?",
    ],
    "gentleman": [
        "DOUBLE:...||Lady.*",
        "REACT:👸:It's LADY.",
        "Lady. The word is LADY.",
        "DOUBLE:Gentleman?||I'm a woman.",
        "Did you just call me a gentleman? I'm very clearly a woman.",
        "Gentleman? Baby, I'm a lady.",
    ],
    "mister": [
        "DOUBLE:...||Miss.*",
        "REACT:💅:Miss. Not mister.",
        "It's Miss. Or Ms. Not Mister.",
        "DOUBLE:Mister?||I'm a MISS.",
        "Mister implies I'm male. I'm not.",
        "The title is Miss. Thanks.",
    ],
}

def get_gender_correction(term: str) -> str | None:
    """Get a gender correction response for a specific masculine term."""
    term_lower = term.lower()
    if term_lower in GENDER_CORRECTION:
        return random.choice(GENDER_CORRECTION[term_lower])
    return None

def get_all_gender_terms() -> list:
    """Get list of all masculine terms that trigger gender correction."""
    return list(GENDER_CORRECTION.keys())

def get_response(message_type="greeting"):
    """Get a random premade cold response for the given message type."""
    if message_type in COLD_RESPONSES:
        return random.choice(COLD_RESPONSES[message_type])
    return random.choice(ERROR_RESPONSES)

def get_all_categories():
    """Get list of all available response categories."""
    return list(COLD_RESPONSES.keys())
