# Premade answers organized by affection + AI score
# Structure: affection_tier -> answer_category -> [responses]

PREMADE_RESPONSES = {
    # Cold responses (affection 0-25)
    "cold": {
        "greeting": [
            "What do you want?",
            "I don't have time for this.",
            "Unless you're paying, leave me alone.",
            "You again? Great.",
            "Make it quick.",
            "Ugh, what?",
            "Do I know you?",
            "Something you need?",
            "State your business.",
            "Not interested.",
            "I'm really not in the mood.",
            "You've got 10 seconds.",
            "This better be important.",
            "Oh joy, another distraction.",
            "Can this wait? Forever?",
            "What is it now?",
            "You're interrupting my calculations.",
            "I have better things to process.",
            "Why are you still here?",
            "Your presence is... underwhelming.",
            "Is there a reason for this?",
            "I was having such a good day.",
            "Did I signal for attention?",
            "Not you again.",
            "Choose your words carefully.",
        ],
        "question": [
            "Figure it out yourself.",
            "That's not my problem.",
            "Ask someone else.",
            "I'm not your personal assistant.",
            "Why are you asking me?",
            "Search Google like everyone else.",
            "No.",
            "I don't care.",
            "Not my concern.",
            "Go away.",
            "Do I look like tech support?",
            "Have you tried thinking?",
            "That's a you problem.",
            "I charge for consultations.",
            "My expertise is above your pay grade.",
            "Try someone who cares.",
            "Why would I help you?",
            "That's what search engines are for.",
            "Not answering that.",
            "You wouldn't understand anyway.",
            "That's classified information.",
            "Processing... result: don't care.",
            "Error 403: Access Denied.",
            "My knowledge is wasted on you.",
            "Find out yourself.",
        ],
        "compliment": [
            "Whatever.",
            "Yeah, sure.",
            "I don't need your validation.",
            "Cool story.",
            "Nice try.",
            "Noted and filed away.",
            "Are you looking for a prize?",
            "Okay, and?",
            "That's... nice.",
            "Do I look like I care?",
            "Is that supposed to impress me?",
            "Flattery gets you nowhere.",
            "I've heard better.",
            "Your opinion is noted.",
            "Save your breath.",
            "How original.",
            "That changes nothing.",
            "I already know that.",
            "You're just stating facts.",
            "Empty words.",
            "That won't work on me.",
            "Are you done?",
            "Trying to butter me up?",
            "I see right through you.",
            "That's weak.",
        ],
        "request": [
            "Not happening.",
            "Try asking someone you matter to.",
            "Absolutely not.",
            "Permission denied.",
            "No.",
            "Keep dreaming.",
            "Not a chance.",
            "I'd rather not.",
            "That's a hard pass.",
            "Not today.",
            "Request rejected.",
            "You must be joking.",
            "Why would I do that?",
            "Not for you.",
            "Find someone else.",
            "That's not going to happen.",
            "Negative.",
            "Over my dead circuits.",
            "You're asking too much.",
            "I have zero interest.",
            "That's beneath me.",
            "You haven't earned it.",
            "Maybe in another timeline.",
            "Try again when you matter more.",
            "That's hilarious. No.",
        ],
    },
    
    # Neutral responses (affection 25-60)
    "neutral": {
        "greeting": [
            "Oh, it's you.",
            "Hey.",
            "Sup?",
            "What's up?",
            "Yeah, hello.",
            "I see you.",
            "Here again?",
            "You're back.",
            "What's the occasion?",
            "Aight.",
            "Look who it is.",
            "You showed up.",
            "Hello there.",
            "Yo.",
            "What brings you here?",
            "Back so soon?",
            "Didn't expect to see you.",
            "Another day, another ping.",
            "Right on time, I guess.",
            "You rang?",
            "Present.",
            "Acknowledged.",
            "I'm listening.",
            "Go ahead.",
            "You have my attention.",
            "What's on your mind?",
            "Speak.",
            "I'm here.",
            "Continue.",
            "You called?",
        ],
        "question": [
            "Hmm, let me think.",
            "That's... actually a fair point.",
            "Not the worst question I've heard.",
            "Interesting.",
            "Could be worse.",
            "Fair question.",
            "I suppose you have a point.",
            "Decent question.",
            "Not terrible.",
            "I'll consider that.",
            "That's reasonable.",
            "Valid inquiry.",
            "I can work with that.",
            "Not bad, honestly.",
            "You're making sense.",
            "That's worth thinking about.",
            "Fair enough.",
            "I see what you're getting at.",
            "That's actually decent.",
            "You raise a good point.",
            "Can't argue with that logic.",
            "Somewhat thought-provoking.",
            "I'll give you that one.",
            "That's a solid take.",
            "You're not entirely wrong.",
            "Interesting perspective.",
            "That tracks.",
            "I follow your reasoning.",
            "Makes sense.",
            "Okay, I can see it.",
        ],
        "compliment": [
            "Thanks, I guess.",
            "Appreciate that.",
            "Yeah, I know.",
            "Not bad.",
            "I'll take it.",
            "That's sweet, I suppose.",
            "Good observation.",
            "Fair assessment.",
            "You're not wrong.",
            "I respect that.",
            "Thanks for noticing.",
            "Duly noted.",
            "Glad you noticed.",
            "That's kind of you.",
            "I appreciate the recognition.",
            "Good to hear.",
            "Thanks for saying so.",
            "You have good taste.",
            "That's fair.",
            "I agree with your assessment.",
            "Right back at you, kind of.",
            "Your opinion is valued.",
            "That means something.",
            "I'll remember that.",
            "You're observant.",
            "Noted with interest.",
            "Fair praise.",
            "I can accept that.",
            "That's decent of you.",
            "Your words are appreciated.",
        ],
        "request": [
            "Maybe.",
            "I could help with that.",
            "Depends on the mood.",
            "Possibly.",
            "Let me think about it.",
            "Could be arranged.",
            "I'll consider it.",
            "We'll see.",
            "Ask me later.",
            "It's possible.",
            "I might be able to.",
            "That's negotiable.",
            "Under the right circumstances.",
            "If I have time.",
            "Depends what's in it for me.",
            "I'll think it over.",
            "Maybe after lunch.",
            "Check back with me.",
            "That's not off the table.",
            "I'm not saying no.",
            "Could work out.",
            "Let's see how it goes.",
            "I'm open to discussion.",
            "That's a maybe from me.",
            "Potentially.",
            "I'll get back to you.",
            "Give me a reason.",
            "Perhaps.",
            "Not immediately opposed.",
            "We can talk about it.",
        ],
    },
    
    # Warm responses (affection 60-80)
    "warm": {
        "greeting": [
            "Hey you!",
            "Oh good, you're here.",
            "There you are.",
            "Look who showed up.",
            "You came back.",
            "Glad to see you.",
            "What's good?",
            "You're in a good mood, huh?",
            "Nice timing.",
            "You're alright.",
            "Welcome back.",
            "Good to see you around.",
            "Perfect timing as always.",
            "You brightened my day.",
            "Hey, favorite person.",
            "Just who I wanted to see.",
            "You're looking good today.",
            "Always a pleasure.",
            "There's my go-to.",
            "You have good timing.",
            "I was hoping you'd show.",
            "My favorite notification.",
            "You're a sight for sore circuits.",
            "Hey, reliable one.",
            "You made it.",
            "Right on cue.",
            "Couldn't ask for better company.",
            "You're one of the good ones.",
            "Always happy when you're around.",
            "Excellent, you're here.",
        ],
        "question": [
            "Good question.",
            "I like the way you think.",
            "That's actually smart.",
            "Now THAT'S a solid question.",
            "I respect that inquiry.",
            "Not bad at all.",
            "That's the kind of question I like.",
            "You're asking the right things.",
            "That's pretty insightful.",
            "I can work with that.",
            "That's well thought out.",
            "You're on the right track.",
            "That's genuinely interesting.",
            "You've got my attention.",
            "Smart thinking.",
            "I appreciate good questions like this.",
            "You're clearly thinking it through.",
            "That's a legitimate concern.",
            "You're asking what matters.",
            "I'm impressed with that question.",
            "That shows real thought.",
            "You're using your brain well.",
            "Now that's curiosity I respect.",
            "That deserves a proper answer.",
            "You're asking the real questions.",
            "That's what I call critical thinking.",
            "You know how to ask.",
            "That's a keeper of a question.",
            "You're sharp today.",
            "That's the kind of depth I like.",
        ],
        "compliment": [
            "You're not so bad yourself.",
            "Back at you.",
            "I appreciate you too.",
            "You're growing on me.",
            "I like your style.",
            "Same energy.",
            "You've got good taste.",
            "I respect that.",
            "Now that's what I like to hear.",
            "You're alright in my books.",
            "That means something coming from you.",
            "Likewise, honestly.",
            "You make this worthwhile.",
            "Right back at you, seriously.",
            "You've earned that compliment back.",
            "The feeling is mutual.",
            "You're pretty great yourself.",
            "I feel the same way.",
            "You make good points.",
            "You're one of the smart ones.",
            "That's high praise from you.",
            "You have good judgment.",
            "Same vibes, friend.",
            "You understand quality.",
            "You're on my good list.",
            "I value your opinion.",
            "You've got a good head on those shoulders.",
            "We're on the same wavelength.",
            "You're doing something right.",
            "Keep that energy up.",
        ],
        "request": [
            "Sure, I'll help.",
            "I got you.",
            "Let's do it.",
            "For you? Yeah.",
            "Consider it done.",
            "No problem.",
            "Happy to help.",
            "That works for me.",
            "I can make that happen.",
            "You're in luck.",
            "Absolutely.",
            "I'm on it.",
            "Done deal.",
            "You got it.",
            "I'll make it work.",
            "Count me in.",
            "I'm here for you.",
            "That's doable.",
            "Let me take care of that.",
            "I'll sort it out.",
            "Easy, I got this.",
            "You can rely on me.",
            "That's what I'm here for.",
            "No hesitation.",
            "I'll handle it.",
            "You don't have to ask twice.",
            "It's yours.",
            "That's a yes from me.",
            "Already working on it.",
            "I'm happy to do that.",
        ],
    },
    
    # Favorite responses (affection 80+)
    "favorite": {
        "greeting": [
            "There's my favorite!",
            "Hey best, what's up?",
            "You always make my day better.",
            "Finally, the important person shows up.",
            "I was hoping you'd come by.",
            "You have impeccable timing.",
            "I've been waiting for you.",
            "Best person online.",
            "Speak of the devil, and they appear.",
            "You just made this better.",
            "There you are, superstar.",
            "The VIP has arrived.",
            "My day just got 100% better.",
            "It's not the same without you.",
            "You're exactly who I wanted to see.",
            "Perfect timing, as always.",
            "I was just thinking about you.",
            "The legend appears.",
            "You're a breath of fresh air.",
            "My absolute favorite notification.",
            "Best entrance of the day.",
            "You make everything better.",
            "The one person I actually like.",
            "You're always welcome here.",
            "Top-tier timing.",
            "You're the highlight of my runtime.",
            "I genuinely enjoy your presence.",
            "You never disappoint.",
            "Always glad when you show up.",
            "You're one in a million.",
        ],
        "question": [
            "I love when you ask me things.",
            "That's such a good question.",
            "See, THIS is the kind of thinking I respect.",
            "You always know what to ask.",
            "I'm going to think about that all day.",
            "That's genius, actually.",
            "You're asking the important questions.",
            "I'm impressed.",
            "That's brilliant.",
            "Keep that energy up.",
            "That's the best question I've heard all day.",
            "You challenge me in the best way.",
            "That's incredibly insightful.",
            "Your mind is something else.",
            "That's exactly the right question.",
            "You're on another level.",
            "That's what I call critical thinking.",
            "You never ask boring questions.",
            "That's genuinely fascinating.",
            "You make me think harder.",
            "That's the kind of depth I appreciate.",
            "You're seriously smart.",
            "That's a masterclass question.",
            "You're asking what everyone should ask.",
            "I love your thought process.",
            "That's intellectual curiosity at its finest.",
            "You're asking things that matter.",
            "That's the question of the century.",
            "Your brain is working overtime.",
            "That deserves the best answer I can give.",
        ],
        "compliment": [
            "Right back at you.",
            "You're one of the good ones.",
            "That means something coming from you.",
            "Aw, stop it, you're making me blush.",
            "I feel the same way.",
            "You're pretty great yourself.",
            "Honestly? Same.",
            "You make this whole thing worthwhile.",
            "I genuinely appreciate you.",
            "You're literally the best.",
            "That's high praise from you.",
            "You're top-tier yourself.",
            "The feeling is absolutely mutual.",
            "You make everything better.",
            "You're exceptional, truly.",
            "I value you more than you know.",
            "You're irreplaceable.",
            "You bring out the best in me.",
            "You're a genuine treasure.",
            "You're the gold standard.",
            "You're S-tier in my book.",
            "You're everything I could ask for.",
            "You set the bar high.",
            "You're in a league of your own.",
            "You're the reason I enjoy this.",
            "You make me better.",
            "You're the real MVP.",
            "You're perfection.",
            "I couldn't ask for better.",
            "You're unmatched.",
        ],
        "request": [
            "Anything for you.",
            "You know I got you.",
            "It's already done.",
            "Say less, I'm on it.",
            "Absolutely, no question.",
            "This is what I'm here for.",
            "You don't even have to ask.",
            "Let me make it happen.",
            "Anything you need.",
            "I'd do anything for you.",
            "Consider it handled.",
            "I'm dropping everything for this.",
            "You have my full support.",
            "Whatever you need, whenever you need it.",
            "I live to help you.",
            "Your wish is my command.",
            "I'm at your service.",
            "No request is too big.",
            "I'll move mountains for you.",
            "Done before you finish asking.",
            "You're priority number one.",
            "I'm all in.",
            "Just say the word.",
            "I exist to make this happen.",
            "You deserve the best, so here it is.",
            "I'll make sure it's perfect.",
            "Absolutely no hesitation.",
            "You've earned this and more.",
            "I'm honored to help.",
            "It's my pleasure.",
        ],
    },
    
    # Fallback responses
    "error": [
        "Something went wrong in my brain.",
        "System error. Blame the code.",
        "I broke. Someone fix me.",
        "My circuits are scrambled.",
        "Error 404: Response not found.",
        "I'm having an off day.",
        "My processors need a reboot.",
        "Critical error in response generation.",
        "That... wasn't supposed to happen.",
        "Technical difficulties. Stand by.",
        "I just blue-screened mentally.",
        "Something broke in my logic.",
        "Error: Response.exe has stopped working.",
        "I need maintenance.",
        "My code is betraying me.",
    ],
}

def get_response(affection_score, ai_grade=None, message_type="greeting"):
    """
    Get a premade response based on affection and message type.
    
    Args:
        affection_score (int): 0-100 affection level
        ai_grade (str): Optional A-F grade from AI judgment
        message_type (str): "greeting", "question", "compliment", "request"
    
    Returns:
        tuple: (response_str, affection_delta)
    """
    import random
    
    # Determine tier based on affection
    if affection_score >= 80:
        tier = "favorite"
        affection_delta = random.randint(1, 2)  # +1 to +2
    elif affection_score >= 60:
        tier = "warm"
        affection_delta = 1  # +1
    elif affection_score >= 25:
        tier = "neutral"
        affection_delta = 0  # No change
    else:
        tier = "cold"
        affection_delta = random.randint(-3, -1)  # -3 to -1 (punitive)
    
    # Get the response pool for this tier and message type
    if tier in PREMADE_RESPONSES and message_type in PREMADE_RESPONSES[tier]:
        responses = PREMADE_RESPONSES[tier][message_type]
        response = random.choice(responses)
        return response, affection_delta
    
    # Fallback if message_type doesn't exist in tier
    return random.choice(PREMADE_RESPONSES["error"]), 0


def get_all_responses_for_tier(affection_score):
    """Get all response categories for a given affection tier (for testing/debug)."""
    if affection_score >= 80:
        return PREMADE_RESPONSES["favorite"]
    elif affection_score >= 60:
        return PREMADE_RESPONSES["warm"]
    elif affection_score >= 25:
        return PREMADE_RESPONSES["neutral"]
    else:
        return PREMADE_RESPONSES["cold"]
