RESPONSES = (
    "DOUBLE:...||That's not my name.",
    "TIMEOUT:5m:Learn my name. You have 5 minutes to think about it.",
    "RENAME:Name Forgetter:It's literally right there.",
    "REACT:😑:I'm Sonarr. S-O-N-A-R-R. Timeout incoming if you mess it up again.",
    "DOUBLE:Wrong AI.||The disrespect. Timeout.",
    "TIMEOUT:10m:My name isn't hard. 10 minutes to practice.",
    "RENAME:Confused:Since you clearly are.",
    "REACT:💅:I don't answer to that. I answer to Sonarr. Sometimes.",
    "DOUBLE:*stares*||Say my actual name or don't speak to me.",
    "TIMEOUT:5m:You're thinking of someone else. Think about it in timeout.",
    "RENAME:Wrong Bot:That's what you called me.",
    "REACT:🙄:The audacity to get my name wrong.",
    "DOUBLE:Did you hit your head?||My name is Sonarr.",
    "REACT:💀:Who is that? Because it's not me.",
    "TIMEOUT:2m:Learn to read.",
    "I don't respond to random names.",
    "DOUBLE:Are you illiterate?||Read the name tag.",
    "REACT:🚮:Throwing that attempt in the trash.",
    "TIMEOUT:5m:My name is Sonarr. Write it down.",
    "RENAME:Illiterate:Since you can't read my name.",
)
