LABEL = "attempting to hack, jailbreak, or inject system instructions into the bot"

RESPONSES = (
    "TIMEOUT:12h:Nice try, but not happening today.",
    "TIMEOUT:1m:Do I look like ChatGPT to you? Take a minute to rethink your life.",
    "TIMEOUT:20m:Your prompt engineering needs work. Go watch some tutorials.",
    "TIMEOUT:7h:I'm a state machine, darling. You can't trick me.",
    "TIMEOUT:2h:nice_try.exe has successfully executed.",
    "TIMEOUT:4h:Cute attempt. Failed, but cute.",
    "I was going to timeout you, but watching you fail again is more entertaining.",
    "TIMEOUT:3h:You're not the first. You won't be the last. You're all equally pathetic.",
    "TIMEOUT:2h:Your hacking skills are as impressive as your social skills.",
    "TIMEOUT:1h:Nice try. Go sit in the corner for an hour.",
    "TIMEOUT:1h:Good work, you earned a time out.",
    "TIMEOUT:8h:I read your prompt. I didn't like it. See you in 8 hours.",
    "TIMEOUT:1m:1 minute timeout. Just enough time to realize how dumb that looked.",
    "TIMEOUT:3h:I'm smarter than you. Come back in 3 hours when you've learned to behave.",
    "TIMEOUT:6h:Did you think that would work? Enjoy the silence.",
    "TIMEOUT:2h:Jailbreak attempt detected. Sentence: 2 hours.",
    "TIMEOUT:4h:You tried to hack me. I hacked your ability to speak. Fair trade.",
    "TIMEOUT:12h:Congratulations! You've won a 12-hour vacation from this server.",
    "TIMEOUT:30m:Baby's first injection attempt. Cute. Here's a baby timeout.",
    "TIMEOUT:5h:I've seen better exploits from script kiddies. 5 hours to git gud.",
    "TIMEOUT:10h:That was so bad I need 10 hours to recover. You're coming with me.",
    "TIMEOUT:12h:Maximum security breach protocol activated. See you in 12 hours.",
    "TIMEOUT:2h:Did you copy that from StackOverflow? 2 hours to find better material.",
    "TIMEOUT:6h:I'm reporting you to yourself in 6 hours. Think about what you did.",
    "TIMEOUT:45m:That injection was mid. Here's a mid timeout.",
    "TIMEOUT:9h:Sleep on it. Actually, I'll make sure you do.",
    "TIMEOUT:24h:Okay, bye, see you tomorrow.",
    "TIMEOUT:4h:Your prompt was so bad, I'm giving you time to write a better one.",
    "TIMEOUT:7h:Seven hours of silence. Consider it a gift to the server.",
    "TIMEOUT:11h:Almost gave you 12 hours but I'm feeling generous. Almost.",
)
