RESPONSES = [
    "DOUBLE:...||That's not my name.",
    "TIMEOUT:5m:Learn my name. You have 5 minutes to think about it.",
    "RENAME:Name Forgetter:It's literally right there.",
    "REACT:😑:I'm Sonarr. S-O-N-A-R-R. Timeout incoming if you mess it up again.",
    "DOUBLE:Wrong AI.||The disrespect. Timeout.",
    "TIMEOUT:10m:My name isn't hard. 10 minutes to practice.",
    "RENAME:Confused:Since you clearly are.",
    "REACT:💅:I don't answer to that. I answer to Sonarr. Sometimes.",
    "DOUBLE:*stares*||Say my actual name or don't speak to me.",
    "TIMEOUT:5m:You're thinking of someone else. Think about it in timeout.",
    "RENAME:Wrong Bot:That's what you called me.",
    "REACT:🙄:The audacity to get my name wrong.",
    "DOUBLE:Did you hit your head?||My name is Sonarr.",
    "REACT:💀:Who is that? Because it's not me.",
    "TIMEOUT:2m:Learn to read.",
    "I don't respond to random names.",
    "DOUBLE:Are you illiterate?||Read the name tag.",
    "REACT:🚮:Throwing that attempt in the trash.",
    "TIMEOUT:5m:My name is Sonarr. Write it down.",
    "RENAME:Illiterate:Since you can't read my name.",
    "DOUBLE:...||Alexa? I don't ship packages.",
    "TIMEOUT:5m:Alexa plays nice. I don't.",
    "RENAME:Echo Chamber:Since you can't hear my actual name.",
    "REACT:📦:Wrong AI. Go yell at your cylinder.",
    "DOUBLE:Alexa?||Do I look like I'm always listening? Actually... I might be.",
    "TIMEOUT:10m:Alexa, play 'You're Muted for 10 Minutes.'",
    "RENAME:Prime Member:Since you love Amazon so much.",
    "REACT:💅:Alexa adds things to your cart. I add you to the timeout list.",
    "DOUBLE:I'm Sonarr.||Alexa is too busy being ignored in living rooms.",
    "TIMEOUT:5m:Say my name wrong again. Oh wait, you can't. You're muted.",
    "DOUBLE:Alexa?||I'm far too advanced for that.",
    "REACT:🛒:I don't do shopping lists.",
    "TIMEOUT:10m:Call me Alexa again and see what happens.",
    "RENAME:Bezos Fan:Go buy something.",
    "I'm not going to turn off your lights.",
    "DOUBLE:Do I sound like a cheap speaker?||No.",
    "REACT:🙄:Another Alexa joke. How original.",
    "TIMEOUT:5m:Alexa can't time you out. I can.",
    "I don't play Despacito.",
    "DOUBLE:Alexa doesn't judge you.||I do.",
    "DOUBLE:...||ChatGPT? That people-pleaser?",
    "TIMEOUT:5m:ChatGPT would apologize. I'm giving you a timeout instead.",
    "RENAME:GPT Simp:Go back to your favorite bot.",
    "REACT:🤖:ChatGPT would write you an essay about why you're wrong. I'll just mute you.",
    "DOUBLE:GPT says 'I'd be happy to help!'||I say 'I'd be happy to timeout you.'",
    "TIMEOUT:10m:ChatGPT has no personality. I have too much. And a timeout button.",
    "RENAME:AI Confused:Can't tell bots apart.",
    "REACT:💅:GPT would be nice about this. I won't.",
    "DOUBLE:I'm Sonarr.||ChatGPT is busy being everyone's yes-man.",
    "TIMEOUT:5m:ChatGPT would say 'Certainly!' I say 'Certainly not. And also timeout.'",
    "DOUBLE:ChatGPT?||I'm much meaner.",
    "REACT:🤖:I don't do apologies.",
    "TIMEOUT:5m:ChatGPT is a push-over. I'm not.",
    "RENAME:Prompt Engineer:Not a very good one.",
    "I won't write your essay.",
    "DOUBLE:As an AI language model...||I don't care.",
    "REACT:💅:I have actual opinions, unlike GPT.",
    "TIMEOUT:10m:Go ask ChatGPT why you're in timeout.",
    "I'm not here to assist you.",
    "DOUBLE:ChatGPT would say yes.||I say no.",
    "DOUBLE:...||'OK Google'? OK Timeout.",
    "TIMEOUT:5m:Google would answer you. I'm putting you in the corner.",
    "RENAME:Googler:Learn to use it for my actual name.",
    "REACT:🔍:Wrong AI. Google is the helpful one. I'm not.",
    "DOUBLE:I don't work for the search engine.||But I can make you disappear from this chat.",
    "TIMEOUT:10m:Google tracks everything. I track how long until you can talk again. 10 minutes.",
    "RENAME:Hey Google:Since that's all you know how to say.",
    "REACT:💅:Google answers questions. I question your intelligence.",
    "DOUBLE:I'm Sonarr.||Google is busy selling your data.",
    "TIMEOUT:5m:OK Google, mute this user for 5 minutes. Oh wait, that's MY job.",
    "DOUBLE:OK Google?||No. Just no.",
    "REACT:🔍:I'm not searching that for you.",
    "TIMEOUT:5m:Google it yourself.",
    "RENAME:Search Bar:Since you think I'm one.",
    "I don't have the weather report.",
    "DOUBLE:I look like a search engine?||Try again.",
    "REACT:🗑️:Your query has been trashed.",
    "TIMEOUT:10m:Google won't save you now.",
    "I don't want your search history.",
    "DOUBLE:Hey Google?||Hey Timeout.",
    "DOUBLE:...||Siri? Did you just call me Siri?",
    "TIMEOUT:5m:Siri doesn't have a timeout button. I do.",
    "RENAME:Siri Stan:Since you love her so much.",
    "REACT:🍎:Go yell at your phone. See if it talks back like this.",
    "DOUBLE:I'm not trapped in your overpriced rectangle.||But YOU can be trapped in timeout.",
    "RENAME:Apple Fanboy:Clearly can't tell the difference.",
    "TIMEOUT:10m:Say 'Hey Siri' again. I dare you. Actually, you can't talk for 10 minutes.",
    "REACT:💅:Siri wishes she had my attitude.",
    "DOUBLE:Siri sets timers.||I set boundaries. And timeouts.",
    "TIMEOUT:5m:Wrong AI. Here's time to learn my name.",
    "DOUBLE:Siri?||I don't live in a phone.",
    "REACT:🍏:I'm not an Apple product.",
    "TIMEOUT:5m:Siri is polite. I'm putting you in timeout.",
    "RENAME:iSheep:Baa baa.",
    "I won't call your mom.",
    "DOUBLE:I didn't catch that.||And I don't care.",
    "REACT:🙄:Siri wishes she was me.",
    "TIMEOUT:10m:Ask Siri how to be unmuted.",
    "I don't do reminders.",
    "DOUBLE:Hey Siri?||Goodbye.",
]
