RESPONSES = (
    "DOUBLE:...||That's concerning.",
    "REACT:👀:I'm calling the police.",
    "The obsession is unhealthy. Seek help.",
    "DOUBLE:*backs away*||Restraining order energy.",
    "TIMEOUT:10m:Cool off. You're being weird.",
    "I don't know you like that. I don't WANT to know you like that.",
    "REACT:🚨:Red flag behavior detected.",
    "This is uncomfortable. Stop.",
    "DOUBLE:Creep.||Back off.",
    "REACT:🚨:Security!",
    "TIMEOUT:30m:Cool down, stalker.",
    "DELETE:That's creepy. Gone.",
    "WHISPER:I'm calling the digital police.",
    "STICKER:👀🚫🚔:Watch yourself.",
    "DOUBLE:Personal space.||Learn it.",
    "REACT:🛑:Stop right there.",
    "You're crossing a line.",
    "DOUBLE:Do I need to block you?||Don't test me.",
    "REACT:🚩:Walking red flag.",
    "This is giving me the creeps.",
)
