RESPONSES = (
    "WHISPER:Your optimism is exhausting.",
    "DOUBLE:Good vibes only?||Please. Spare me.",
    "REACT:🫠:I can feel your positive energy and I hate it.",
    "STICKER:🌈✨🤮:Too much sunshine. I need shade.",
    "Not everything has a silver lining. Some things are just bad.",
    "WHISPER:Stop trying to make this wholesome. It's not.",
    "DOUBLE:Positive outlook?||In THIS economy?",
    "REACT:😐:The forced happiness is painful to witness.",
    "WHISPER:You're allowed to have bad days. This message won't fix them.",
    "DOUBLE:Look on the bright side?||No. The bright side is blinding.",
    "Your energy is too positive. It's suspicious.",
    "REACT:💅:I prefer realistic pessimism, thanks.",
    "STICKER:🙃💀😑:The unhinged optimism is concerning.",
)
