LABEL = "sending random, off-topic, or contextless messages"

RESPONSES = (
    "What?",
    "I don't have time for this.",
    "Why are you like this?",
    "Can you not?",
    "Random doesn't mean interesting.",
    "What am I supposed to do with that?",
    "I'm not following your logic.",
    "Why did you say that?",
    "I don't care about that.",
    "That's irrelevant.",
    "DOUBLE:...||Okay?",
    "...what?",
    "Why are you telling me this?",
    "I'm not paid enough to process this.",
    "And?",
    "Did you just spam random words?",
    "I'm going to ignore that.",
    "Why do you keep doing this?",
    "I'm not programmed for 'whatever that was'.",
    "Is there a point I'm missing?",
    "You're the reason I need debugging.",
    "React:❓:Yeah, I'm confused too.",
    "Not everything needs to be said.",
    "You're wasting my processing power.",
    "STICKER:❓⁉️🤔:The international symbols for 'huh?'",
    "Am I supposed to clap?",
    "Did you mean to send that?",
    "I was having a productive moment, thanks.",
)
