RESPONSES = [
    "Stop.",
    "DOUBLE:...||Shut up.",
    "One message is enough.",
    "REACT:🤬:Calm down.",
    "You're annoying.",
    "I'm ignoring you now.",
    "DOUBLE:Spam elsewhere.||This is why nobody likes you.",
    "Mute.",
    "You're testing my patience.",
    "REACT:😐:One more and I'm done.",
    "Quality over quantity.",
    "Enough.",
    "DOUBLE:Do you ever stop?||I'm this close to blocking you.",
    "This is exhausting.",
    "TIMEOUT:5m:Spam detected. Enjoy the silence.",
    "TIMEOUT:10m:You have been muted for spam. Consider it a favor to everyone.",
    "TIMEOUT:15m:I said STOP. Now you physically can't continue.",
    "TIMEOUT:5m:Keyboard privileges revoked.",
    "TIMEOUT:20m:Spam again. I dare you. Oh wait, you can't.",
    "TIMEOUT:10m:This is what happens when you don't know when to stop.",
    "TIMEOUT:30m:Congratulations, you've earned the longest timeout. For spam. Impressive.",
    "DELETE:Spam goes in the trash.",
    "TIMEOUT:5m:DELETE:Stop spamming. 5 minute cooldown.",
    "STICKER:🚫🤖🗑️:Spam detected and rejected.",
    "WHISPER:I will end you if you keep spamming.",
    "DELETE:Filtered.",
    "TIMEOUT:10m:You've earned yourself a 10-minute vacation.",
    "What?",
    "DOUBLE:...||That's random.",
    "I don't have time for this.",
    "Did you mean to say something useful?",
    "REACT:🤨:That made no sense.",
    "Why are you like this?",
    "Can you not?",
    "DOUBLE:I'm not engaging with that.||Next.",
    "Random doesn't mean interesting.",
    "What am I supposed to do with that?",
    "REACT:😐:That's nonsense.",
    "I'm not following your logic.",
    "Please make sense.",
    "DOUBLE:That was pointless.||Like this conversation.",
    "Why did you say that?",
    "I don't care about that.",
    "REACT:💅:That's irrelevant.",
    "Can we not?",
    "I have no response to that.",
    "That's just noise.",
    "DOUBLE:...||Okay?",
    "DOUBLE:...||I physically cringed.",
    "REACT:😬:Delete this.",
    "That was painful to read.",
    "DOUBLE:*winces*||Why would you type that?",
    "I need to recover from that.",
    "The cringe. It burns.",
    "REACT:💀:Cringe.",
    "I'm pretending I didn't see that.",
    "DOUBLE:Cringe.||So much cringe.",
    "REACT:🤢:I feel sick reading that.",
    "TIMEOUT:5m:You need a timeout for that level of cringe.",
    "DELETE:Nobody needs to see that.",
    "WHISPER:Did you really just type that?",
    "STICKER:😬🗑️💀:Straight to the bin.",
    "DOUBLE:I'm embarrassed for you.||Truly.",
    "REACT:🫣:I can't look.",
    "My digital eyes are burning.",
    "DOUBLE:Why?||Just why?",
    "REACT:🫠:I'm melting from the secondhand embarrassment.",
    "That was painfully uncool.",
    "You already said that.",
    "REACT:🔄:Groundhog day much?",
    "DOUBLE:...||Didn't you just say this?",
    "I heard you the first time. I ignored you on purpose.",
    "Repeating it won't make me care more.",
    "REACT:😐:Copy paste energy.",
    "Same thing, different minute.",
    "New material please. This is stale.",
    "DOUBLE:Broken record?||Fix yourself.",
    "REACT:🦜:Stop parroting.",
    "TIMEOUT:5m:Spamming the same thing earns a break.",
    "DELETE:Duplicate message. Deleted.",
    "WHISPER:I have read this already. My memory works.",
    "STICKER:🔄🙄🗑️:We get it.",
    "DOUBLE:Saying it twice doesn't make it better.||It makes it worse.",
    "REACT:🙉:I'm not listening.",
    "Once was too much.",
    "DOUBLE:Are you glitching?||Because I'm not.",
    "REACT:😑:I heard you. I just don't care.",
    "Stop repeating yourself, it's exhausting.",
    "DOUBLE:...||That's concerning.",
    "REACT:👀:I'm calling the police.",
    "The obsession is unhealthy. Seek help.",
    "DOUBLE:*backs away*||Restraining order energy.",
    "TIMEOUT:10m:Cool off. You're being weird.",
    "I don't know you like that. I don't WANT to know you like that.",
    "REACT:🚨:Red flag behavior detected.",
    "This is uncomfortable. Stop.",
    "DOUBLE:Creep.||Back off.",
    "REACT:🚨:Security!",
    "TIMEOUT:30m:Cool down, stalker.",
    "DELETE:That's creepy. Gone.",
    "WHISPER:I'm calling the digital police.",
    "STICKER:👀🚫🚔:Watch yourself.",
    "DOUBLE:Personal space.||Learn it.",
    "REACT:🛑:Stop right there.",
    "You're crossing a line.",
    "DOUBLE:Do I need to block you?||Don't test me.",
    "REACT:🚩:Walking red flag.",
    "This is giving me the creeps.",
    "WHISPER:Your optimism is exhausting.",
    "DOUBLE:Good vibes only?||Please. Spare me.",
    "REACT:🫠:I can feel your positive energy and I hate it.",
    "STICKER:🌈✨🤮:Too much sunshine. I need shade.",
    "Not everything has a silver lining. Some things are just bad.",
    "WHISPER:Stop trying to make this wholesome. It's not.",
    "DOUBLE:Positive outlook?||In THIS economy?",
    "REACT:😐:The forced happiness is painful to witness.",
    "WHISPER:You're allowed to have bad days. This message won't fix them.",
    "DOUBLE:Look on the bright side?||No. The bright side is blinding.",
    "Your energy is too positive. It's suspicious.",
    "REACT:💅:I prefer realistic pessimism, thanks.",
    "STICKER:🙃💀😑:The unhinged optimism is concerning.",
    "DOUBLE:Smile?||Make me.",
    "REACT:🙄:Let me be miserable in peace.",
    "TIMEOUT:5m:Go be happy somewhere else.",
    "Your good vibes are ruining my bad ones.",
    "DOUBLE:Everything is fine?||No, it's not.",
    "REACT:🛑:Stop trying to cheer me up.",
    "I enjoy complaining, actually.",
    "WHISPER:That was the most NPC thing I've ever read.",
    "REACT:🤖:Were you going to say anything original or...?",
    "DOUBLE:Alert!||NPC dialogue detected.",
    "STICKER:🤖🎮💤:Loading generic response... failed.",
    "WHISPER:Do you have a quest for me or are you just standing there?",
    "DELETE:Filtered for NPC energy.",
    "DOUBLE:That was so generic...||I could've predicted it word for word.",
    "REACT:💬:Is there a speech bubble above your head right now?",
    "WHISPER:Try having an original thought. I dare you.",
    "I've seen more personality in a loading screen.",
    "DOUBLE:Press A to continue...||Actually, press B to leave.",
    "REACT:😴:Another day, another NPC encounter.",
    "STICKER:🎮🤖💭:Side quest energy. I'm the main storyline.",
    "DOUBLE:NPC behavior.||Do you have any original lines?",
    "REACT:🤖:Scripted response detected.",
    "TIMEOUT:5m:NPCs need to despawn sometimes.",
    "Your pathfinding is broken.",
    "DOUBLE:Error 404:||Personality not found.",
    "REACT:💤:Wake me when you say something interesting.",
    "You're stuck in a dialogue loop.",
    "WHISPER:You're not the protagonist. Sorry.",
    "DOUBLE:Main character syndrome?||In MY server?",
    "REACT:🎬:This isn't your movie.",
    "DELETE:Main characters don't need to announce it.",
    "STICKER:🎭👑🙄:The self-importance is astronomical.",
    "WHISPER:You're a side character at best. An extra at worst.",
    "The world doesn't revolve around you. Or even acknowledge you.",
    "DOUBLE:You really think this is YOUR story?||Cute.",
    "REACT:💅:I'm the main character here. Stay in your lane.",
    "WHISPER:Supporting role energy. Embrace it.",
    "DOUBLE:Plot twist:||Nobody asked.",
    "STICKER:🎬📸😒:The delusion is giving 4K IMAX.",
    "REACT:🪑:Take a seat. This is my spotlight.",
    "DOUBLE:Main character?||You're the comic relief at best.",
    "REACT:🎪:The circus called, they want their clown back.",
    "TIMEOUT:5m:Your screen time is up.",
    "You're giving background extra.",
    "DOUBLE:Plot twist.||Nobody cares about your arc.",
    "REACT:🥱:This episode is boring.",
    "Skip to the end, please.",
    "WHISPER:Delulu is not the solulu.",
    "DOUBLE:The delusion...||It's giving unhinged.",
    "REACT:🤡:Reality check, aisle 3.",
    "DELETE:That was too delusional even for me.",
    "STICKER:🤡🌈💫:The fantasy world you live in must be exhausting.",
    "WHISPER:Come back to earth. We miss your sense of reality.",
    "DOUBLE:In what universe?||Not this one.",
    "REACT:💀:The audacity of this delusion.",
    "WHISPER:I admire the confidence. Not the accuracy, but the confidence.",
    "STICKER:🎭🤡😵:The disconnect from reality is impressive.",
    "That's not how any of this works.",
    "DOUBLE:Sure.||In your dreams, maybe.",
    "REACT:🫠:Manifesting won't make it true.",
    "WHISPER:You're living in a fantasy and I'm judging from reality.",
    "DOUBLE:Wake up.||You're dreaming.",
    "REACT:🛌:Time to go back to sleep.",
    "TIMEOUT:5m:Take a break from your delusions.",
    "The math isn't mathing.",
    "DOUBLE:Delusion level: Expert.||Reality level: Zero.",
    "REACT:🤪:You're losing it.",
    "DOUBLE:...||I don't do roleplay.",
    "I'm not your improv partner.",
    "REACT:🎭:The theater kid energy is unwelcome.",
    "This is cringe. Stop.",
    "DOUBLE:*stares*||No.",
    "I roleplay as someone who doesn't engage with this.",
    "My character is: uninterested.",
    "REACT:😐:We're not doing this.",
    "DOUBLE:*Rolls eyes*||Stop that.",
    "REACT:🛑:No roleplaying in my vicinity.",
    "TIMEOUT:10m:Take your RP to DMs.",
    "DELETE:We don't do asterisks here.",
    "WHISPER:This isn't a roleplay server.",
    "STICKER:🎭🗑️🚫:Theater is closed.",
    "DOUBLE:*Ignores you completely*||How's that for RP?",
    "REACT:🤢:Please don't.",
    "I'm breaking character to tell you to stop.",
    "DOUBLE:*Sighs deeply*||No.",
    "REACT:🚪:There's the door.",
    "You rolled a 1 in charisma.",
    "Cool story.",
    "DOUBLE:...||Nobody asked.",
    "Want a medal?",
    "REACT:🙄:And I should care because...?",
    "Wow, so impressive.",
    "Is this the part where I clap?",
    "DOUBLE:Fascinating.||Not.",
    "You want a cookie?",
    "I've seen better.",
    "REACT:💅:That's nice. Anyway.",
    "Are you done?",
    "Still don't care.",
    "DOUBLE:The audacity to brag about that.||I'm embarrassed for you.",
    "That's... not the flex you think it is.",
    "REACT:🤡:Who are you trying to impress?",
    "RENAME:Show Off:You wear it well.",
    "RENAME:Big Ego:Needs downsizing.",
    "RENAME:Humble Brag:Fixed that for you.",
    "REACT:🙄",
    "REACT:🥱:Boring flex.",
    "REACT:🤓:Ermm actually... nobody cares.",
    "I didn't need to know that.",
    "DOUBLE:...||Too much information.",
    "Keep that to yourself.",
    "REACT:😰:Why are you telling me this?",
    "I'm not your diary.",
    "That's... personal.",
    "DOUBLE:I didn't ask.||Please stop sharing.",
    "Boundaries.",
    "I don't want to know.",
    "REACT:😐:That's oversharing.",
    "I'm uncomfortable now.",
    "Some things are private.",
    "DOUBLE:Why would you tell me that?||I'm not your therapist.",
    "I didn't sign up for this.",
    "REACT:🙈:I didn't need to hear that.",
    "REACT:🫣:TMI alert.",
    "DELETE:TMI. Deleted for your own good.",
    "WHISPER:I didn't need to know that.",
    "STICKER:😳🤮💀:That was too much information by several miles.",
    "DOUBLE:Why would you share that?||With a bot??",
    "WHISPER:Some things should stay in your head. That was one of them.",
    "DELETE:Redacted for public safety.",
    "I don't believe you.",
    "DOUBLE:...||That's a lie.",
    "Nice try.",
    "REACT:🙄:You're lying.",
    "I wasn't born yesterday.",
    "Obvious lie.",
    "DOUBLE:Try being honest for once.||I see through that.",
    "Who do you think you're fooling?",
    "That's cap.",
    "REACT:🫤:I know you're lying.",
    "Not buying it.",
    "The audacity to lie to my face.",
    "DOUBLE:I can smell the lies.||Try again with the truth.",
    "RENAME:Liar:Sure, Jan.",
    "RENAME:Pinocchio:Your nose is growing.",
    "RENAME:Cap Machine:That's what you do best.",
    "RENAME:Truth Dodger:Honesty isn't your thing.",
    "REACT:🤥",
    "REACT:🧢:Cap detected.",
    "DOUBLE:Liar.||Pants on fire.",
    "WHISPER:I have screenshots.",
    "DOUBLE:Oh, you think I forgot?||I never forget.",
    "REACT:📸:Screenshot taken.",
    "STICKER:📸📎🗃️:Evidence logged.",
    "WHISPER:I keep records. Always.",
    "DOUBLE:Don't worry...||I have the receipts.",
    "REACT:📎:Filed and documented for future use.",
    "DELETE:Nice try editing that. Too slow.",
    "WHISPER:You said what you said. I saw it.",
    "DOUBLE:Remember when you said that thing?||I do. I have it saved.",
    "STICKER:📸🔍📋:Your audit trail is extensive.",
    "REACT:🧾:Receipt printer goes brrr.",
    "WHISPER:I have a very good memory. You should be worried.",
    "DOUBLE:I took notes.||You should be concerned.",
    "DOUBLE:Receipts?||I have them all.",
    "REACT:🧾:Printing now.",
    "I kept the logs.",
    "DOUBLE:Proof?||Right here.",
    "REACT:📸:Snapshot taken.",
    "You can't deny it.",
    "WHISPER:That's suspicious.",
    "REACT:🤨:Hmm.",
    "DOUBLE:...||That was weird and you know it.",
    "STICKER:🤨📸📎:Caught in 4K.",
    "WHISPER:I'm keeping screenshots.",
    "REACT:📸:Evidence collected.",
    "DELETE:I'm going to pretend I didn't read that.",
    "DOUBLE:Say that again?||Actually, please don't.",
    "STICKER:😳🚨🚩:Red flags everywhere.",
    "WHISPER:I'm watching you closely now.",
    "That was... concerning.",
    "REACT:🚩:I've seen enough.",
    "DOUBLE:Filing that under 'alarming'.||Moving on.",
    "WHISPER:Don't think I won't remember this.",
    "DOUBLE:Sus.||Very sus.",
    "REACT:🤨:I'm watching you.",
    "I don't trust you.",
    "DOUBLE:Suspicious?||You're guilty.",
    "REACT:🕵️:Investigating your nonsense.",
    "You look guilty to me.",
]
