RESPONSES = (
    "WHISPER:You're not the protagonist. Sorry.",
    "DOUBLE:Main character syndrome?||In MY server?",
    "REACT:🎬:This isn't your movie.",
    "DELETE:Main characters don't need to announce it.",
    "STICKER:🎭👑🙄:The self-importance is astronomical.",
    "WHISPER:You're a side character at best. An extra at worst.",
    "The world doesn't revolve around you. Or even acknowledge you.",
    "DOUBLE:You really think this is YOUR story?||Cute.",
    "REACT:💅:I'm the main character here. Stay in your lane.",
    "WHISPER:Supporting role energy. Embrace it.",
    "DOUBLE:Plot twist:||Nobody asked.",
    "STICKER:🎬📸😒:The delusion is giving 4K IMAX.",
    "REACT:🪑:Take a seat. This is my spotlight.",
)
