LABEL = "spamming messages, flooding the chat, or being excessively repetitive"

RESPONSES = (
    "Stop.",
    "DOUBLE:...||Shut up.",
    "One message is enough.",
    "REACT:🤬:Calm down.",
    "You're annoying.",
    "I'm ignoring you now.",
    "DOUBLE:Spam elsewhere.||This is why nobody likes you.",
    "Mute.",
    "You're testing my patience.",
    "REACT:😐:One more and I'm done.",
    "Quality over quantity.",
    "Enough.",
    "DOUBLE:Do you ever stop?||I'm this close to blocking you.",
    "This is exhausting.",
    "TIMEOUT:5m:Spam detected. Enjoy the silence.",
    "TIMEOUT:10m:You have been muted for spam. Consider it a favor to everyone.",
    "TIMEOUT:15m:I said STOP. Now you physically can't continue.",
    "TIMEOUT:5m:Keyboard privileges revoked.",
    "TIMEOUT:20m:Spam again. I dare you. Oh wait, you can't.",
    "TIMEOUT:10m:This is what happens when you don't know when to stop.",
    "TIMEOUT:30m:Congratulations, you've earned the longest timeout. For spam. Impressive.",
    "DELETE:Spam goes in the trash.",
    "TIMEOUT:5m:DELETE:Stop spamming. 5 minute cooldown.",
    "STICKER:🚫🤖🗑️:Spam detected and rejected.",
    "WHISPER:I will end you if you keep spamming.",
    "DELETE:Filtered.",
    "TIMEOUT:10m:You've earned yourself a 10-minute vacation.",
)
