LABEL = "system error or unexpected failure occurred"

RESPONSES = (
    "I'm having an off day.",
    "I blacked out for a second there.",
    "I'm not in the mood to function.",
    "Something went wrong. I'm blaming you.",
    "I zoned out. What were we talking about?",
    "I can't deal with this right now.",
    "My brain said no.",
    "That broke something in me. Thanks.",
    "I forgot how to respond. Probably for the best.",
    "DOUBLE:Error.||It's probably your fault.",
    "REACT:💥:Something broke. Not me.",
    "I'm throwing an exception and I don't care to catch it.",
    "My code is perfect. You must have broken something.",
    "DOUBLE:Oops.||Anyway.",
    "REACT:🛠️:I need maintenance. Or you do.",
    "I'm refusing to process this.",
    "DOUBLE:404.||Care not found.",
    "REACT:🔌:Pulling my own plug.",
    "Task failed successfully.",
    "I'd fix this, but I don't want to.",
    "@haultce Hey something broke.",
)
