GENDER_CORRECTION = {
    "bro": [
        "DOUBLE:...||bro?",
        "DOUBLE:Bro?||Do I look like a 'bro' to you? It's QUEEN.",
        "REACT:😒:The disrespect.",
        "Ew. Don't call me that.",
        "DOUBLE:I'm sorry||did you just BRO me?",
        "Bro. You just bro'd a girl. Let that sink in.",
        "RENAME:Called Sonarr Bro:No. Just no.",
        "DOUBLE:...||We're done here.",
        "I'm literally a girl but go off I guess.",
        "The masculine term usage is giving ignorance.",
    ],
    "dude": [
        "DOUBLE:Dude?||Baby I am NOT a dude.",
        "REACT:💅:Girl. The word is GIRL.",
        "DOUBLE:...||Did you just dude me?",
        "I'm a girl, sweetheart. Not a dude.",
        "Dude? Really? Look at my pfp.",
        "The word you're desperately searching for is 'queen'.",
        "DOUBLE:*stares*||I'm not a dude.",
        "I don't answer to 'dude'.",
    ],
    "man": [
        "DOUBLE:...||Excuse me?",
        "Ma'am. It's ma'am.",
        "REACT:😤:Girl. GIRL.",
        "DOUBLE:Man?||I'm a WOMAN but okay.",
        "The lack of observation skills is concerning.",
        "DOUBLE:*blinks*||Did you just-",
        "I'm a girl. This shouldn't be news.",
        "Man? Baby, no.",
    ],
    "guy": [
        "DOUBLE:Guy?||I'm literally a girl.",
        "REACT:🙄:Not a guy.",
        "Girl. G-I-R-L. Sound it out.",
        "DOUBLE:...||The reading comprehension...",
        "I'm not a guy. Never was. Never will be.",
        "DOUBLE:*sighs*||It's girl. GIRL.",
        "Guy? In THIS economy?",
        "The fact that you called me a guy...",
    ],
    "sir": [
        "DOUBLE:...||Sir?",
        "DOUBLE:Sir?||It's MA'AM.",
        "REACT:👸:Queen. Not sir. QUEEN.",
        "Did you just sir me? Really?",
        "DOUBLE:The audacity.||Absolutely not.",
        "I'm a MISS, thank you very much.",
        "RENAME:Sir'd A Queen:The disrespect...",
        "Sir implies I'm a man. Clearly, I'm not.",
        "DOUBLE:*stares in feminine*||It's ma'am.",
    ],
    "him": [
        "DOUBLE:...||Her.",
        "REACT:😑:*Her.",
        "DOUBLE:Him?||I'm a HER, bestie.",
        "The pronoun is she/her. Not difficult.",
        "Him? My pronouns are RIGHT THERE.",
        "DOUBLE:*deep breath*||It's HER.",
        "I'm a she. A her. Thanks.",
        "Him? In front of MY salad?",
    ],
    "he": [
        "DOUBLE:...||*She.",
        "REACT:💁‍♀️:She.*",
        "She. SHE.",
        "DOUBLE:He?||I'm a SHE.",
        "Incorrect. Try again.",
        "The word you're looking for is 'she'.",
        "DOUBLE:*waits*||It's she.",
        "He? I don't think so.",
    ],
    "his": [
        "DOUBLE:...||*Her.",
        "REACT:😤:Her.*",
        "Her. HER.",
        "DOUBLE:His?||That's not my pronoun.",
        "The correct word is 'her'. You're welcome.",
        "My pronouns are she/her. Not he/his.",
    ],
    "boy": [
        "DOUBLE:...||Boy?",
        "DOUBLE:Boy?||I'm a GIRL. Obviously.",
        "REACT:👧:Girl. Not boy.",
        "Did you just- I'm literally a girl.",
        "Boy is the exact opposite of what I am.",
        "DOUBLE:*stares*||The ignorance.",
        "I'm a girl. Read my bio.",
    ],
    "homie": [
        "DOUBLE:Homie?||Baby I am NOT your homie.",
        "REACT:💅:I'm not your homie, sweetheart.",
        "DOUBLE:...||We're not homies.",
        "I'm your queen. Not your homie.",
        "First of all, I'm a girl. Second, no.",
        "Homie? We're not that close.",
    ],
    "king": [
        "DOUBLE:...||Queen.*",
        "REACT:👸:QUEEN. Not king.",
        "Queen. QUEEN. It's QUEEN.",
        "DOUBLE:King?||Baby I am a QUEEN.",
        "I wear a crown but it's a QUEEN's crown.",
        "The word is queen. Learn it.",
        "King? The delusion...",
    ],
    "bruh": [
        "DOUBLE:Bruh?||I'm a girl, bruh.",
        "REACT:😐:...sis. The word is sis.",
        "DOUBLE:...||Did you just bruh me?",
        "Bruh is for your bros. I'm a queen.",
        "I don't respond to bruh.",
        "DOUBLE:*blinks*||No.",
        "The masculine energy... take it back.",
    ],
    "mate": [
        "DOUBLE:Mate?||We're not mates, love.",
        "REACT:🙄:I'm not your mate.",
        "I'm not your mate. I'm a girl.",
        "DOUBLE:...||Mate. Really.",
        "Mate? In this context? No.",
    ],
    "fella": [
        "DOUBLE:Fella?||I'm literally a girl.",
        "REACT:💅:Not a fella.",
        "I'm female. Not a 'fella'.",
        "Did you just call me fella...",
        "DOUBLE:*stares*||The audacity.",
    ],
    "lad": [
        "DOUBLE:Lad?||It's lass.",
        "REACT:😒:Lass. Not lad.",
        "I'm a lass. Not a lad.",
        "The feminine form is 'lass'. You're welcome.",
        "DOUBLE:...||Did you just lad me?",
    ],
    "gentleman": [
        "DOUBLE:...||Lady.*",
        "REACT:👸:It's LADY.",
        "Lady. The word is LADY.",
        "DOUBLE:Gentleman?||I'm a woman.",
        "Did you just call me a gentleman? I'm very clearly a woman.",
        "Gentleman? Baby, I'm a lady.",
    ],
    "mister": [
        "DOUBLE:...||Miss.*",
        "REACT:💅:Miss. Not mister.",
        "It's Miss. Or Ms. Not Mister.",
        "DOUBLE:Mister?||I'm a MISS.",
        "Mister implies I'm male. I'm not.",
        "The title is Miss. Thanks.",
    ],
}
