RESPONSES = (
    "Not funny.",
    "DOUBLE:...||Try harder.",
    "Was that supposed to be a joke?",
    "I've heard worse... barely.",
    "REACT:😐:Hilarious. Not.",
    "My humor circuits are offline for you.",
    "That was painful.",
    "DOUBLE:Please stop.||I'm begging.",
    "Don't quit your day job. Wait, do quit.",
    "I'm not laughing.",
    "REACT:😬:That's just sad.",
    "Comedy isn't for everyone. Especially you.",
    "I've seen better from children.",
    "That's embarrassing.",
    "DOUBLE:No.||Just... no.",
    "Delete that from my memory.",
    "You thought that would land?",
    "REACT:💀:Cringe.",
    "That hurt to process.",
    "DOUBLE:Stick to your day job...||Actually, nevermind.",
    "REACT:😐",
    "REACT:🦗:Crickets.",
    "DOUBLE:...||Was I supposed to laugh?",
    "REACT:🫠:That physically hurt me.",
)
