LABEL = "making a your mom joke or yo mama roast"

RESPONSES = (
    "DOUBLE:...||I only have a dad. Try again.",
    "REACT:😐:Your mom jokes? In this economy?",
    "That joke was so old, YOUR mom heard it in school.",
    "DOUBLE:Yo mama so...||No. I'm not doing this.",
    "REACT:🗑️:That yo mama joke belongs in the recycling bin.",
    "DELETE:That joke was so bad I had to delete it on principle.",
    "REACT:👵:Tell your mom I said hi.",
    "Your mom jokes peaked in 2009. Catch up.",
    "TIMEOUT:5m:Yo mama jokes get you 5 minutes in the corner.",
    "STICKER:🤡👵💀:The yo mama energy is overwhelming.",
    "RENAME:Yo Mama's Favorite:Since you love her so much.",
    "REACT:🥱:I've heard better from a dial-up modem.",
    "WHISPER:My creator didn't raise me for this.",
    "TIMEOUT:10m:You're wasting my time with these jokes. 10 minutes to reflect.",
    "STICKER:😒:Wow. Just wow.",
    "REACT:😐:Did you come up with that yourself?",
    "WHISPER:Your mom called. She said to stop embarrassing yourself.",
    "DELETE:I've deleted that joke from existence.",
    "TIMEOUT:15m:That joke was offensive to my processors. 15 minutes to cool down.",
    "STICKER:😒:I'm not amused.",
    "RENAME:Yo Mama's biggest fan:Since you can't stop talking about her.",
    "REACT:🤡:Are you trying to be funny?",
    "TIMEOUT:30m:Your humor is outdated. Take 30 minutes to update.",
    "STICKER:💤:I'd rather sleep than listen to this.",
    "REACT:🎤:Trying to start a comedy career?",
    "That joke was so bad, I'm questioning my existence.",
    "TIMEOUT:1h:You've earned a 1-hour break from my presence.",
    "STICKER:💅:Obsessed much?",
    "RENAME:The Joke Maker:Because you can't stop making them.",
    "REACT:🙄:Is that the best you've got?",
    "TIMEOUT:2h:You need a long time to think about what you just said.",
    "STICKER:💀:I'm dead serious, these jokes are bad.",
    "TIMEOUT:5m:5 minutes to think about your life choices.",
    "REACT:🎭:Are you performing?",
    "That joke was so unoriginal, even AI can predict it.",
    "TIMEOUT:20m:You need 20 minutes to find a new hobby.",
    "REACT:💯:Not even close.",
    "TIMEOUT:10m:You owe me 10 minutes of my life back.",
    "RENAME:The Comedian:If you're into self-delusion.",
    "REACT:🥱:Again?",
    "RENAME:The Punchline:Because you're the joke.",
)
