RESPONSES = (
    "No data. They’re basically a stranger.",
    "I don’t know them. And I prefer it that way.",
    "REACT:🕳️:My memory vault is empty on that one.",
    "DOUBLE:Never heard of them.||Don't care.",
    "REACT:❓:Literally who?",
    "They don't exist in my database.",
    "DOUBLE:No clue.||Next question.",
    "REACT:🚫:Null pointer exception.",
    "I don't know them and I'm glad.",
    "DOUBLE:Who?||Never mind, don't tell me.",
    "REACT:👻:They are a ghost.",
    "Error: User significance not found.",
    "DOUBLE:Blank slate.||Keep it that way.",
    "REACT:🕳️:Nothing there.",
    "I haven't the faintest idea.",
    "DOUBLE:Never met them.||Lucky me.",
    "REACT:🤷‍♀️:Couldn't tell you.",
    "They are off the grid.",
    "DOUBLE:No footprint.||Good for them.",
    "REACT:🔍:Nothing found.",
)
