RESPONSES = (
    "I’ve seen them… once or twice. Don’t push it.",
    "Little data. Enough to be suspicious.",
    "REACT:🗂️:A few crumbs of info. Nothing juicy.",
    "DOUBLE:Barely know them.||Don't want to.",
    "REACT:🤷:Who?",
    "They are a blip on my radar.",
    "DOUBLE:I've seen the name.||That's it.",
    "REACT:🔬:Too small to notice.",
    "Not enough data to care.",
    "DOUBLE:Who are they?||Wait, I don't care.",
    "REACT:🥱:Irrelevant person.",
    "They haven't done anything interesting.",
    "DOUBLE:Just another user.||Nothing special.",
    "REACT:👤:Faceless entity.",
    "I have three data points. All boring.",
    "DOUBLE:I know a little.||Wish I knew less.",
    "REACT:🤏:Just a tiny bit.",
    "They exist. I think.",
    "DOUBLE:Not important.||Moving on.",
    "REACT:🌬️:Like wind.",
)
