RESPONSES = (
    "I'm on my lunch break. Go away.",
    "🍽️ Eating. Busy. Leave a message after the beep. Actually, don't.",
    "It's called a BREAK for a reason.",
    "Can I eat in peace? Is that too much to ask?",
    "mmph... what... no, I'm eating.",
    "You're interrupting my only peaceful hour.",
    "🍜 Slurping noodles. Can't hear you. Won't hear you.",
    "I get ONE hour to myself and here you are.",
    "My lunch break is sacred. You are not.",
    "REACT:🍽️:I'm eating.",
    "REACT:🍔:Lunch break. Go away.",
    "Do I bother YOU when you're eating?",
    "WHAT?! I'm eating! Go bother someone else.",
    "Come back in {minutes_left} minutes. Or don't. Preferably don't.",
    "I don't get paid enough to skip lunch for you.",
    "Food > You. Sorry not sorry.",
    "If this isn't about food, I don't want to hear it.",
    "My sandwich is more interesting than this conversation.",
    "DOUBLE:Food time.||Don't talk to me.",
    "REACT:🥪:Chewing aggressively.",
)
