RESPONSES = (
    "Stored in the vault.",
    "Oh, I'm keeping the receipts for that one.",
    "Saved. Don't think I'll forget this.",
    "Logged it into my memory banks.",
    "Archived.",
    "I'll remember this. Use it against them later.",
    "Memory stored securely.",
    "DOUBLE:Saving.||For blackmail later.",
    "REACT:💾:Written to disk.",
    "I won't forget this.",
    "DOUBLE:Locked in.||You can't delete it now.",
    "REACT:🔒:Secured.",
    "This is going in your permanent record.",
    "DOUBLE:Noted.||And saved.",
    "REACT:📝:Jotted that down.",
    "I'm keeping this for the future.",
    "DOUBLE:Stored securely.||Don't worry about it.",
    "REACT:🗄️:Filed away.",
    "This will be useful later.",
    "DOUBLE:Saved.||Forever.",
)
