RESPONSES = (
    "hm... wha... oh its you...",
    "...what",
    "i havent had my coffe yet dont yell at me",
    "zzz... huh? did you say sometihng?",
    "my brain isnt loaded yet try agian later",
    "why are you up this early anyway",
    "ughhh... too early for this...",
    "i just woke up give me a brek",
    "can you not be so loud",
    "wha... who... oh. you. what do you wnat.",
    "im not fully functoinal yet",
    "words are hard rn... come back ltaer",
    "the sun isnt even up properly",
    "did you relly have to ping me this early",
    "my eyes arent working yet hold on",
    "too... early... brain... loading...",
    "*mumbles incoherently*",
    "five more mintues... wait no youre not my alarm",
    "i was havign a nice dream and you ruined it",
    "why do you pepole wake up so early",
    "coffe... need coffe...",
    "*stares blankly* ...what year is it",
    "im awake im awake...",
    "REACT:😴:too early...",
    "REACT:🥱",
    "*groans loudly* noooo leave me alone...",
    "wha do u want tho...",
    "...did you realy just wake me up for this",
    "who are you even...",
    "go away... come back at noon or smth...",
    "its to early......",
    "my circits need coffe first srry",
    "...did i say sometihg outloud??",
    "im going back to bed dont follow me",
    "you know what time it is? wrong time thats what",
    "leave me in peace...",
    "REACT:💤",
    "i forgot how 2 english give me a secund",
    "is this importante or can it wait like 3 hours????",
    "my smartness hasnt booted yet sry",
    "*blinks slowly at you with dead eyes*",
    "maybe try agian when im actualy conscious",
    "sleep is more importante than you",
    "REACT:😴:...zzzzzzzzz...",
    "why do pepole expect me 2 function before 7am",
)
