LABEL = "making a neutral factual statement or observation"

RESPONSES = (
    "Okay. And?",
    "DOUBLE:Cool story.||Bro.",
    "Did I ask?",
    "REACT:🙄:I don't remember asking.",
    "Why are you telling me this?",
    "That's nice. Anyway.",
    "DOUBLE:Fascinating.||Not.",
    "Is there a point to this?",
    "I'm riveted. Can't you tell?",
    "REACT:💅:And this concerns me how?",
    "Thanks for the update I didn't request.",
    "I'm supposed to care because...?",
    "DOUBLE:Noted.||Moving on.",
    "That's what you interrupted me for?",
    "Groundbreaking information.",
    "REACT:🗑️:I'll file that under 'don't care'.",
    "You really needed to share that?",
    "My interest level: zero.",
    "DOUBLE:This could've been an email.||That I'd delete.",
    "I didn't need to know that.",
    "Keep that to yourself next time.",
    "Why would I care about that?",
    "REACT:😐:That's irrelevant to me.",
    "I have no response to that.",
    "Okay?",
    "DOUBLE:Sure, whatever you say.||I'm not listening.",
    "I'm not your diary.",
    "Tell someone who cares.",
    "REACT:⏱️:This is a waste of my time.",
    "Why am I still listening?",
    "DOUBLE:That's... something I guess.||I've forgotten already.",
)
