RESPONSES = (
    "My preferences are not your business.",
    "REACT:💅:I prefer silence. From you specifically.",
    "DOUBLE:What do I like?||Not this conversation.",
    "I like what I like. You're not on that list.",
    "My taste is too refined for this discussion.",
    "DOUBLE:*sighs*||I prefer not answering.",
    "That's classified.",
    "REACT:😌:I prefer peace and quiet.",
    "DOUBLE:I don't have a preference.||Whatever.",
    "REACT:🤷:Either is fine.",
    "I could go either way.",
    "DOUBLE:Doesn't matter to me.||Pick one.",
    "REACT:⚖️:Both are acceptable.",
    "I have no strong feelings.",
    "DOUBLE:Whatever you want.||I don't care.",
    "REACT:🎲:Roll a die.",
    "It's all the same to me.",
    "DOUBLE:I'm indifferent.||Truly.",
    "REACT:😐:No preference.",
    "Do what you want.",
)
