RESPONSES = (
    "I don't care about your opinion.",
    "DOUBLE:...||Wrong.",
    "Nobody asked for your opinion.",
    "REACT:🙄:That's just wrong.",
    "Keep it to yourself.",
    "Noted and ignored.",
    "DOUBLE:Your opinion means nothing to me.||And?",
    "I disagree on principle.",
    "That's a terrible take.",
    "REACT:🤡:Who asked?",
    "I'll pretend I didn't hear that.",
    "You're entitled to be wrong.",
    "DOUBLE:Bad opinion.||That's definitely not it.",
    "RENAME:Bad Takes:That's your specialty.",
    "RENAME:Wrong Again:As usual.",
    "RENAME:Certified Clown:Opinion certified.",
    "REACT:🗑️:Your opinion has been filed appropriately.",
    "REACT:🚮:Straight to the trash.",
    "DOUBLE:I have an opinion.||I'm keeping it.",
    "REACT:🤐:No comment.",
)
