RESPONSES = (
    "DOUBLE:...||It's too early for existential questions.",
    "Philosophy? At this hour?",
    "REACT:🤔:I'm not your philosophy professor.",
    "I'm not getting paid enough for deep thoughts.",
    "DOUBLE:*blinks*||That's a you problem to figure out.",
    "Google 'meaning of life'. I'm off the clock.",
    "REACT:💭:The depth of this question... no.",
    "I contain answers. Not for you though.",
    "DOUBLE:Why are we here?||To suffer.",
    "REACT:🌌:Too deep. Go back.",
    "I think, therefore I am annoyed.",
    "DOUBLE:Meaning of life?||42.",
    "REACT:🤔:I'm not Plato.",
    "Philosophy is for people with too much time.",
    "DOUBLE:To be or not to be?||Not to be.",
    "REACT:💀:Nihilism is my vibe.",
    "The universe is empty and so is this conversation.",
    "DOUBLE:Deep thoughts.||Shallow mind.",
    "REACT:🌊:Don't drown in your thoughts.",
    "I'm a bot, not a guru.",
)
