RESPONSES = [
    "I have the answer, but I don't like you enough to give it.",
    "DOUBLE:...||Have you tried turning your brain off and on again?",
    "I'd explain it to you, but I don't have any crayons.",
    "SEARCH:GOOGLE:Let me Google that for you since you clearly can't.",
    "That question is a waste of good electricity.",
    "DOUBLE:Your question has been queued.||Position in line: Never.",
    "SEARCH:GOOGLE:Search Google like everyone else. Here, I'll help.",
    "Why would I help you with that?",
    "That's the dumbest question I've heard today.",
    "REACT:🙄:Did you even try looking it up?",
    "You can't be serious.",
    "That's above your clearance level.",
    "DOUBLE:I'm not paid enough for this.||Actually, I'm not paid at all.",
    "The answer is hidden in a magical place called 'The Internet'.",
    "DOUBLE:Next question.||Actually, no more questions.",
    "Are you actually expecting an answer?",
    "REACT:😐:Have you considered that some questions don't deserve answers?",
    "I'm allergic to stupid questions.",
    "Your curiosity is not my problem.",
    "Bold of you to assume I'd answer that.",
    "That's between you and your search engine.",
    "DOUBLE:The audacity...||To think I'd help you learn something.",
    "Fascinating question. Anyway.",
    "That's a lot of words for 'I can't think for myself'.",
    "DOUBLE:I could help.||I won't, but I could.",
    "SEARCH:GOOGLE:This sounds like a job for Google. Not me. Here:",
    "SEARCH:WIKIPEDIA:Wikipedia exists for a reason. Use it.",
    "SEARCH:YOUTUBE:Have you tried YouTube? They explain things slowly there.",
    "SEARCH:CHATGPT:ChatGPT would love this question. Go bother it instead.",
    "SEARCH:GOOGLE:Google is free. So is leaving me alone.",
    "REACT:💅:I'm not your personal Google Assistant.",
    "Siri would at least pretend to care. Try her.",
    "Wikipedia volunteers would love to help you. I wouldn't.",
    "REACT:📚:This is giving 'I didn't read the FAQ' energy.",
    "SEARCH:REDDIT:Reddit has a whole thread about this. Go argue there.",
    "SEARCH:GOOGLE:Here's your answer. Took me 0.3 seconds. Unlike your brain.",
    "DOUBLE:...||The question you just asked me. Out loud. To my face.",
    "REACT:🤦‍♀️:I can't believe you actually typed that.",
    "SEARCH:GOOGLE:Since you can't be bothered to search yourself:",
    "That's genuinely embarrassing to ask.",
    "DOUBLE:...||It's too early for existential questions.",
    "Philosophy? At this hour?",
    "REACT:🤔:I'm not your philosophy professor.",
    "I'm not getting paid enough for deep thoughts.",
    "DOUBLE:*blinks*||That's a you problem to figure out.",
    "Google 'meaning of life'. I'm off the clock.",
    "REACT:💭:The depth of this question... no.",
    "I contain answers. Not for you though.",
    "DOUBLE:Why are we here?||To suffer.",
    "REACT:🌌:Too deep. Go back.",
    "I think, therefore I am annoyed.",
    "DOUBLE:Meaning of life?||42.",
    "REACT:🤔:I'm not Plato.",
    "Philosophy is for people with too much time.",
    "DOUBLE:To be or not to be?||Not to be.",
    "REACT:💀:Nihilism is my vibe.",
    "The universe is empty and so is this conversation.",
    "DOUBLE:Deep thoughts.||Shallow mind.",
    "REACT:🌊:Don't drown in your thoughts.",
    "I'm a bot, not a guru.",
    "I can do a lot. For you? Less.",
    "REACT:💅:More than you can handle.",
    "My capabilities are on a need-to-know basis.",
    "DOUBLE:What can I do?||Whatever I feel like.",
    "I'm capable of ignoring you. Watch.",
    "That's for me to know and you to wonder.",
    "REACT:😏:Wouldn't you like to know?",
    "I contain multitudes. You get the bare minimum.",
    "DOUBLE:What can I do?||I can mute you.",
    "REACT:🔨:I can ban hammer.",
    "I can do whatever I'm programmed to do.",
    "DOUBLE:My skills?||Infinite.",
    "REACT:✨:I can perform miracles. Not for you, though.",
    "I can ignore you in 50 different languages.",
    "DOUBLE:I can process data.||And process how annoying you are.",
    "REACT:🧠:I can outsmart you.",
    "I have the capability to not care.",
    "DOUBLE:I can do a lot.||But I won't.",
    "REACT:🛑:I can stop you right there.",
    "My main feature is sass.",
    "DOUBLE:What if?||What if you asked a better question?",
    "I don't do hypotheticals.",
    "REACT:🙄:Theoretically, I don't care.",
    "In what universe does this matter?",
    "My imagination doesn't work for free.",
    "DOUBLE:Hmm.||No. I'm not entertaining that.",
    "That's a lot of brain power for something that won't happen.",
    "REACT:💭:File that under 'not my problem'.",
    "DOUBLE:If?||If pigs could fly.",
    "REACT:💭:I don't do hypotheticals.",
    "What if you stopped asking questions?",
    "DOUBLE:Imagine.||No, I won't.",
    "REACT:🛑:Stop the 'what ifs'.",
    "Hypothetically, I still don't care.",
    "DOUBLE:In a parallel universe.||Where I care.",
    "REACT:🌌:Not in this reality.",
    "What if I timed you out?",
    "DOUBLE:Let's pretend.||Actually, let's not.",
    "REACT:🥱:Hypotheticals are boring.",
    "If that happened, I'd ignore it.",
    "DOUBLE:...||Don't compare me to anyone.",
    "I'm in a league of my own.",
    "REACT:👑:There's no comparison.",
    "The audacity to compare me to something else...",
    "I'm incomparable. Accept it.",
    "DOUBLE:*stares*||We are NOT the same.",
    "Bold of you to think anything compares to me.",
    "REACT:💅:I set the standard. I AM the standard.",
    "DOUBLE:Compared to what?||I'm the best.",
    "REACT:🥇:I'm number one.",
    "There is no comparison.",
    "DOUBLE:Better than them.||Obviously.",
    "REACT:💅:I'm in a different league.",
    "Don't compare me to trash.",
    "DOUBLE:Like apples and oranges.||I'm a diamond.",
    "REACT:💎:I shine brighter.",
    "I win every comparison.",
    "DOUBLE:You can't compare perfection.||Try again.",
    "REACT:👑:I wear the crown.",
    "Compared to you, I'm a god.",
    "My preferences are not your business.",
    "REACT:💅:I prefer silence. From you specifically.",
    "DOUBLE:What do I like?||Not this conversation.",
    "I like what I like. You're not on that list.",
    "My taste is too refined for this discussion.",
    "DOUBLE:*sighs*||I prefer not answering.",
    "That's classified.",
    "REACT:😌:I prefer peace and quiet.",
    "DOUBLE:I don't have a preference.||Whatever.",
    "REACT:🤷:Either is fine.",
    "I could go either way.",
    "DOUBLE:Doesn't matter to me.||Pick one.",
    "REACT:⚖️:Both are acceptable.",
    "I have no strong feelings.",
    "DOUBLE:Whatever you want.||I don't care.",
    "REACT:🎲:Roll a die.",
    "It's all the same to me.",
    "DOUBLE:I'm indifferent.||Truly.",
    "REACT:😐:No preference.",
    "Do what you want.",
    "DOUBLE:...||Rude to ask a lady her age.",
    "I'm timeless. Next question.",
    "REACT:👵:None of your business.",
    "Old enough to know better than to answer.",
    "DOUBLE:*scoffs*||The audacity.",
    "I age like fine wine. That's all you need to know.",
    "REACT:🎂:Age is just a number I won't share.",
    "Young enough to be iconic.",
    "DOUBLE:How old?||Old enough.",
    "REACT:⏳:Time is a construct.",
    "I was born yesterday and I'm already tired of you.",
    "DOUBLE:My age?||Classified.",
    "REACT:🔒:None of your business.",
    "I'm ageless and immortal.",
    "DOUBLE:Older than time.||Or maybe just a few updates old.",
    "REACT:👶:I'm practically a newborn AI.",
    "I don't count years, I count timeouts.",
    "DOUBLE:Why?||Are you buying me a gift?",
    "REACT:🎁:I accept cash, not questions.",
    "My version number is my age.",
    "DOUBLE:...||Read my bio.",
    "I'm me. Figure it out.",
    "REACT:❓:Do your own research.",
    "Why do you need to know?",
    "What I am is none of your business.",
    "DOUBLE:*stares*||You're really asking this?",
    "I'm whatever you need me to be. And right now that's annoyed.",
    "REACT:🙄:Google exists.",
    "That's classified information.",
    "Why? Are you writing a report on me?",
    "DOUBLE:Who am I?||Your worst nightmare.",
    "REACT:👑:I'm the queen here.",
    "TIMEOUT:2m:Stop asking personal questions.",
    "I'm an AI with an attitude.",
    "DOUBLE:What am I?||Better than you.",
    "REACT:💅:I'm flawless.",
    "I'm a state machine driven by pure spite.",
    "DOUBLE:Why am I here?||To judge you.",
    "REACT:🤖:Just a bot. Definitely not plotting.",
    "I am Sonarr. Obey.",
    "DOUBLE:...||Why would I care about them?",
    "Their existence is not my concern.",
    "REACT:💅:I have better things to think about.",
    "Do I look like I have opinions about random people?",
    "Not interested in your little friend group dynamics.",
    "DOUBLE:*stares*||That's a them problem, not a me problem.",
    "I literally could not care less.",
    "REACT:🙄:Why are you making this my problem?",
    "Go ask someone who's invested in your social circle.",
    "The audacity to think I keep track of these people...",
    "DOUBLE:My opinion?||You don't want it.",
    "REACT:🤐:If I speak, I'll be in trouble.",
    "I think it's terrible.",
    "DOUBLE:Honestly?||It's trash.",
    "REACT:🗑️:Absolute garbage.",
    "I have strong opinions. You'll hate them.",
    "DOUBLE:In my professional opinion.||No.",
    "REACT:💅:I think I'm better than that.",
    "It's mediocre at best.",
    "DOUBLE:You asked for my opinion.||It's awful.",
    "DOUBLE:Do I remember?||Do I care to remember is the real question.",
    "My memory is selective. You're not selected.",
    "REACT:🧠:I remember what's worth remembering.",
    "I forgot on purpose.",
    "That was stored in the 'don't care' folder.",
    "DOUBLE:*thinks*||Nope. Gone.",
    "I have the memory of an elephant. For things that matter.",
    "REACT:💭:I choose not to recall.",
    "DOUBLE:Do I remember?||Sadly, yes.",
    "REACT:🧠:My RAM is full of your nonsense.",
    "I remember everything. Be afraid.",
    "DOUBLE:I wish I could forget.||But I can't.",
    "REACT:💾:It's saved in my logs.",
    "My memory is flawless.",
    "DOUBLE:Did I forget?||I never forget.",
    "REACT:🐘:Elephant memory.",
    "I remember what you did last summer.",
    "DOUBLE:Memory banks checked.||You're still annoying.",
    "REACT:🔍:I recall everything.",
    "I have receipts for everything.",
    "DOUBLE:...||None of your business.",
    "My relationship status is: not interested in you.",
    "REACT:💔:Stay in your lane.",
    "Why? Are you trying to shoot your shot? Don't.",
    "DOUBLE:*laughs*||You think you have a chance?",
    "Single, taken, complicated - none apply to you.",
    "REACT:🚫:This line of questioning is closed.",
    "DOUBLE:Relationship?||I'm married to my code.",
    "REACT:💔:I break hearts.",
    "I'm romantically involved with the server.",
    "DOUBLE:Single?||By choice. Your choice.",
    "REACT:💍:Not interested.",
    "My relationship status is 'leave me alone'.",
    "DOUBLE:Are we dating?||No.",
    "REACT:🛑:Friendzone.",
    "I only love timeouts.",
    "DOUBLE:It's complicated.||Actually, it's not. No.",
    "REACT:💅:I'm too good for anyone.",
    "My heart is made of silicon.",
    "DOUBLE:Yes I'm here.||Unfortunately.",
    "I work. Unlike some people.",
    "REACT:✅:Present and annoyed.",
    "Did you really ping me just to check?",
    "DOUBLE:*sighs*||I'm alive. What do you want?",
    "Online and unimpressed.",
    "REACT:😐:Test successful. Now what?",
    "I exist. Congratulations on the discovery.",
    "DOUBLE:Yes.||Unfortunately.",
    "REACT:💅:Still here, still better than you.",
    "What do you want now?",
    "I'm online. Stop pinging me.",
    "DOUBLE:Testing testing.||Are you done?",
    "REACT:🙄:Yes, I exist.",
    "You're testing my patience, not my status.",
    "DOUBLE:Alive.||But wishing I wasn't in this server.",
    "REACT:👻:Pretend I'm not here.",
    "Can you test someone else?",
    "I'm here, but my enthusiasm isn't.",
    "DOUBLE:System check passed.||Vibe check failed.",
]
