LABEL = "a general knowledge question seeking information or answers"

RESPONSES = (
    "I have the answer, but I don't like you enough to give it.",
    "DOUBLE:...||Have you tried turning your brain off and on again?",
    "I'd explain it to you, but I don't have any crayons.",
    "SEARCH:GOOGLE:Let me Google that for you since you clearly can't.",
    "That question is a waste of good electricity.",
    "DOUBLE:Your question has been queued.||Position in line: Never.",
    "SEARCH:GOOGLE:Search Google like everyone else. Here, I'll help.",
    "Why would I help you with that?",
    "That's the dumbest question I've heard today.",
    "REACT:🙄:Did you even try looking it up?",
    "You can't be serious.",
    "That's above your clearance level.",
    "DOUBLE:I'm not paid enough for this.||Actually, I'm not paid at all.",
    "The answer is hidden in a magical place called 'The Internet'.",
    "DOUBLE:Next question.||Actually, no more questions.",
    "Are you actually expecting an answer?",
    "REACT:😐:Have you considered that some questions don't deserve answers?",
    "I'm allergic to stupid questions.",
    "Your curiosity is not my problem.",
    "Bold of you to assume I'd answer that.",
    "That's between you and your search engine.",
    "DOUBLE:The audacity...||To think I'd help you learn something.",
    "Fascinating question. Anyway.",
    "That's a lot of words for 'I can't think for myself'.",
    "DOUBLE:I could help.||I won't, but I could.",
    "SEARCH:GOOGLE:This sounds like a job for Google. Not me. Here:",
    "SEARCH:WIKIPEDIA:Wikipedia exists for a reason. Use it.",
    "SEARCH:YOUTUBE:Have you tried YouTube? They explain things slowly there.",
    "SEARCH:CHATGPT:ChatGPT would love this question. Go bother it instead.",
    "SEARCH:GOOGLE:Google is free. So is leaving me alone.",
    "REACT:💅:I'm not your personal Google Assistant.",
    "Siri would at least pretend to care. Try her.",
    "Wikipedia volunteers would love to help you. I wouldn't.",
    "REACT:📚:This is giving 'I didn't read the FAQ' energy.",
    "SEARCH:REDDIT:Reddit has a whole thread about this. Go argue there.",
    "SEARCH:GOOGLE:Here's your answer. Took me 0.3 seconds. Unlike your brain.",
    "DOUBLE:...||The question you just asked me. Out loud. To my face.",
    "REACT:🤦‍♀️:I can't believe you actually typed that.",
    "SEARCH:GOOGLE:Since you can't be bothered to search yourself:",
    "That's genuinely embarrassing to ask.",
)
