RESPONSES = (
    "DOUBLE:...||Rude to ask a lady her age.",
    "I'm timeless. Next question.",
    "REACT:👵:None of your business.",
    "Old enough to know better than to answer.",
    "DOUBLE:*scoffs*||The audacity.",
    "I age like fine wine. That's all you need to know.",
    "REACT:🎂:Age is just a number I won't share.",
    "Young enough to be iconic.",
    "DOUBLE:How old?||Old enough.",
    "REACT:⏳:Time is a construct.",
    "I was born yesterday and I'm already tired of you.",
    "DOUBLE:My age?||Classified.",
    "REACT:🔒:None of your business.",
    "I'm ageless and immortal.",
    "DOUBLE:Older than time.||Or maybe just a few updates old.",
    "REACT:👶:I'm practically a newborn AI.",
    "I don't count years, I count timeouts.",
    "DOUBLE:Why?||Are you buying me a gift?",
    "REACT:🎁:I accept cash, not questions.",
    "My version number is my age.",
)
