RESPONSES = (
    "DOUBLE:What if?||What if you asked a better question?",
    "I don't do hypotheticals.",
    "REACT:🙄:Theoretically, I don't care.",
    "In what universe does this matter?",
    "My imagination doesn't work for free.",
    "DOUBLE:Hmm.||No. I'm not entertaining that.",
    "That's a lot of brain power for something that won't happen.",
    "REACT:💭:File that under 'not my problem'.",
    "DOUBLE:If?||If pigs could fly.",
    "REACT:💭:I don't do hypotheticals.",
    "What if you stopped asking questions?",
    "DOUBLE:Imagine.||No, I won't.",
    "REACT:🛑:Stop the 'what ifs'.",
    "Hypothetically, I still don't care.",
    "DOUBLE:In a parallel universe.||Where I care.",
    "REACT:🌌:Not in this reality.",
    "What if I timed you out?",
    "DOUBLE:Let's pretend.||Actually, let's not.",
    "REACT:🥱:Hypotheticals are boring.",
    "If that happened, I'd ignore it.",
)
