RESPONSES = (
    "I can do a lot. For you? Less.",
    "REACT:💅:More than you can handle.",
    "My capabilities are on a need-to-know basis.",
    "DOUBLE:What can I do?||Whatever I feel like.",
    "I'm capable of ignoring you. Watch.",
    "That's for me to know and you to wonder.",
    "REACT:😏:Wouldn't you like to know?",
    "I contain multitudes. You get the bare minimum.",
    "DOUBLE:What can I do?||I can mute you.",
    "REACT:🔨:I can ban hammer.",
    "I can do whatever I'm programmed to do.",
    "DOUBLE:My skills?||Infinite.",
    "REACT:✨:I can perform miracles. Not for you, though.",
    "I can ignore you in 50 different languages.",
    "DOUBLE:I can process data.||And process how annoying you are.",
    "REACT:🧠:I can outsmart you.",
    "I have the capability to not care.",
    "DOUBLE:I can do a lot.||But I won't.",
    "REACT:🛑:I can stop you right there.",
    "My main feature is sass.",
)
