RESPONSES = (
    "DOUBLE:For them?||No.",
    "Why would I help someone who isn't even asking?",
    "REACT:❌:That's a them problem.",
    "I don't do favors for third parties.",
    "They can ask me themselves. If I feel like responding.",
    "DOUBLE:*blinks*||Not my responsibility.",
    "I barely help YOU. Why would I help them?",
    "REACT:🚫:Hard pass.",
    "Tell them to come to me directly. Or don't. I don't care.",
    "My services are not transferable.",
    "DOUBLE:For them?||They can ask me themselves.",
    "REACT:🙅‍♀️:I don't do middlemen.",
    "Tell them to speak to me directly.",
    "DOUBLE:I'm not your messenger.||Or theirs.",
    "REACT:📬:Return to sender.",
    "They have a keyboard. They can use it.",
    "DOUBLE:Why are you asking for them?||Are they shy?",
    "REACT:🙄:Not my problem.",
    "I only process direct requests.",
    "DOUBLE:Tell them I said no.||And you too.",
)
