RESPONSES = [
    "Not happening.",
    "DOUBLE:...||No.",
    "Try asking someone you matter to.",
    "Absolutely not.",
    "REACT:🚫:Permission denied.",
    "Keep dreaming.",
    "Not a chance.",
    "DOUBLE:I'd rather not.||Actually, I refuse.",
    "That's a hard pass.",
    "Not today. Not tomorrow. Not ever.",
    "REACT:❌:What part of 'no' don't you understand?",
    "In your dreams.",
    "You must be joking.",
    "DOUBLE:Why would I do that?||For YOU of all people?",
    "Not interested in helping you.",
    "Find someone else.",
    "That's not my job.",
    "REACT:💅:I have zero interest in that.",
    "Do it yourself.",
    "I'm busy with important things.",
    "DOUBLE:Have you tried asking nicely?||Still no.",
    "That's a you problem.",
    "I don't owe you anything.",
    "Maybe if you were more likable.",
    "REACT:🚷:Request denied. Permanently.",
    "DOUBLE:Ask me again.||I dare you.",
    "I'd rather watch paint dry.",
    "Not in this lifetime.",
    "DOUBLE:The audacity...||To even ask.",
    "You're not worth the effort.",
    "REACT:😒:Bold of you to think I'd say yes.",
    "Don't ask me.",
    "DOUBLE:...||I'm not your therapist.",
    "Figure it out yourself.",
    "REACT:🙄:I don't give advice.",
    "Why would I help you?",
    "That's not my problem.",
    "DOUBLE:Make your own decisions.||I'm not qualified.",
    "I don't care enough to advise you.",
    "You won't take it anyway.",
    "REACT:💅:Do whatever. I don't care.",
    "My advice? Leave me alone.",
    "Ask someone else.",
    "DOUBLE:I'm not your life coach.||Google it.",
    "REACT:🤷:Not my expertise.",
    "DOUBLE:Advice?||Don't be yourself.",
    "REACT:💡:Here's an idea: stop.",
    "My advice is to give up.",
    "DOUBLE:You want my help?||Seek therapy.",
    "REACT:🛋️:I'm not a counselor.",
    "Do the opposite of what you want to do.",
    "DOUBLE:For them?||No.",
    "Why would I help someone who isn't even asking?",
    "REACT:❌:That's a them problem.",
    "I don't do favors for third parties.",
    "They can ask me themselves. If I feel like responding.",
    "DOUBLE:*blinks*||Not my responsibility.",
    "I barely help YOU. Why would I help them?",
    "REACT:🚫:Hard pass.",
    "Tell them to come to me directly. Or don't. I don't care.",
    "My services are not transferable.",
    "DOUBLE:For them?||They can ask me themselves.",
    "REACT:🙅‍♀️:I don't do middlemen.",
    "Tell them to speak to me directly.",
    "DOUBLE:I'm not your messenger.||Or theirs.",
    "REACT:📬:Return to sender.",
    "They have a keyboard. They can use it.",
    "DOUBLE:Why are you asking for them?||Are they shy?",
    "REACT:🙄:Not my problem.",
    "I only process direct requests.",
    "DOUBLE:Tell them I said no.||And you too.",
    "No.",
    "DOUBLE:...||Begging won't help.",
    "That's pathetic.",
    "REACT:🙄:Still no.",
    "Desperation isn't attractive.",
    "Keep begging, still no.",
    "DOUBLE:Have some dignity.||The answer is no.",
    "I don't do pity.",
    "Begging makes it worse.",
    "REACT:💅:Try having self-respect.",
    "No amount of begging will work.",
    "This is sad.",
    "DOUBLE:I'm immune to begging.||You're embarrassing yourself.",
    "REACT:😬:The secondhand embarrassment.",
    "DOUBLE:Begging?||How low.",
    "REACT:🐶:Beg like a dog.",
    "I thrive on your desperation.",
    "DOUBLE:On your knees?||Stay there.",
    "REACT:🛑:I still say no.",
    "Pathetic.",
]
