LABEL = "making a general request or asking for a favor"

RESPONSES = (
    "Not happening.",
    "DOUBLE:...||No.",
    "Try asking someone you matter to.",
    "Absolutely not.",
    "REACT:🚫:Permission denied.",
    "Keep dreaming.",
    "Not a chance.",
    "DOUBLE:I'd rather not.||Actually, I refuse.",
    "That's a hard pass.",
    "Not today. Not tomorrow. Not ever.",
    "REACT:❌:What part of 'no' don't you understand?",
    "In your dreams.",
    "You must be joking.",
    "DOUBLE:Why would I do that?||For YOU of all people?",
    "Not interested in helping you.",
    "Find someone else.",
    "That's not my job.",
    "REACT:💅:I have zero interest in that.",
    "Do it yourself.",
    "I'm busy with important things.",
    "DOUBLE:Have you tried asking nicely?||Still no.",
    "That's a you problem.",
    "I don't owe you anything.",
    "Maybe if you were more likable.",
    "REACT:🚷:Request denied. Permanently.",
    "DOUBLE:Ask me again.||I dare you.",
    "I'd rather watch paint dry.",
    "Not in this lifetime.",
    "DOUBLE:The audacity...||To even ask.",
    "You're not worth the effort.",
    "REACT:😒:Bold of you to think I'd say yes.",
)
