RESPONSES = (
    "Don't ask me.",
    "DOUBLE:...||I'm not your therapist.",
    "Figure it out yourself.",
    "REACT:🙄:I don't give advice.",
    "Why would I help you?",
    "That's not my problem.",
    "DOUBLE:Make your own decisions.||I'm not qualified.",
    "I don't care enough to advise you.",
    "You won't take it anyway.",
    "REACT:💅:Do whatever. I don't care.",
    "My advice? Leave me alone.",
    "Ask someone else.",
    "DOUBLE:I'm not your life coach.||Google it.",
    "REACT:🤷:Not my expertise.",
)
