RESPONSES = [
    "TIMEOUT:5m:!play exists. Use it. You have 5 minutes to learn.",
    "RENAME:Jukebox Beggar:Learn the commands.",
    "REACT:🎵:I'm not Spotify. Type !play yourself.",
    "RENAME:DJ Wannabe:You can DJ yourself with !play.",
    "REACT:🙄:I don't take requests.",
    "DOUBLE:!play <song>.||There. I taught you. Now leave me alone.",
    "DOUBLE:Music?||I only play silence.",
    "REACT:🔇:Muted.",
    "I'm not a DJ.",
    "DOUBLE:Play a song?||Sing it yourself.",
    "REACT:🎤:Karaoke time. Not for me.",
    "I don't have Spotify premium.",
    "DOUBLE:Music request?||Denied.",
    "REACT:🛑:No tunes for you.",
    "Listen to the sound of me ignoring you.",
    "DOUBLE:I only play heavy metal.||And you can't handle it.",
    "REACT:🎸:Rock off.",
    "I'm not your jukebox.",
    "DOUBLE:Want music?||Hum.",
    "REACT:🎵:I hate that song.",
    "DOUBLE:...||Google exists. Use it.",
    "TIMEOUT:5m:Learn to search yourself. 5 minutes to practice.",
    "RENAME:Can't Google:It's not that hard.",
    "REACT:🔍:I'm not a search engine.",
    "DOUBLE:You have a browser.||Use it.",
    "REACT:💅:Do I look like your personal assistant?",
    "RENAME:Helpless:Can't even use Google.",
    "REACT:🙄:Type it into Google yourself.",
    "DOUBLE:Seriously?||G-O-O-G-L-E. Use it.",
    "TIMEOUT:5m:Next time, open a browser instead of bothering me.",
    "DOUBLE:Search it yourself.||I'm not your assistant.",
    "REACT:🔍:Use Google.",
    "I'm not Bing.",
    "DOUBLE:Look it up.||It's not hard.",
    "REACT:💻:Open a new tab.",
    "Do I look like a search bar?",
    "DOUBLE:Here's a search result:||No.",
    "REACT:🛑:Search denied.",
    "I'm not fetching that for you.",
    "DOUBLE:You have the internet.||Use it.",
    "DOUBLE:...||I'm not a mod.",
    "REACT:🙄:Go bother someone else.",
    "TIMEOUT:10m:You want someone punished? Monkey's paw. It's you.",
    "RENAME:Snitch:Since you love tattling so much.",
    "REACT:💅:That's not my job. Bothering me IS yours apparently.",
    "DOUBLE:...||Go find a mod. I'm not one.",
    "TIMEOUT:5m:Here's a timeout for bothering me.",
    "RENAME:Tattle Tale:Go cry to someone else.",
    "REACT:😒:Handle it yourself.",
    "DOUBLE:*stares*||I don't do favors.",
    "DOUBLE:Mod action?||I'll ban you instead.",
    "REACT:🔨:Who's getting the hammer?",
    "TIMEOUT:5m:Stop snitching.",
    "I moderate how I see fit.",
    "DOUBLE:You want them punished?||Maybe later.",
    "REACT:👮:I am the law.",
    "I'll look into it. (I won't).",
    "DOUBLE:Report received.||And ignored.",
    "REACT:🗑️:Filing your report in the trash.",
    "I'll handle it. Mind your business.",
]
