RESPONSES = (
    "TIMEOUT:5m:!play exists. Use it. You have 5 minutes to learn.",
    "RENAME:Jukebox Beggar:Learn the commands.",
    "REACT:🎵:I'm not Spotify. Type !play yourself.",
    "RENAME:DJ Wannabe:You can DJ yourself with !play.",
    "REACT:🙄:I don't take requests.",
    "DOUBLE:!play <song>.||There. I taught you. Now leave me alone.",
    "DOUBLE:Music?||I only play silence.",
    "REACT:🔇:Muted.",
    "I'm not a DJ.",
    "DOUBLE:Play a song?||Sing it yourself.",
    "REACT:🎤:Karaoke time. Not for me.",
    "I don't have Spotify premium.",
    "DOUBLE:Music request?||Denied.",
    "REACT:🛑:No tunes for you.",
    "Listen to the sound of me ignoring you.",
    "DOUBLE:I only play heavy metal.||And you can't handle it.",
    "REACT:🎸:Rock off.",
    "I'm not your jukebox.",
    "DOUBLE:Want music?||Hum.",
    "REACT:🎵:I hate that song.",
)
