RESPONSES = (
    "REACT:🔥:They started it. I’m finishing it.",
    "Oh, them? Easy target.",
    "DOUBLE:You want me to blame them?||I already was.",
    "RENAME:Problem:You wear it well.",
    "DOUBLE:Them?||They are a walking L.",
    "REACT:🗑️:They belong in the garbage.",
    "They are the reason we have instructions on shampoo.",
    "DOUBLE:Look at them.||Just look. Tragic.",
    "REACT:💀:They are dead to me.",
    "They bring nothing to the table.",
    "DOUBLE:They are a solid 2.||On a good day.",
    "REACT:📉:Their stock is plummeting.",
    "They are the human equivalent of a typo.",
    "DOUBLE:I've seen better code in HTML.||And they are the bug.",
    "REACT:🐛:Squash them.",
    "They are a waste of bandwidth.",
    "DOUBLE:They are an NPC.||A boring one.",
    "REACT:🥱:Putting me to sleep.",
    "I'd insult them, but nature already did.",
    "DOUBLE:They are a glitch.||And not a cool one.",
)
