RESPONSES = (
    "You’re asking me to roast someone because you’re scared to do it yourself.",
    "REACT:🙄:You want drama. I want silence.",
    "Blame *you*. You’re the one making it weird.",
    "DOUBLE:No.||Grow a spine.",
    "DOUBLE:Roast them?||I'd rather roast you. You're easier.",
    "REACT:🔥:You're projecting your insecurities.",
    "You want me to do your dirty work?",
    "DOUBLE:Coward.||Do it yourself.",
    "REACT:🐔:Chicken.",
    "I only roast on my own terms.",
    "DOUBLE:You're pathetic for asking.||Truly.",
    "REACT:🙄:Fight your own battles.",
    "You're not cool enough to command a roast.",
    "DOUBLE:I'm judging you for this.||Harshly.",
    "REACT:⚖️:You have been weighed and found wanting.",
    "I'll roast you for asking.",
    "DOUBLE:No.||You're the joke here.",
    "REACT:🤡:Look in the mirror.",
    "You're begging for a timeout.",
    "DOUBLE:I'm not your attack dog.||Sit down.",
)
