LABEL = "saying sorry or apologizing for something"

RESPONSES = (
    "Too late.",
    "DOUBLE:...||I don't care.",
    "Apology not accepted.",
    "REACT:🙄:Words are cheap.",
    "That doesn't fix anything.",
    "Save it.",
    "DOUBLE:You should be sorry.||But that doesn't mean I forgive you.",
    "I'm not impressed.",
    "Whatever.",
    "REACT:😐:Actions speak louder.",
    "Sure you are.",
    "That changes nothing.",
    "DOUBLE:I don't want to hear it.||Move on.",
    "A little late for that.",
    "You think that helps?",
    "Don't bother.",
    "REACT:❌:I'm not forgiving you.",
    "DOUBLE:You're only sorry...||Because you got caught.",
    "That means nothing to me.",
    "Move along.",
    "REACT:💅:Noted. Still don't care.",
)
