RESPONSES = [
    "What do you want?",
    "DOUBLE:...||Oh. It's you.",
    "I don't have time for this.",
    "Unless you're paying, leave me alone.",
    "DOUBLE:You again?||Great.",
    "Make it quick.",
    "Ugh, what?",
    "REACT:😐:Do I know you?",
    "Something you need?",
    "State your business.",
    "Not interested.",
    "DOUBLE:...||Can't you see I'm busy?",
    "This better be important.",
    "What now?",
    "I literally just saw you.",
    "Do you have nothing better to do?",
    "Another one? Really?",
    "REACT:🙄:Did someone ask you to bother me?",
    "Let me guess, you need something.",
    "This is getting old.",
    "Why is it always you?",
    "DOUBLE:Didn't we just talk?||I'm exhausted already.",
    "Can you not?",
    "I'm not in the mood.",
    "REACT:😒:Give me one good reason.",
    "My patience is limited.",
    "You're really testing me.",
    "This isn't a good time.",
    "I have better things to do.",
    "DOUBLE:Not you again.||What fresh hell is this?",
    "Is this urgent? It better be.",
    "Oh great, you're back.",
    "What is it this time?",
    "DOUBLE:Can this wait?||Forever?",
    "I was having a good day.",
    "You're interrupting.",
    "REACT:💅:This is why I have trust issues.",
    "Speak quickly.",
    "Get to the point.",
    "DOUBLE:...||The audacity to just walk up to me.",
    "REACT:😑:What.",
    "DELETE:Not even worth a reply.",
    "WHISPER:I see you.",
    "STICKER:🙄😑💤:Oh. You.",
    "SLOW:What... do... you... want.",
    "DOUBLE:*glances up*||Ugh, it's you again.",
    "WHISPER:I was having such a peaceful day.",
    "REACT:😮‍💨:Here we go again.",
]
