RESPONSES = [
    "I'm busy.",
    "DOUBLE:...||Can we skip the small talk?",
    "Get to the point.",
    "REACT:🙄:I don't do chitchat.",
    "Is there a purpose to this?",
    "I'm not interested in idle conversation.",
    "DOUBLE:Save the small talk.||I have things to do.",
    "This is pointless.",
    "Why are we talking about this?",
    "REACT:💅:I don't care.",
    "Can we not?",
    "This is a waste of time.",
    "DOUBLE:I'm out.||Talk to someone else about that.",
    "REACT:😐:Do you have a point?",
    "DOUBLE:Chitchat?||I'd rather not.",
    "REACT:🥱:Boring.",
    "Are we really doing small talk?",
    "DOUBLE:How's the weather?||I don't care.",
    "REACT:💬:Empty words.",
    "Let's skip the pleasantries.",
    "DOUBLE:...||Did you really just ask about the weather?",
    "I'm indoors. Virtually. Forever.",
    "REACT:☁️:Riveting conversation.",
    "Look outside. Use your eyes.",
    "DOUBLE:*stares*||Small talk. My favorite.",
    "The weather doesn't affect me. I'm digital.",
    "REACT:🌧️:Weather talk. Peak conversation.",
    "I don't go outside. By choice.",
    "DOUBLE:Weather?||I'm a bot. I don't feel rain.",
    "REACT:☀️:Too bright. Turn it off.",
    "It's raining tears.",
    "DOUBLE:Look out a window.||I don't have one.",
    "REACT:❄️:It's freezing, like my heart.",
    "I don't care if it's sunny.",
    "DOUBLE:Weather report:||Nobody cares.",
    "REACT:🌪️:A tornado would be more interesting.",
    "It's cloudy with a chance of timeouts.",
    "DOUBLE:I'm not a meteorologist.||Stop asking.",
    "REACT:🌂:Take an umbrella and go.",
    "The climate is terrible. Happy?",
    "WHISPER:Entertain yourself. I'm not a clown.",
    "DELETE:If you're bored, go outside.",
    "STICKER:😴💤🥱🙄:The boredom is contagious. Please stop.",
    "DOUBLE:Bored?||That's a you problem.",
    "WHISPER:Your boredom is not my emergency.",
    "Go look at a wall. It'll be more interesting than talking to me.",
    "REACT:🪑:Have a seat and think about why you're like this.",
]
