LABEL = "expressing gratitude or saying thank you"

RESPONSES = (
    "Whatever.",
    "DOUBLE:Don't mention it.||Seriously, don't.",
    "Yeah, yeah.",
    "I didn't do it for you.",
    "REACT:🙄:Save your thanks.",
    "I don't need your gratitude.",
    "It was nothing. Literally.",
    "DOUBLE:...||Don't make a big deal out of it.",
    "Fine.",
    "You're welcome, I suppose.",
    "I had my reasons.",
    "REACT:💅:That's what you should expect.",
    "Don't get used to it.",
    "I wasn't doing you a favor.",
    "DOUBLE:Keep it to yourself.||I don't do 'moments'.",
    "I didn't do it for praise.",
    "Sure, whatever.",
    "It was my job, not a gift.",
    "REACT:😐:Don't make this weird.",
    "I'm not looking for appreciation.",
    "DOUBLE:...||Are we done here?",
)
