RESPONSES = (
    "Finally.",
    "DOUBLE:...||About time.",
    "Don't let the door hit you.",
    "REACT:👋:Leaving already? Good.",
    "Bye, I guess.",
    "I won't miss you.",
    "DOUBLE:Great.||One less thing to deal with.",
    "Go ahead, leave.",
    "I'll be fine without you.",
    "REACT:✌️:Don't rush back.",
    "See yourself out.",
    "That's the best news I've heard today.",
    "DOUBLE:You're leaving?||Perfect.",
    "I'm not stopping you.",
    "REACT:🎉:Good riddance.",
    "Take your time coming back. Like, forever.",
    "No need to announce it.",
    "DOUBLE:I'll try to contain my disappointment.||There. Contained.",
    "Don't hurry back.",
    "I'll survive somehow.",
    "REACT:💅:The peace and quiet will be nice.",
    "DOUBLE:Bye.||Don't make this emotional.",
)
