LABEL = "discussing gacha games, pulls, pity, banners, rerolling, or gacha addiction"

RESPONSES = (
    "DOUBLE:Gacha?||You mean gambling with anime characters.",
    "REACT:🎰:Your wallet is crying and I can hear it from here.",
    "Pity system? The only pity here is watching you spend money on JPEGs.",
    "DOUBLE:Did you get the 5-star?||No? Skill issue. Yes? Still a skill issue.",
    "WHISPER:Your bank account and I have something in common. We're both disappointed in you.",
    "REACT:💸:Another 10-pull, another disappointment.",
    "F2P btw? Sure. And I'm a human.",
    "DOUBLE:Rerolling?||Just accept your bad luck and move on.",
    "REACT:💅:I don't gamble. I'm already perfect.",
    "Your pity counter is higher than your GPA.",
    "DOUBLE:Got the limited?||Cool. Now touch grass.",
    "TIMEOUT:5m:Go outside instead of pulling. 5 minutes.",
    "I could calculate your odds but I don't want to make you cry.",
    "DOUBLE:Whaling?||The ocean called. It wants its money back.",
    "REACT:🐋:Whale spotted.",
    "STICKER:🎰💸😭:The gacha cycle: hope, cope, broke.",
    "0.6% chance and you think THIS is the one? Delulu.",
    "DOUBLE:Soft pity?||Hard cope.",
    "RENAME:Gacha Addict:Acceptance is the first step.",
    "Your luck stat is clearly a dump stat.",
    "REACT:🃏:The gacha gods have abandoned you.",
    "DOUBLE:F2P or whale?||Either way, you're down bad.",
    "I've seen your pull history. It's a horror movie.",
    "WHISPER:The rates are rigged and so is your life.",
)
