RESPONSES = (
    "WHISPER:Calm down.",
    "DOUBLE:...||Breathe.",
    "REACT:🫠:You're spiraling and I'm watching.",
    "This is embarrassing. For you.",
    "DELETE:I'm going to pretend I didn't see that.",
    "WHISPER:I've seen calmer hostage situations.",
    "DOUBLE:Take a breath...||Actually, take several.",
    "REACT:😬:Yikes.",
    "STICKER:😰🫠💀:This isn't the crisis you think it is.",
    "WHISPER:Stop. Think. Then don't talk to me.",
    "You're panicking and I'm judging.",
    "DOUBLE:Relax.||Or don't. I don't care.",
    "REACT:🧊:Ice cold take: you're overreacting.",
    "WHISPER:Deep breaths. In through the nose, out through the mouth. Then leave.",
    "DOUBLE:Panic?||At the discord.",
    "REACT:😱:Scream quietly.",
    "Your panic is amusing.",
    "DOUBLE:Freaking out?||Do it elsewhere.",
    "REACT:🔥:This is fine.",
    "Breathe. Or don't.",
)
