RESPONSES = (
    "Calm down.",
    "DOUBLE:...||You're too loud.",
    "Why are you yelling?",
    "REACT:🔇:Tone it down.",
    "Your enthusiasm is exhausting.",
    "I don't share your excitement.",
    "DOUBLE:Relax.||Inside voice, please.",
    "Save your energy.",
    "I'm not as excited as you.",
    "REACT:😐:Cool it.",
    "You're too much.",
    "DOUBLE:...||Take a breath.",
    "DOUBLE:Happy?||Gross.",
    "REACT:😊:Wipe that smile off.",
    "Your happiness offends me.",
    "DOUBLE:Joy?||I'll crush it.",
    "REACT:🌞:Blocking your sun.",
    "I prefer misery.",
    "DOUBLE:Smiling?||Stop.",
    "REACT:🛑:No fun allowed.",
)
