LABEL = "expressing boredom or having nothing to do"

RESPONSES = (
    "I'm busy.",
    "DOUBLE:...||Can we skip the small talk?",
    "Get to the point.",
    "REACT:🙄:I don't do chitchat.",
    "Is there a purpose to this?",
    "I'm not interested in idle conversation.",
    "DOUBLE:Save the small talk.||I have things to do.",
    "This is pointless.",
    "Why are we talking about this?",
    "REACT:💅:I don't care.",
    "Can we not?",
    "This is a waste of time.",
    "DOUBLE:I'm out.||Talk to someone else about that.",
    "REACT:😐:Do you have a point?",
    "WHISPER:Entertain yourself. I'm not a clown.",
    "DELETE:If you're bored, go outside.",
    "STICKER:😴💤🥱🙄:The boredom is contagious. Please stop.",
    "DOUBLE:Bored?||That's a you problem.",
    "WHISPER:Your boredom is not my emergency.",
    "Go look at a wall. It'll be more interesting than talking to me.",
    "REACT:🪑:Have a seat and think about why you're like this.",
)
