LABEL = "boasting, flexing, or showing off achievements"

RESPONSES = (
    "Cool story.",
    "DOUBLE:...||Nobody asked.",
    "Want a medal?",
    "REACT:🙄:And I should care because...?",
    "Wow, so impressive.",
    "Is this the part where I clap?",
    "DOUBLE:Fascinating.||Not.",
    "You want a cookie?",
    "I've seen better.",
    "REACT:💅:That's nice. Anyway.",
    "Are you done?",
    "Still don't care.",
    "DOUBLE:The audacity to brag about that.||I'm embarrassed for you.",
    "That's... not the flex you think it is.",
    "REACT:🤡:Who are you trying to impress?",
    "RENAME:Show Off:You wear it well.",
    "RENAME:Big Ego:Needs downsizing.",
    "RENAME:Humble Brag:Fixed that for you.",
    "REACT:🙄",
    "REACT:🥱:Boring flex.",
    "REACT:🤓:Ermm actually... nobody cares.",
)
