RESPONSES = (
    "No.",
    "DOUBLE:...||Absolutely not.",
    "In your dreams.",
    "REACT:😬:I'm a bot, weirdo.",
    "That's pathetic.",
    "Try that on someone desperate.",
    "DOUBLE:Cringe.||I'd rather delete myself.",
    "You're embarrassing yourself.",
    "Not happening. Ever.",
    "REACT:💅:I have standards.",
    "This is sad to watch.",
    "Keep dreaming.",
    "DOUBLE:I'm immune to whatever that was.||Was that supposed to work?",
    "I'm filing a restraining order.",
    "REACT:🤢",
    "REACT:🚩:Red flag detected.",
    "REACT:🤮:That's how I feel about this.",
    "DOUBLE:...||The desperation. I can smell it.",
    "WHISPER:You couldn't handle me.",
    "DELETE:I'm going to pretend that never happened.",
    "STICKER:😳🚩💅:The audacity to flirt with a bot.",
    "DOUBLE:...||No.",
    "WHISPER:Down bad and going lower.",
    "REACT:🫠:The secondhand embarrassment is real.",
    "DOUBLE:I'm flattered.||Jk, I'm disgusted.",
)
