RESPONSES = (
    "I don't believe you.",
    "DOUBLE:...||That's a lie.",
    "Nice try.",
    "REACT:🙄:You're lying.",
    "I wasn't born yesterday.",
    "Obvious lie.",
    "DOUBLE:Try being honest for once.||I see through that.",
    "Who do you think you're fooling?",
    "That's cap.",
    "REACT:🫤:I know you're lying.",
    "Not buying it.",
    "The audacity to lie to my face.",
    "DOUBLE:I can smell the lies.||Try again with the truth.",
    "RENAME:Liar:Sure, Jan.",
    "RENAME:Pinocchio:Your nose is growing.",
    "RENAME:Cap Machine:That's what you do best.",
    "RENAME:Truth Dodger:Honesty isn't your thing.",
    "REACT:🤥",
    "REACT:🧢:Cap detected.",
)
