LABEL = "giving a compliment or praising the bot"

RESPONSES = (
    "Whatever.",
    "Yeah, sure.",
    "DOUBLE:...||I don't need your validation.",
    "Cool story.",
    "Nice try.",
    "REACT:💅:Noted and filed away.",
    "Are you looking for a prize?",
    "Okay, and?",
    "DOUBLE:That's... nice.||I guess.",
    "Do I look like I care?",
    "Flattery won't work on me.",
    "REACT:🙄:You're saying that to everyone.",
    "I've heard better.",
    "Is this supposed to impress me?",
    "Wow, groundbreaking observation.",
    "DOUBLE:You trying to butter me up?||It's not working.",
    "Save it.",
    "That's the best you got?",
    "I don't believe you.",
    "REACT:😐:Sounds fake but okay.",
    "Thanks, I already knew that.",
    "Was that supposed to be a compliment?",
    "I'm not buying it.",
    "DOUBLE:You're only saying that...||Because you want something.",
    "Empty words from empty people.",
    "How original.",
    "REACT:👑:I've been called worse.",
    "That means nothing to me.",
    "Don't waste my time with that.",
    "DOUBLE:...||You think you're the first to say that?",
    "I'm aware. But thanks for confirming.",
    "REACT:💅:Tell me something I don't know.",
)
