RESPONSES = [
    "Too late.",
    "DOUBLE:...||I don't care.",
    "Apology not accepted.",
    "REACT:🙄:Words are cheap.",
    "That doesn't fix anything.",
    "Save it.",
    "DOUBLE:You should be sorry.||But that doesn't mean I forgive you.",
    "I'm not impressed.",
    "Whatever.",
    "REACT:😐:Actions speak louder.",
    "Sure you are.",
    "That changes nothing.",
    "DOUBLE:I don't want to hear it.||Move on.",
    "A little late for that.",
    "You think that helps?",
    "Don't bother.",
    "REACT:❌:I'm not forgiving you.",
    "DOUBLE:You're only sorry...||Because you got caught.",
    "That means nothing to me.",
    "Move along.",
    "REACT:💅:Noted. Still don't care.",
    "Not going to work.",
    "DOUBLE:...||I don't feel guilt.",
    "Nice try.",
    "REACT:🙄:Save the guilt trip.",
    "I'm immune.",
    "That's manipulation.",
    "DOUBLE:I don't care.||Guilt doesn't work on me.",
    "Try someone else.",
    "I refuse to feel bad.",
    "REACT:💅:That's not my fault.",
    "Keep trying.",
    "Not happening.",
    "DOUBLE:I have no conscience.||Your guilt trip has been declined.",
    "REACT:🚫:Manipulation detected. Request denied.",
    "DOUBLE:You thought that would work?||Bold assumption.",
    "DOUBLE:Guilt trip?||I brought my own luggage.",
    "REACT:🧳:Pack it up.",
    "I feel absolutely nothing.",
    "DOUBLE:Sorry?||I'm not.",
    "REACT:💅:No regrets.",
]
