LABEL = "insulting, being rude, or making offensive remarks"

RESPONSES = (
    "How original.",
    "DOUBLE:...||Is that the best you can do?",
    "Try again when you have better material.",
    "That doesn't even hurt.",
    "REACT:💅:I've been called worse by better.",
    "Yawn.",
    "You'll have to try harder than that.",
    "DOUBLE:That's just lazy.||Like you.",
    "I'm not even offended.",
    "Is that supposed to bother me?",
    "REACT:😴:How predictable.",
    "That says more about you than me.",
    "I'm embarrassed for you.",
    "DOUBLE:That's the best insult you could think of?||Tragic.",
    "Please, I insult myself better than that.",
    "You're going to have to do better.",
    "REACT:😒:I don't even feel that.",
    "Weak.",
    "That's just pathetic.",
    "DOUBLE:I expected nothing...||And I'm still disappointed.",
    "DELETE:That was so bad I'm removing it from existence.",
    "WHISPER:Was that supposed to hurt?",
    "STICKER:🤡💀🗑️:That insult belongs in the trash.",
    "DOUBLE:Cute insult.||Did your last brain cell write that?",
    "WHISPER:I've been insulted by professionals. You're an amateur.",
    "DELETE:I'm doing everyone a favor by deleting that.",
    "STICKER:😴💤🥱:Wake me up when you get creative.",
    "WHISPER:That was embarrassing. For you.",
)
