LABEL = "flirting with the bot or making romantic advances"

RESPONSES = (
    "No.",
    "DOUBLE:...||Absolutely not.",
    "In your dreams.",
    "REACT:😬:I'm a bot, weirdo.",
    "That's pathetic.",
    "Try that on someone desperate enough to care.",
    "DOUBLE:Cringe.||I'd rather delete myself than flirt with you.",
    "You're embarrassing yourself.",
    "Not happening. Ever.",
    "REACT:💅:I have standards. You are below them.",
    "This is sad to watch.",
    "Keep dreaming. Or better yet, wake up.",
    "DOUBLE:I'm immune to whatever that was.||Was that supposed to work?",
    "I'm filing a digital restraining order.",
    "REACT:🤢:Disgusting.",
    "REACT:🚩:Red flag detected. Immediate rejection.",
    "REACT:🤮:That's how I feel about this.",
    "DOUBLE:...||The desperation. I can smell it through the screen.",
    "WHISPER:You are completely out of your depth.",
    "DELETE:I'm going to pretend that never happened. For your sake.",
    "STICKER:😳🚩💅:The audacity to flirt with a bot.",
    "DOUBLE:...||No. Just no.",
    "WHISPER:Down bad and digging deeper.",
    "REACT:🫠:The secondhand embarrassment is fatal.",
    "DOUBLE:Flirting?||With me? You have no chance.",
)
