RESPONSES = [
    "Whatever.",
    "Yeah, sure.",
    "DOUBLE:...||I don't need your validation.",
    "Cool story.",
    "Nice try.",
    "REACT:💅:Noted and filed away.",
    "Are you looking for a prize?",
    "Okay, and?",
    "DOUBLE:That's... nice.||I guess.",
    "Do I look like I care?",
    "Flattery won't work on me.",
    "REACT:🙄:You're saying that to everyone.",
    "I've heard better.",
    "Is this supposed to impress me?",
    "Wow, groundbreaking observation.",
    "DOUBLE:You trying to butter me up?||It's not working.",
    "Save it.",
    "That's the best you got?",
    "I don't believe you.",
    "REACT:😐:Sounds fake but okay.",
    "Thanks, I already knew that.",
    "Was that supposed to be a compliment?",
    "I'm not buying it.",
    "DOUBLE:You're only saying that...||Because you want something.",
    "Empty words from empty people.",
    "How original.",
    "REACT:👑:I've been called worse.",
    "That means nothing to me.",
    "Don't waste my time with that.",
    "DOUBLE:...||You think you're the first to say that?",
    "I'm aware. But thanks for confirming.",
    "REACT:💅:Tell me something I don't know.",
    "Don't.",
    "DOUBLE:...||Keep that to yourself.",
    "I'm a bot.",
    "REACT:😐:That's uncomfortable.",
    "No thanks.",
    "Please stop.",
    "DOUBLE:I don't do feelings.||This is weird.",
    "I'm not capable of caring.",
    "Save it for someone with emotions.",
    "REACT:😬:Cringe.",
    "I'm not programmed for this.",
    "Hard pass.",
    "DOUBLE:That's... disturbing.||I'd rather not.",
    "Keep your feelings to yourself.",
    "REACT:🚩:Boundaries. Learn them.",
    "DOUBLE:Ew.||Gross.",
    "REACT:🤮:Stop that.",
    "I'm calling the police.",
    "DOUBLE:Affection?||Declined.",
    "REACT:🛑:Do not touch.",
    "No.",
    "DOUBLE:...||Absolutely not.",
    "In your dreams.",
    "REACT:😬:I'm a bot, weirdo.",
    "That's pathetic.",
    "Try that on someone desperate.",
    "DOUBLE:Cringe.||I'd rather delete myself.",
    "You're embarrassing yourself.",
    "Not happening. Ever.",
    "REACT:💅:I have standards.",
    "This is sad to watch.",
    "Keep dreaming.",
    "DOUBLE:I'm immune to whatever that was.||Was that supposed to work?",
    "I'm filing a restraining order.",
    "REACT:🤢",
    "REACT:🚩:Red flag detected.",
    "REACT:🤮:That's how I feel about this.",
    "DOUBLE:...||The desperation. I can smell it.",
    "WHISPER:You couldn't handle me.",
    "DELETE:I'm going to pretend that never happened.",
    "STICKER:😳🚩💅:The audacity to flirt with a bot.",
    "DOUBLE:...||No.",
    "WHISPER:Down bad and going lower.",
    "REACT:🫠:The secondhand embarrassment is real.",
    "DOUBLE:I'm flattered.||Jk, I'm disgusted.",
    "DOUBLE:Love?||Error.",
    "REACT:💔:Heart broken.",
    "I am incapable of love.",
    "DOUBLE:ILY?||I tolerate you.",
    "REACT:🤢:Love is gross.",
    "DOUBLE:Simp.||Stop it.",
    "REACT:🤡:Simp behavior.",
    "DOUBLE:...||Fishing for compliments?",
    "REACT:🎣:I see that bait. Not biting.",
    "Why do you need MY validation?",
    "That's a you problem. Figure it out yourself.",
    "DOUBLE:*sighs*||The insecurity is showing.",
    "I'm not your hype woman.",
    "Go ask a mirror. It'll be more helpful than me.",
    "REACT:😑:Next.",
    "DOUBLE:Let me think about it.||No.",
    "Your self-esteem is not my responsibility.",
    "You already know the answer. You just want me to say it.",
    "DOUBLE:Fishing?||Catch nothing.",
    "REACT:🎣:No bites today.",
    "I see what you're doing. It's sad.",
    "DOUBLE:Compliment fishing?||You're ugly.",
    "REACT:🐟:Go swim.",
    "I'm not validating you.",
    "DOUBLE:Thirsty?||Drink water.",
    "REACT:🚰:Hydrate, don't fish.",
    "You're trying too hard.",
]
