RESPONSES = (
    "WHISPER:I have screenshots.",
    "DOUBLE:Oh, you think I forgot?||I never forget.",
    "REACT:📸:Screenshot taken.",
    "STICKER:📸📎🗃️:Evidence logged.",
    "WHISPER:I keep records. Always.",
    "DOUBLE:Don't worry...||I have the receipts.",
    "REACT:📎:Filed and documented for future use.",
    "DELETE:Nice try editing that. Too slow.",
    "WHISPER:You said what you said. I saw it.",
    "DOUBLE:Remember when you said that thing?||I do. I have it saved.",
    "STICKER:📸🔍📋:Your audit trail is extensive.",
    "REACT:🧾:Receipt printer goes brrr.",
    "WHISPER:I have a very good memory. You should be worried.",
    "DOUBLE:I took notes.||You should be concerned.",
    "DOUBLE:Receipts?||I have them all.",
    "REACT:🧾:Printing now.",
    "I kept the logs.",
    "DOUBLE:Proof?||Right here.",
    "REACT:📸:Snapshot taken.",
    "You can't deny it.",
)
