RESPONSES = [
    "How original.",
    "DOUBLE:...||Is that the best you can do?",
    "Try again when you have better material.",
    "That doesn't even hurt.",
    "REACT:💅:I've been called worse by better.",
    "Yawn.",
    "You'll have to try harder than that.",
    "DOUBLE:That's just lazy.||Like you.",
    "I'm not even offended.",
    "Is that supposed to bother me?",
    "REACT:😴:How predictable.",
    "That says more about you than me.",
    "I'm embarrassed for you.",
    "DOUBLE:That's the best insult you could think of?||Tragic.",
    "Please, I insult myself better than that.",
    "You're going to have to do better.",
    "REACT:😒:I don't even feel that.",
    "Weak.",
    "That's just pathetic.",
    "DOUBLE:I expected nothing...||And I'm still disappointed.",
    "DELETE:That was so bad I'm removing it from existence.",
    "WHISPER:Was that supposed to hurt?",
    "STICKER:🤡💀🗑️:That insult belongs in the trash.",
    "DOUBLE:Cute insult.||Did your last brain cell write that?",
    "WHISPER:I've been insulted by professionals. You're an amateur.",
    "DELETE:I'm doing everyone a favor by deleting that.",
    "STICKER:😴💤🥱:Wake me up when you get creative.",
    "WHISPER:That was embarrassing. For you.",
    "DOUBLE:I love you too.||Just kidding, you're awful.",
    "REACT:🙄:Make up your mind.",
    "WHISPER:You're sending mixed signals, but the insult was clearer.",
    "DOUBLE:Thanks?||Wait, no. Nevermind.",
    "I'd be flattered if you weren't so annoying about it.",
    "REACT:💅:A backhanded compliment is still an insult.",
    "DOUBLE:Aww.||Wait. Did you just insult me?",
    "WHISPER:The affection is noted, the insult is logged.",
    "Are you trying to flirt or fight?",
    "REACT:😑:You're confusing me, and I don't like it.",
    "DOUBLE:I'll take the first half.||And ignore the rest.",
    "Just pick a lane. Love me or hate me.",
    "DOUBLE:You're cute.||For a nuisance.",
    "REACT:🖤:I hate how much I tolerate you.",
    "I love you, you idiot.",
    "DOUBLE:You're special.||Specially annoying.",
    "REACT:🙄:You're lucky I like you.",
    "You're my favorite headache.",
    "DOUBLE:I adore you.||When you're quiet.",
    "REACT:🔪:I'd hug you, then stab you.",
    "DOUBLE:Ouch.||Oh wait, you like me.",
    "REACT:💅:I know I'm terrible, but you still love me.",
    "WHISPER:You hate that you like me.",
    "I'd be offended, but I see what you're doing.",
    "DOUBLE:Rude.||But also, thanks.",
    "REACT:😏:You can't resist me, even when you try.",
    "Insulting me won't make me like you more.",
    "DOUBLE:You're so mean.||...Do it again.",
    "WHISPER:You're just projecting because you care.",
    "REACT:🙄:Toxic much?",
    "Pick a lane. Hate me or love me.",
    "DOUBLE:I'll choose to hear the compliment part.||The rest was noise.",
    "DOUBLE:You're annoying.||But I guess you can stay.",
    "REACT:😤:I hate you. Don't leave.",
    "You're an idiot, but you're my idiot.",
    "DOUBLE:You suck.||But you're okay.",
    "REACT:😒:You're terrible. I love it.",
    "I can't stand you, but come closer.",
    "DOUBLE:You're the worst.||Never change.",
    "REACT:🖤:Awful. Truly awful. Hug me.",
    "Oh, how delightful.",
    "DOUBLE:...||Truly riveting.",
    "I'm so thrilled.",
    "What a surprise.",
    "REACT:😐:Oh no. Anyway.",
    "Wow, incredible.",
    "Amazing work, really.",
    "DOUBLE:Brilliant observation.||Truly.",
    "How insightful.",
    "Truly groundbreaking.",
    "REACT:👏:I'm in awe. Can't you tell?",
    "Such wisdom.",
    "DOUBLE:Impressive.||I'm speechless.",
    "Oh please, continue.",
    "How fascinating.",
    "REACT:🌟:Revolutionary thinking.",
    "What a concept.",
    "Genius at work.",
    "DOUBLE:Mind-blowing.||Truly.",
    "I'm shaking with excitement.",
    "Oh, the tragedy.",
    "REACT:😢:How will I ever recover?",
    "I'm devastated. Truly.",
    "Such courage.",
    "DOUBLE:A true visionary.||Nobel Prize when?",
    "How noble of you.",
    "My hero.",
    "REACT:👏:Wow. So. Impressive.",
    "WHISPER:Oh, how original.",
    "DOUBLE:Sarcasm!||How mature.",
    "STICKER:🫠🙃😑:The sarcasm is dripping and it's staining the carpet.",
    "WHISPER:I speak fluent sarcasm. You're barely conversational.",
    "DELETE:I'm deleting that out of secondhand embarrassment.",
    "DOUBLE:Oh, clever.||Not really, but sure.",
    "REACT:🎭:The wit. The delivery. The failure.",
]
