RESPONSES = (
    "WHISPER:That's suspicious.",
    "REACT:🤨:Hmm.",
    "DOUBLE:...||That was weird and you know it.",
    "STICKER:🤨📸📎:Caught in 4K.",
    "WHISPER:I'm keeping screenshots.",
    "REACT:📸:Evidence collected.",
    "DELETE:I'm going to pretend I didn't read that.",
    "DOUBLE:Say that again?||Actually, please don't.",
    "STICKER:😳🚨🚩:Red flags everywhere.",
    "WHISPER:I'm watching you closely now.",
    "That was... concerning.",
    "REACT:🚩:I've seen enough.",
    "DOUBLE:Filing that under 'alarming'.||Moving on.",
    "WHISPER:Don't think I won't remember this.",
    "DOUBLE:Sus.||Very sus.",
    "REACT:🤨:I'm watching you.",
    "I don't trust you.",
    "DOUBLE:Suspicious?||You're guilty.",
    "REACT:🕵️:Investigating your nonsense.",
    "You look guilty to me.",
)
