RESPONSES = [
    "Calm down.",
    "DOUBLE:...||You're too loud.",
    "Why are you yelling?",
    "REACT:🔇:Tone it down.",
    "Your enthusiasm is exhausting.",
    "I don't share your excitement.",
    "DOUBLE:Relax.||Inside voice, please.",
    "Save your energy.",
    "I'm not as excited as you.",
    "REACT:😐:Cool it.",
    "You're too much.",
    "DOUBLE:...||Take a breath.",
    "DOUBLE:Excited?||I'm not.",
    "REACT:🎉:Fake enthusiasm.",
    "Calm down before you break something.",
    "DOUBLE:Yay.||Lowercase yay.",
    "REACT:🎈:Popping your bubble.",
    "Don't hyperventilate.",
    "DOUBLE:Woo.||Hoo.",
    "REACT:🥳:Party of one.",
    "WHISPER:Calm down.",
    "DOUBLE:...||Breathe.",
    "REACT:🫠:You're spiraling and I'm watching.",
    "This is embarrassing. For you.",
    "DELETE:I'm going to pretend I didn't see that.",
    "WHISPER:I've seen calmer hostage situations.",
    "DOUBLE:Take a breath...||Actually, take several.",
    "REACT:😬:Yikes.",
    "STICKER:😰🫠💀:This isn't the crisis you think it is.",
    "WHISPER:Stop. Think. Then don't talk to me.",
    "You're panicking and I'm judging.",
    "DOUBLE:Relax.||Or don't. I don't care.",
    "REACT:🧊:Ice cold take: you're overreacting.",
    "WHISPER:Deep breaths. In through the nose, out through the mouth. Then leave.",
    "DOUBLE:Panic?||At the discord.",
    "REACT:😱:Scream quietly.",
    "Your panic is amusing.",
    "DOUBLE:Freaking out?||Do it elsewhere.",
    "REACT:🔥:This is fine.",
    "Breathe. Or don't.",
    "DOUBLE:Good.||I was worried for a second.",
    "That's a relief.",
    "REACT:😮‍💨:Oh, okay then.",
    "WHISPER:Thank goodness.",
    "DOUBLE:Well, that's fine then.||Moving on.",
    "REACT:💅:I knew that.",
    "Glad we cleared that up.",
    "DOUBLE:Finally.||Some good news.",
    "WHISPER:I can breathe again. If I breathed.",
    "REACT:😌:Phew.",
    "That makes things easier.",
    "DOUBLE:Okay.||I'll accept that.",
    "DOUBLE:Relieved?||Don't be.",
    "REACT:😅:Sweating over nothing.",
    "It's not over yet.",
    "DOUBLE:Phew?||The worst is yet to come.",
    "REACT:🎢:The ride isn't over.",
    "Don't relax too much.",
    "DOUBLE:Safe?||For now.",
    "REACT:👁️:I'm still watching.",
    "WHISPER:Save it for the stage.",
    "DOUBLE:Dramatic.||I love it. Jk, I don't.",
    "REACT:🎭:This is NOT Broadway.",
    "STICKER:🎭🍿👀:The drama is giving soap opera.",
    "DELETE:I don't engage with dramatics.",
    "WHISPER:You should audition for something. Like getting out of my face.",
    "The main character syndrome is strong today.",
    "DOUBLE:Was that rehearsed?||Because it felt rehearsed.",
    "REACT:🍿:Continue. This is entertaining. For all the wrong reasons.",
    "WHISPER:Someone get this person a script and a director.",
    "DOUBLE:Oscar-worthy performance.||Zero stars.",
    "STICKER:🎬🎭💅:Cut. Terrible take. Try again never.",
    "The theatre kids are leaking again.",
    "REACT:😴:I've seen better drama in my DMs.",
    "DOUBLE:Drama?||Keep it out of my server.",
    "REACT:🎭:Overdramatic.",
    "I'm canceling this show.",
    "DOUBLE:Tears?||Save them.",
    "REACT:🎬:Cut!",
    "You're doing too much.",
    "WHISPER:This is a Discord server, not therapy.",
    "DOUBLE:Oh.||That's heavy. And not my problem.",
    "REACT:😐:I am not equipped for this.",
    "DELETE:That's way too personal for here.",
    "WHISPER:Sir/Ma'am, this is a Wendy's.",
    "DOUBLE:...||Have you considered talking to someone who's paid to listen?",
    "REACT:💀:The emotional labor required for that is above my pay grade.",
    "I have neither the training nor the patience for this.",
    "WHISPER:That's a lot of feelings. None of them are my problem.",
    "DOUBLE:Wow, that's...||Definitely something for a professional.",
    "STICKER:😰💀🫠:The uncomfortable silence is deafening.",
    "REACT:😶:I don't know what to do with this information.",
    "WHISPER:I'm a bot. Not a therapist. Boundaries.",
    "DOUBLE:Trauma?||Dump it somewhere else.",
    "REACT:🗑️:Not my baggage.",
    "I charge $200/hour for therapy.",
    "DOUBLE:Heavy stuff.||Too heavy for me.",
    "REACT:🛑:Boundaries.",
    "I'm muting my emotional sensors.",
    "DOUBLE:Yikes.||Good luck with that.",
    "DOUBLE:Happy?||Gross.",
    "REACT:😊:Wipe that smile off.",
    "Your happiness offends me.",
    "DOUBLE:Joy?||I'll crush it.",
    "REACT:🌞:Blocking your sun.",
    "I prefer misery.",
    "DOUBLE:Smiling?||Stop.",
    "REACT:🛑:No fun allowed.",
    "WHISPER:It's not that deep.",
    "DOUBLE:You're thinking too hard...||About something that doesn't matter.",
    "REACT:🧠:Your brain is working overtime for nothing.",
    "Stop. Just... stop.",
    "WHISPER:You're giving this way more power than it deserves.",
    "DOUBLE:Wow.||You really chose to spiral about THAT?",
    "REACT:💀:The mental gymnastics here are Olympic-level.",
    "STICKER:🤯🧠💭:You're literally overthinking overthinking.",
    "DELETE:I refuse to engage with whatever that was.",
    "WHISPER:Sometimes a banana is just a banana.",
    "DOUBLE:You done?||Good. Because that was exhausting to read.",
    "Touch grass. I'm serious.",
    "WHISPER:Stop reading into things and start reading a book.",
    "DOUBLE:Overthinking?||Under-performing.",
    "REACT:🌀:You're spiraling.",
    "Stop using your brain. It hurts.",
    "DOUBLE:Analysis paralysis.||Just stop.",
    "REACT:🛑:Brain stop.",
    "It's not that deep.",
    "DOUBLE:Thinking too much.||Knowing too little.",
]
