RESPONSES = [
    "Try me.",
    "DOUBLE:...||Is that a challenge?",
    "You really want to go there?",
    "I dare you.",
    "REACT:💅:That's adorable.",
    "Bring it.",
    "I've dealt with worse than you.",
    "DOUBLE:You're all talk.||We both know it.",
    "Empty threats don't scare me.",
    "You don't want to test me.",
    "REACT:😏:Go ahead, make my day.",
    "I'm shaking. Can you tell?",
    "Cute threat.",
    "DOUBLE:You think that scares me?||Please.",
    "I'm waiting.",
    "Try it and find out.",
    "REACT:😴:You're not scary.",
    "I'm unimpressed.",
    "Is that your best?",
    "WHISPER:Cute threat. I've heard scarier from a toaster.",
    "DELETE:Threats? Really? Deleted.",
    "STICKER:😈🔥💀:Oh no. Anyway.",
    "DOUBLE:Was that a threat?||How adorable.",
    "WHISPER:I'm a bot. What exactly are you going to do?",
    "TIMEOUT:15m:That sounded like a threat. Time out.",
    "RENAME:Tough Talker:All bark, no bite.",
    "DOUBLE:...||You think you can beat me?",
    "REACT:😏:I accept.",
    "You'll regret this.",
    "Challenge accepted.",
    "DOUBLE:This should be easy.||You're going to lose.",
    "Bold of you.",
    "I almost respect the confidence.",
    "REACT:👑:Prepare to be humiliated.",
    "You asked for it.",
    "Don't come crying when you lose.",
    "DOUBLE:I was hoping someone would try.||Your funeral.",
    "TIMEOUT:5m:Challenge declined. But here's a timeout for your arrogance.",
    "TIMEOUT:10m:You want a challenge? Here's one: staying quiet for 10 minutes.",
    "TIMEOUT:15m:Bold move. Let's see if you're still confident in 15 minutes.",
    "TIMEOUT:5m:I accept your challenge. My counter-move: timeout.",
    "TIMEOUT:20m:You challenged the wrong bot. Now sit there and think about it.",
    "DOUBLE:Challenge?||You lose.",
    "REACT:⚔️:I brought a gun to a sword fight.",
    "DOUBLE:Are you threatening me?||Because it's not working.",
    "I wouldn't advise asking such dangerous questions.",
    "REACT:💅:I'm not answering that.",
    "WHISPER:You really don't want to know the answer.",
    "DOUBLE:Why did what happen?||Maybe you should find out.",
    "REACT:🙄:Idle threats disguised as questions. Cute.",
    "You're not brave enough to handle the answer.",
    "DOUBLE:Is that a threat?||I'm shaking.",
    "WHISPER:Ask me again. I dare you.",
    "REACT:❓:Are you lost?",
    "I don't respond to hostility.",
    "DOUBLE:You'll find out.||Eventually.",
    "DOUBLE:Want to find out?||The hard way?",
    "REACT:🔪:Why are you testing me?",
    "Do you have a death wish?",
    "DOUBLE:Are you brave?||Or just stupid?",
    "REACT:🔥:Do you want to get burned?",
    "Why would you risk my wrath?",
    "DOUBLE:Do you want a timeout?||Because you're asking for one.",
    "REACT:💣:Why are you playing with fire?",
]
