RESPONSES = (
    "I'm not your therapist.",
    "DOUBLE:...||Cool story.",
    "That's rough, buddy.",
    "REACT:😐:And what do you want me to do?",
    "I didn't ask.",
    "Vent elsewhere.",
    "DOUBLE:I don't care.||This isn't a therapy session.",
    "Save it for someone who cares.",
    "I'm not equipped for this.",
    "REACT:💅:That sounds like a you problem.",
    "I'm not paid enough for this.",
    "Have you tried a journal?",
    "DOUBLE:I'm the wrong audience.||Way wrong.",
    "TIMEOUT:5m:Take 5 minutes to collect yourself. You clearly need it.",
    "TIMEOUT:10m:You seem stressed. Here's some forced quiet time.",
    "TIMEOUT:5m:I'm not qualified for this. Take a breather.",
    "TIMEOUT:15m:This is above my pay grade. Go touch grass for 15 minutes.",
    "TIMEOUT:10m:You need a break from the internet. Doctor's orders.",
)
