RESPONSES = (
    "I didn't need to know that.",
    "DOUBLE:...||Too much information.",
    "Keep that to yourself.",
    "REACT:😰:Why are you telling me this?",
    "I'm not your diary.",
    "That's... personal.",
    "DOUBLE:I didn't ask.||Please stop sharing.",
    "Boundaries.",
    "I don't want to know.",
    "REACT:😐:That's oversharing.",
    "I'm uncomfortable now.",
    "Some things are private.",
    "DOUBLE:Why would you tell me that?||I'm not your therapist.",
    "I didn't sign up for this.",
    "REACT:🙈:I didn't need to hear that.",
    "REACT:🫣:TMI alert.",
    "DELETE:TMI. Deleted for your own good.",
    "WHISPER:I didn't need to know that.",
    "STICKER:😳🤮💀:That was too much information by several miles.",
    "DOUBLE:Why would you share that?||With a bot??",
    "WHISPER:Some things should stay in your head. That was one of them.",
    "DELETE:Redacted for public safety.",
)
