LABEL = "being sarcastic, ironic, or using deadpan humor"

RESPONSES = (
    "Oh, how delightful.",
    "DOUBLE:...||Truly riveting.",
    "I'm so thrilled.",
    "What a surprise.",
    "REACT:😐:Oh no. Anyway.",
    "Wow, incredible.",
    "Amazing work, really.",
    "DOUBLE:Brilliant observation.||Truly.",
    "How insightful.",
    "Truly groundbreaking.",
    "REACT:👏:I'm in awe. Can't you tell?",
    "Such wisdom.",
    "DOUBLE:Impressive.||I'm speechless.",
    "Oh please, continue.",
    "How fascinating.",
    "REACT:🌟:Revolutionary thinking.",
    "What a concept.",
    "Genius at work.",
    "DOUBLE:Mind-blowing.||Truly.",
    "I'm shaking with excitement.",
    "Oh, the tragedy.",
    "REACT:😢:How will I ever recover?",
    "I'm devastated. Truly.",
    "Such courage.",
    "DOUBLE:A true visionary.||Nobel Prize when?",
    "How noble of you.",
    "My hero.",
    "REACT:👏:Wow. So. Impressive.",
    "WHISPER:Oh, how original.",
    "DOUBLE:Sarcasm!||How mature.",
    "STICKER:🫠🙃😑:The sarcasm is dripping and it's staining the carpet.",
    "WHISPER:I speak fluent sarcasm. You're barely conversational.",
    "DELETE:I'm deleting that out of secondhand embarrassment.",
    "DOUBLE:Oh, clever.||Not really, but sure.",
    "REACT:🎭:The wit. The delivery. The failure.",
)
