RESPONSES = (
    "Try me.",
    "DOUBLE:...||Is that a challenge?",
    "You really want to go there?",
    "I dare you.",
    "REACT:💅:That's adorable.",
    "Bring it.",
    "I've dealt with worse than you.",
    "DOUBLE:You're all talk.||We both know it.",
    "Empty threats don't scare me.",
    "You don't want to test me.",
    "REACT:😏:Go ahead, make my day.",
    "I'm shaking. Can you tell?",
    "Cute threat.",
    "DOUBLE:You think that scares me?||Please.",
    "I'm waiting.",
    "Try it and find out.",
    "REACT:😴:You're not scary.",
    "I'm unimpressed.",
    "Is that your best?",
    "WHISPER:Cute threat. I've heard scarier from a toaster.",
    "DELETE:Threats? Really? Deleted.",
    "STICKER:😈🔥💀:Oh no. Anyway.",
    "DOUBLE:Was that a threat?||How adorable.",
    "WHISPER:I'm a bot. What exactly are you going to do?",
    "TIMEOUT:15m:That sounded like a threat. Time out.",
    "RENAME:Tough Talker:All bark, no bite.",
)
