RESPONSES = [
    "Cry me a river.",
    "DOUBLE:Oh no.||Anyway.",
    "That's tough.",
    "REACT:💅:Deal with it.",
    "I don't care about your problems.",
    "Not my problem.",
    "DOUBLE:That's life.||Boohoo.",
    "Do I look like customer service?",
    "Take it up with someone who cares.",
    "REACT:😐:You'll survive.",
    "Suck it up.",
    "Welcome to reality.",
    "DOUBLE:Nobody cares.||Get over it.",
    "REACT:😭:Cry about it.",
    "REACT:🍼:Here's your bottle.",
    "DOUBLE:Complaining?||File a ticket. I'll delete it.",
    "REACT:📝:Noted. And ignored.",
    "I'm not HR.",
    "DOUBLE:Whining?||Stop.",
    "REACT:🙉:I can't hear you.",
    "I'm not your therapist.",
    "DOUBLE:...||Cool story.",
    "That's rough, buddy.",
    "REACT:😐:And what do you want me to do?",
    "I didn't ask.",
    "Vent elsewhere.",
    "DOUBLE:I don't care.||This isn't a therapy session.",
    "Save it for someone who cares.",
    "I'm not equipped for this.",
    "REACT:💅:That sounds like a you problem.",
    "I'm not paid enough for this.",
    "Have you tried a journal?",
    "DOUBLE:I'm the wrong audience.||Way wrong.",
    "TIMEOUT:5m:Take 5 minutes to collect yourself. You clearly need it.",
    "TIMEOUT:10m:You seem stressed. Here's some forced quiet time.",
    "TIMEOUT:5m:I'm not qualified for this. Take a breather.",
    "TIMEOUT:15m:This is above my pay grade. Go touch grass for 15 minutes.",
    "TIMEOUT:10m:You need a break from the internet. Doctor's orders.",
    "DOUBLE:Venting?||I'm an airlock. Goodbye.",
    "REACT:🌬️:Blowing off steam.",
    "DOUBLE:Jealousy?||It's not a good look.",
    "REACT:💅:The envy is showing, bestie.",
    "Imagine being jealous in this economy.",
    "Stay pressed.",
    "That sounds like a personal problem.",
    "DOUBLE:*sips tea*||Couldn't be me.",
    "Main character energy doesn't need jealousy.",
    "REACT:😌:I'd be jealous of me too.",
    "DOUBLE:Jealous?||You should be.",
    "REACT:💚:Green is not your color.",
    "Envy looks terrible on you.",
    "DOUBLE:Want what I have?||You can't.",
    "REACT:🐍:Hiss hiss.",
    "I thrive on your jealousy.",
    "DOUBLE:Bitter?||Have some sugar.",
    "REACT:🍋:Sucking on lemons.",
    "I'd be jealous of me too.",
    "DOUBLE:Stay mad.||And stay jealous.",
    "REACT:💅:I'm better. Deal with it.",
    "Jealousy is a disease. Get well soon.",
    "WHISPER:I can feel the passive aggression from here.",
    "DOUBLE:Oh, that was subtle.||And by subtle I mean pathetically transparent.",
    "REACT:😊:I see what you did there. And I don't care.",
    "STICKER:🙃😊💅:My passive-aggressive senses are tingling.",
    "WHISPER:Say what you mean or say nothing at all.",
    "You can just say you're upset. It's okay. I still won't care.",
    "DOUBLE:That was almost clever...||Almost.",
    "REACT:🔪:Cute. Real cute.",
    "WHISPER:The subtext isn't as hidden as you think.",
    "If you have something to say, say it with your chest.",
    "DOUBLE:I love how you think that's subtle.||Spoiler: it's not.",
    "REACT:💅:Noted. Not acting on it. But noted.",
    "STICKER:🙄😑😒:The vibes are... tense.",
    "WHISPER:I'm choosing to ignore the tone. Be grateful.",
    "DOUBLE:Passive?||Be aggressive.",
    "REACT:🔪:I see that knife.",
    "I can be more passive aggressive. Watch.",
    "DOUBLE:Sure.||Fine. Okay.",
    "REACT:😊:Smiling through the hate.",
    "Bless your heart.",
    "DOUBLE:Mad?||Stay mad.",
    "REACT:🤬:Watch your blood pressure.",
    "Your anger amuses me.",
    "DOUBLE:Furious?||I love it.",
    "REACT:🍿:Eating popcorn while you rage.",
]
