<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sonarr.Application\Sonarr.Application.csproj" />
    <ProjectReference Include="..\..\src\Sonarr.Infrastructure\Sonarr.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Sonarr.Bot\Sonarr.Bot.csproj" />
    <ProjectReference Include="..\..\src\Sonarr.Migrator\Sonarr.Migrator.csproj" />
  </ItemGroup>

</Project>